#!/bin/sh
# Script de inicialização feito por Protimus.

PATH=./:$PATH

L_SRV=login-server_sql
C_SRV=char-server_sql
M_SRV=map-server_sql

print_start() {
echo "brAthena Iniciando..."
echo "            brAthena (c) 2009 ~ 2012"
echo ""
echo "checando..."
}

check_files() {

    for i in ${L_SRV} ${C_SRV} ${M_SRV}
    do
        if [ ! -f ./$i ]; then
            echo "$i Não existe ou não pode ser executado."
            echo "Desligado! Verifique seu compilador."
            exit 1;
        fi
    done

#    more << EOF
echo "Checagem completa."
#EOF
}
    

case $1 in
    'start')
        print_start
        check_files
		
		exec ./${L_SRV}& 
		exec ./${C_SRV}& 
		exec ./${M_SRV}& 
        echo "O brAthena foi iniciado!"
;;
    'stop')
        ps ax | grep -E "${L_SRV}|${C_SRV}|${M_SRV}" | awk '{print $1}' | xargs kill
;;
	'restart')
        $0 stop
        $0 start
;;
    'gdb')
        print_start
        check_files
		
		ulimit -c unlimited
		exec ./${L_SRV}& 
		exec ./${C_SRV}& 
		gdb map-server_sql map-server_sql.core
        echo "O brAthena foi iniciado em modo de depuração!"
		gdb> bt full
;;
    *)
        echo "Modo de usar: brathena-start { start | stop | restart | gdb}"
;;
esac