--
-- Estrutura para a tabela `item_violetbox`
--  

CREATE TABLE IF NOT EXISTS `item_violetbox` (
  `GroupID` tinyint(1) NOT NULL default '0',
  `ItemID` smallint(2) unsigned NOT NULL default '0',
  `Rate` tinyint(1) unsigned NOT NULL default '0',
   PRIMARY KEY (`GroupID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*
 Itens da Velha Caixa Roxa.
 Descrição: Responsável pelos itens obtidos pela Velha Caixa Roxa.
 Cabeçalho: REPLACE INTO `item_violetbox` VALUES ('ID do Grupo de Itens, ID do Item, Chance de Sucesso');
*/

REPLACE INTO `item_violetbox` VALUES (2,501,14);	-- 'Poção Vermelha'
REPLACE INTO `item_violetbox` VALUES (2,502,14);	-- 'Poção Laranja'
REPLACE INTO `item_violetbox` VALUES (2,503,14);	-- 'Poção Amarela'
REPLACE INTO `item_violetbox` VALUES (2,504,14);	-- 'Poção Branca'
REPLACE INTO `item_violetbox` VALUES (2,505,14);	-- 'Poção Azul'
REPLACE INTO `item_violetbox` VALUES (2,506,14);	-- 'Poção Verde'
REPLACE INTO `item_violetbox` VALUES (2,507,14);	-- 'Erva Vermelha'
REPLACE INTO `item_violetbox` VALUES (2,508,14);	-- 'Erva Amarela'
REPLACE INTO `item_violetbox` VALUES (2,509,14);	-- 'Erva Branca'
REPLACE INTO `item_violetbox` VALUES (2,510,14);	-- 'Erva Azul'
REPLACE INTO `item_violetbox` VALUES (2,511,14);	-- 'Erva Verde'
REPLACE INTO `item_violetbox` VALUES (2,512,14);	-- 'Maçã'
REPLACE INTO `item_violetbox` VALUES (2,513,14);	-- 'Banana'
REPLACE INTO `item_violetbox` VALUES (2,514,14);	-- 'Uvas'
REPLACE INTO `item_violetbox` VALUES (2,515,14);	-- 'Cenoura'
REPLACE INTO `item_violetbox` VALUES (2,516,14);	-- 'Batata Doce'
REPLACE INTO `item_violetbox` VALUES (2,517,14);	-- 'Carne'
REPLACE INTO `item_violetbox` VALUES (2,518,14);	-- 'Mel'
REPLACE INTO `item_violetbox` VALUES (2,519,14);	-- 'Leite'
REPLACE INTO `item_violetbox` VALUES (2,520,14);	-- 'Folha de Hinalle'
REPLACE INTO `item_violetbox` VALUES (2,521,14);	-- 'Folha de Aloe'
REPLACE INTO `item_violetbox` VALUES (2,522,14);	-- 'Mastela'
REPLACE INTO `item_violetbox` VALUES (2,523,14);	-- 'Água Benta'
REPLACE INTO `item_violetbox` VALUES (2,525,14);	-- 'Panacéia'
REPLACE INTO `item_violetbox` VALUES (2,526,14);	-- 'Geléia Real'
REPLACE INTO `item_violetbox` VALUES (2,528,14);	-- 'Ração para Monstros'
REPLACE INTO `item_violetbox` VALUES (2,529,14);	-- 'Bala'
REPLACE INTO `item_violetbox` VALUES (2,530,14);	-- 'Bengala Doce'
REPLACE INTO `item_violetbox` VALUES (2,531,14);	-- 'Suco de Maçã'
REPLACE INTO `item_violetbox` VALUES (2,532,14);	-- 'Suco de Banana'
REPLACE INTO `item_violetbox` VALUES (2,533,14);	-- 'Suco de Uva'
REPLACE INTO `item_violetbox` VALUES (2,534,14);	-- 'Suco de Cenoura'
REPLACE INTO `item_violetbox` VALUES (2,535,14);	-- 'Abóbora'
REPLACE INTO `item_violetbox` VALUES (2,536,14);	-- 'Sorvete'
REPLACE INTO `item_violetbox` VALUES (2,537,14);	-- 'Ração para Bichinho'
REPLACE INTO `item_violetbox` VALUES (2,538,14);	-- 'Biscoito de Gengibre'
REPLACE INTO `item_violetbox` VALUES (2,539,14);	-- 'Pedaço de Bolo'
REPLACE INTO `item_violetbox` VALUES (2,544,14);	-- 'Peixe Cru'
REPLACE INTO `item_violetbox` VALUES (2,545,14);	-- 'Poção Vermelha Compacta'
REPLACE INTO `item_violetbox` VALUES (2,546,14);	-- 'Poção Amarela Compacta'
REPLACE INTO `item_violetbox` VALUES (2,547,14);	-- 'Poção Branca Compacta'
REPLACE INTO `item_violetbox` VALUES (2,548,14);	-- 'Queijo'
REPLACE INTO `item_violetbox` VALUES (2,549,14);	-- 'Batata Doce Assada'
REPLACE INTO `item_violetbox` VALUES (2,550,14);	-- 'Bolinhos de Arroz'
REPLACE INTO `item_violetbox` VALUES (2,551,14);	-- 'Sushi'
REPLACE INTO `item_violetbox` VALUES (2,553,14);	-- 'Pão de Carne'
REPLACE INTO `item_violetbox` VALUES (2,555,14);	-- 'Bolinho de Arroz'
REPLACE INTO `item_violetbox` VALUES (2,558,14);	-- 'Chocolate'
REPLACE INTO `item_violetbox` VALUES (2,561,14);	-- 'Chocolate Branco'
REPLACE INTO `item_violetbox` VALUES (2,601,14);	-- 'Asa de Mosca'
REPLACE INTO `item_violetbox` VALUES (2,602,14);	-- 'Asa de Borboleta'
REPLACE INTO `item_violetbox` VALUES (2,603,614);	-- 'Velha Caixa Azul'
REPLACE INTO `item_violetbox` VALUES (2,604,214);	-- 'Galho Seco'
REPLACE INTO `item_violetbox` VALUES (2,605,14);	-- 'Analgésico'
REPLACE INTO `item_violetbox` VALUES (2,606,14);	-- 'Aloe Vera'
REPLACE INTO `item_violetbox` VALUES (2,607,14);	-- 'Fruto de Yggdrasil'
REPLACE INTO `item_violetbox` VALUES (2,608,14);	-- 'Semente de Yggdrasil'
REPLACE INTO `item_violetbox` VALUES (2,609,14);	-- 'Amuleto'
REPLACE INTO `item_violetbox` VALUES (2,610,14);	-- 'Folha de Yggdrasil'
REPLACE INTO `item_violetbox` VALUES (2,611,14);	-- 'Lupa'
REPLACE INTO `item_violetbox` VALUES (2,612,14);	-- 'Mini-Fornalha'
REPLACE INTO `item_violetbox` VALUES (2,613,14);	-- 'Martelo de Ferro'
REPLACE INTO `item_violetbox` VALUES (2,614,14);	-- 'Martelo de Ouro'
REPLACE INTO `item_violetbox` VALUES (2,615,14);	-- 'Martelo de Oridecon'
REPLACE INTO `item_violetbox` VALUES (2,616,1);	-- 'Velho Álbum de Cartas'
REPLACE INTO `item_violetbox` VALUES (2,617,103);	-- 'Velha Caixa Roxa'
REPLACE INTO `item_violetbox` VALUES (2,618,14);	-- 'Pergaminho Desgastado'
REPLACE INTO `item_violetbox` VALUES (2,619,14);	-- 'Maçã Verde'
REPLACE INTO `item_violetbox` VALUES (2,620,14);	-- 'Suco de Laranja'
REPLACE INTO `item_violetbox` VALUES (2,621,14);	-- 'Erva Amarga'
REPLACE INTO `item_violetbox` VALUES (2,622,14);	-- 'Cenoura Arco-Íris'
REPLACE INTO `item_violetbox` VALUES (2,623,14);	-- 'Minhoca Boa-Pinta'
REPLACE INTO `item_violetbox` VALUES (2,624,14);	-- 'Peixe Podre'
REPLACE INTO `item_violetbox` VALUES (2,625,14);	-- 'Ferro Enferrujado'
REPLACE INTO `item_violetbox` VALUES (2,626,14);	-- 'Suco de Monstro'
REPLACE INTO `item_violetbox` VALUES (2,627,14);	-- 'Leite Doce'
REPLACE INTO `item_violetbox` VALUES (2,628,14);	-- 'Osso Seco'
REPLACE INTO `item_violetbox` VALUES (2,629,14);	-- 'Flor Cantante'
REPLACE INTO `item_violetbox` VALUES (2,630,14);	-- 'Musgo Encharcado'
REPLACE INTO `item_violetbox` VALUES (2,631,14);	-- 'Erva Letal'
REPLACE INTO `item_violetbox` VALUES (2,632,14);	-- 'Minhoca Gorducha'
REPLACE INTO `item_violetbox` VALUES (2,633,14);	-- 'Batata Assada'
REPLACE INTO `item_violetbox` VALUES (2,634,14);	-- 'Banana Tropical'
REPLACE INTO `item_violetbox` VALUES (2,635,14);	-- 'Horror da Tribo'
REPLACE INTO `item_violetbox` VALUES (2,636,14);	-- 'Sem Destinatário'
REPLACE INTO `item_violetbox` VALUES (2,637,14);	-- 'Vassoura Velha'
REPLACE INTO `item_violetbox` VALUES (2,638,14);	-- 'Faca de Prata da Castidade'
REPLACE INTO `item_violetbox` VALUES (2,639,14);	-- 'Bracelete da Obediência'
REPLACE INTO `item_violetbox` VALUES (2,640,14);	-- 'Pedra Brilhante'
REPLACE INTO `item_violetbox` VALUES (2,641,14);	-- 'Contratos das Sombras'
REPLACE INTO `item_violetbox` VALUES (2,642,14);	-- 'Livro do Diabo'
REPLACE INTO `item_violetbox` VALUES (2,643,14);	-- 'Incubadora'
REPLACE INTO `item_violetbox` VALUES (2,644,114);	-- 'Caixa de Presente'
REPLACE INTO `item_violetbox` VALUES (2,645,14);	-- 'Poção da Concentração'
REPLACE INTO `item_violetbox` VALUES (2,656,14);	-- 'Poção do Despertar'
REPLACE INTO `item_violetbox` VALUES (2,657,14);	-- 'Poção da Fúria Selvagem'
REPLACE INTO `item_violetbox` VALUES (2,659,14);	-- 'Coração Apaixonado'
REPLACE INTO `item_violetbox` VALUES (2,663,14);	-- 'Ovos de Chocolate Branco'
REPLACE INTO `item_violetbox` VALUES (2,664,14);	-- 'Caixa de Presente 1'
REPLACE INTO `item_violetbox` VALUES (2,665,14);	-- 'Caixa de Presente 2'
REPLACE INTO `item_violetbox` VALUES (2,666,14);	-- 'Caixa de Presente 3'
REPLACE INTO `item_violetbox` VALUES (2,667,14);	-- 'Caixa de Presente 4'
REPLACE INTO `item_violetbox` VALUES (2,668,14);	-- 'Envelope Vermelho'
REPLACE INTO `item_violetbox` VALUES (2,678,14);	-- 'Garrafa de Veneno'
REPLACE INTO `item_violetbox` VALUES (2,679,14);	-- 'Pílula Dourada'
REPLACE INTO `item_violetbox` VALUES (2,701,14);	-- 'Armadilha para Insetos'
REPLACE INTO `item_violetbox` VALUES (2,702,14);	-- 'Sangue de Animal'
REPLACE INTO `item_violetbox` VALUES (2,703,14);	-- 'Hinalle'
REPLACE INTO `item_violetbox` VALUES (2,704,14);	-- 'Aloés'
REPLACE INTO `item_violetbox` VALUES (2,705,14);	-- 'Trevo'
REPLACE INTO `item_violetbox` VALUES (2,706,14);	-- 'Trevo de Quatro Folhas'
REPLACE INTO `item_violetbox` VALUES (2,707,14);	-- 'Planta da Melodia'
REPLACE INTO `item_violetbox` VALUES (2,708,14);	-- 'Menta'
REPLACE INTO `item_violetbox` VALUES (2,710,14);	-- 'Flor das Ilusões'
REPLACE INTO `item_violetbox` VALUES (2,711,14);	-- 'Broto'
REPLACE INTO `item_violetbox` VALUES (2,712,14);	-- 'Flor'
REPLACE INTO `item_violetbox` VALUES (2,713,14);	-- 'Garrafa Vazia'
REPLACE INTO `item_violetbox` VALUES (2,714,14);	-- 'Emperium'
REPLACE INTO `item_violetbox` VALUES (2,715,14);	-- 'Gema Amarela'
REPLACE INTO `item_violetbox` VALUES (2,716,14);	-- 'Gema Vermelha'
REPLACE INTO `item_violetbox` VALUES (2,717,14);	-- 'Gema Azul'
REPLACE INTO `item_violetbox` VALUES (2,718,14);	-- 'Granada'
REPLACE INTO `item_violetbox` VALUES (2,719,14);	-- 'Ametista'
REPLACE INTO `item_violetbox` VALUES (2,720,14);	-- 'Aquamarina'
REPLACE INTO `item_violetbox` VALUES (2,721,14);	-- 'Esmeralda'
REPLACE INTO `item_violetbox` VALUES (2,722,14);	-- 'Pérola'
REPLACE INTO `item_violetbox` VALUES (2,723,14);	-- 'Rubi'
REPLACE INTO `item_violetbox` VALUES (2,724,14);	-- 'Rubi Amaldiçoado'
REPLACE INTO `item_violetbox` VALUES (2,725,14);	-- 'Peridoto'
REPLACE INTO `item_violetbox` VALUES (2,726,14);	-- 'Safira'
REPLACE INTO `item_violetbox` VALUES (2,727,14);	-- 'Opala'
REPLACE INTO `item_violetbox` VALUES (2,728,14);	-- 'Topázio'
REPLACE INTO `item_violetbox` VALUES (2,729,14);	-- 'Zircônio'
REPLACE INTO `item_violetbox` VALUES (2,730,14);	-- 'Diamante de 1 quilate'
REPLACE INTO `item_violetbox` VALUES (2,731,14);	-- 'Diamante de 2 quilates'
REPLACE INTO `item_violetbox` VALUES (2,732,14);	-- 'Diamante de 3 quilates'
REPLACE INTO `item_violetbox` VALUES (2,733,14);	-- 'Diamante Rachado'
REPLACE INTO `item_violetbox` VALUES (2,734,14);	-- 'Moldura Vermelha'
REPLACE INTO `item_violetbox` VALUES (2,735,14);	-- 'Chung Jah'
REPLACE INTO `item_violetbox` VALUES (2,736,14);	-- 'Prato de Porcelana'
REPLACE INTO `item_violetbox` VALUES (2,737,14);	-- 'Concha Preta'
REPLACE INTO `item_violetbox` VALUES (2,738,14);	-- 'Estojo de Lápis'
REPLACE INTO `item_violetbox` VALUES (2,739,14);	-- 'Batom'
REPLACE INTO `item_violetbox` VALUES (2,740,14);	-- 'Boneco de Pelúcia'
REPLACE INTO `item_violetbox` VALUES (2,741,14);	-- 'Boneco de Poring'
REPLACE INTO `item_violetbox` VALUES (2,742,14);	-- 'Boneco de Chonchon'
REPLACE INTO `item_violetbox` VALUES (2,743,14);	-- 'Boneco de Esporo'
REPLACE INTO `item_violetbox` VALUES (2,744,14);	-- 'Buquê'
REPLACE INTO `item_violetbox` VALUES (2,745,14);	-- 'Buquê de Casamento'
REPLACE INTO `item_violetbox` VALUES (2,746,14);	-- 'Bolinha de Gude'
REPLACE INTO `item_violetbox` VALUES (2,747,14);	-- 'Espelho de Cristal'
REPLACE INTO `item_violetbox` VALUES (2,748,14);	-- 'Rosa Eterna'
REPLACE INTO `item_violetbox` VALUES (2,749,14);	-- 'Rosa de Gelo'
REPLACE INTO `item_violetbox` VALUES (2,750,14);	-- 'Boneco de Bafomé'
REPLACE INTO `item_violetbox` VALUES (2,751,14);	-- 'Boneco de Osíris'
REPLACE INTO `item_violetbox` VALUES (2,752,14);	-- 'Boneco de Rocker'
REPLACE INTO `item_violetbox` VALUES (2,753,14);	-- 'Boneco de Yoyo'
REPLACE INTO `item_violetbox` VALUES (2,754,14);	-- 'Boneco de Fumacento'
REPLACE INTO `item_violetbox` VALUES (2,756,14);	-- 'Minério de Oridecon'
REPLACE INTO `item_violetbox` VALUES (2,757,14);	-- 'Minério de Elunium'
REPLACE INTO `item_violetbox` VALUES (2,901,14);	-- 'Trança'
REPLACE INTO `item_violetbox` VALUES (2,902,14);	-- 'Raiz de Árvore'
REPLACE INTO `item_violetbox` VALUES (2,903,14);	-- 'Língua de Réptil'
REPLACE INTO `item_violetbox` VALUES (2,904,14);	-- 'Cauda de Escorpião'
REPLACE INTO `item_violetbox` VALUES (2,905,14);	-- 'Caule'
REPLACE INTO `item_violetbox` VALUES (2,906,14);	-- 'Escama Afiada'
REPLACE INTO `item_violetbox` VALUES (2,907,14);	-- 'Resina'
REPLACE INTO `item_violetbox` VALUES (2,908,14);	-- 'Ova de Sapo'
REPLACE INTO `item_violetbox` VALUES (2,909,14);	-- 'Jellopy'
REPLACE INTO `item_violetbox` VALUES (2,910,14);	-- 'Garleta'
REPLACE INTO `item_violetbox` VALUES (2,911,14);	-- 'Scell'
REPLACE INTO `item_violetbox` VALUES (2,912,14);	-- 'Zargônio'
REPLACE INTO `item_violetbox` VALUES (2,913,14);	-- 'Dente de Morcego'
REPLACE INTO `item_violetbox` VALUES (2,914,14);	-- 'Felpa'
REPLACE INTO `item_violetbox` VALUES (2,915,14);	-- 'Crisálida'
REPLACE INTO `item_violetbox` VALUES (2,916,14);	-- 'Plumas de Ave'
REPLACE INTO `item_violetbox` VALUES (2,917,14);	-- 'Garra de Ave'
REPLACE INTO `item_violetbox` VALUES (2,918,14);	-- 'Pata Pegajosa'
REPLACE INTO `item_violetbox` VALUES (2,919,14);	-- 'Couro de Animal'
REPLACE INTO `item_violetbox` VALUES (2,920,14);	-- 'Garra de Lobo'
REPLACE INTO `item_violetbox` VALUES (2,921,14);	-- 'Esporo de Cogumelo'
REPLACE INTO `item_violetbox` VALUES (2,922,14);	-- 'Presa de Orc'
REPLACE INTO `item_violetbox` VALUES (2,923,14);	-- 'Chifre Diabólico'
REPLACE INTO `item_violetbox` VALUES (2,924,14);	-- 'Pó de Borboleta'
REPLACE INTO `item_violetbox` VALUES (2,925,14);	-- 'Bico de Ave'
REPLACE INTO `item_violetbox` VALUES (2,926,14);	-- 'Escamas de Cobra'
REPLACE INTO `item_violetbox` VALUES (2,928,14);	-- 'Antenas de Inseto'
REPLACE INTO `item_violetbox` VALUES (2,929,14);	-- 'Coração Imortal'
REPLACE INTO `item_violetbox` VALUES (2,930,14);	-- 'Bandagem Estragada'
REPLACE INTO `item_violetbox` VALUES (2,931,14);	-- 'Amuleto dos Orcs'
REPLACE INTO `item_violetbox` VALUES (2,932,14);	-- 'Osso'
REPLACE INTO `item_violetbox` VALUES (2,934,14);	-- 'Espólio'
REPLACE INTO `item_violetbox` VALUES (2,935,14);	-- 'Casca'
REPLACE INTO `item_violetbox` VALUES (2,936,14);	-- 'Casca Escamada'
REPLACE INTO `item_violetbox` VALUES (2,937,14);	-- 'Canino Venenoso'
REPLACE INTO `item_violetbox` VALUES (2,938,14);	-- 'Muco Pegajoso'
REPLACE INTO `item_violetbox` VALUES (2,939,14);	-- 'Ferrão de Abelha'
REPLACE INTO `item_violetbox` VALUES (2,940,14);	-- 'Perna de Gafanhoto'
REPLACE INTO `item_violetbox` VALUES (2,941,14);	-- 'Argola'
REPLACE INTO `item_violetbox` VALUES (2,942,14);	-- 'Cauda de Yoyo'
REPLACE INTO `item_violetbox` VALUES (2,943,14);	-- 'Casca Rija'
REPLACE INTO `item_violetbox` VALUES (2,944,14);	-- 'Ferradura'
REPLACE INTO `item_violetbox` VALUES (2,945,14);	-- 'Folha de Fumacento'
REPLACE INTO `item_violetbox` VALUES (2,946,14);	-- 'Casco de Caramujo'
REPLACE INTO `item_violetbox` VALUES (2,947,14);	-- 'Chifre'
REPLACE INTO `item_violetbox` VALUES (2,948,14);	-- 'Pata de Urso'
REPLACE INTO `item_violetbox` VALUES (2,949,14);	-- 'Pluma'
REPLACE INTO `item_violetbox` VALUES (2,950,14);	-- 'Coração de Sereia'
REPLACE INTO `item_violetbox` VALUES (2,951,14);	-- 'Nadadeira'
REPLACE INTO `item_violetbox` VALUES (2,952,14);	-- 'Espinho de Cacto'
REPLACE INTO `item_violetbox` VALUES (2,953,14);	-- 'Coração de Pedra'
REPLACE INTO `item_violetbox` VALUES (2,954,14);	-- 'Escama Brilhante'
REPLACE INTO `item_violetbox` VALUES (2,955,14);	-- 'Pele de Verme'
REPLACE INTO `item_violetbox` VALUES (2,956,14);	-- 'Guelra'
REPLACE INTO `item_violetbox` VALUES (2,957,14);	-- 'Unha Apodrecida'
REPLACE INTO `item_violetbox` VALUES (2,958,14);	-- 'Mandíbula Horrenda'
REPLACE INTO `item_violetbox` VALUES (2,959,14);	-- 'Escama Fétida'
REPLACE INTO `item_violetbox` VALUES (2,960,14);	-- 'Garra de Crustáceo'
REPLACE INTO `item_violetbox` VALUES (2,961,14);	-- 'Concha'
REPLACE INTO `item_violetbox` VALUES (2,962,14);	-- 'Tentáculo'
REPLACE INTO `item_violetbox` VALUES (2,963,14);	-- 'Escama Aquática'
REPLACE INTO `item_violetbox` VALUES (2,964,14);	-- 'Casco de Caranguejo'
REPLACE INTO `item_violetbox` VALUES (2,965,14);	-- 'Casco de Ostra'
REPLACE INTO `item_violetbox` VALUES (2,966,14);	-- 'Carne de Ostra'
REPLACE INTO `item_violetbox` VALUES (2,967,14);	-- 'Casco de Tartaruga'
REPLACE INTO `item_violetbox` VALUES (2,968,14);	-- 'Insígnia do Herói'
REPLACE INTO `item_violetbox` VALUES (2,969,14);	-- 'Ouro'
REPLACE INTO `item_violetbox` VALUES (2,970,14);	-- 'Álcool'
REPLACE INTO `item_violetbox` VALUES (2,971,14);	-- 'Detrimindexta'
REPLACE INTO `item_violetbox` VALUES (2,972,14);	-- 'Karvodailnirol'
REPLACE INTO `item_violetbox` VALUES (2,973,14);	-- 'Antígeno'
REPLACE INTO `item_violetbox` VALUES (2,974,14);	-- 'Mistura'
REPLACE INTO `item_violetbox` VALUES (2,975,14);	-- 'Tintura Vermelha'
REPLACE INTO `item_violetbox` VALUES (2,976,14);	-- 'Tintura Amarela'
REPLACE INTO `item_violetbox` VALUES (2,978,14);	-- 'Tintura Azul'
REPLACE INTO `item_violetbox` VALUES (2,979,14);	-- 'Tintura Verde'
REPLACE INTO `item_violetbox` VALUES (2,980,14);	-- 'Tintura Laranja'
REPLACE INTO `item_violetbox` VALUES (2,981,14);	-- 'Tintura Violeta'
REPLACE INTO `item_violetbox` VALUES (2,982,14);	-- 'Tintura Branca'
REPLACE INTO `item_violetbox` VALUES (2,983,14);	-- 'Tintura Preta'
REPLACE INTO `item_violetbox` VALUES (2,984,14);	-- 'Oridecon'
REPLACE INTO `item_violetbox` VALUES (2,985,14);	-- 'Elunium'
REPLACE INTO `item_violetbox` VALUES (2,986,14);	-- 'Bigorna'
REPLACE INTO `item_violetbox` VALUES (2,987,14);	-- 'Bigorna de Oridecon'
REPLACE INTO `item_violetbox` VALUES (2,988,14);	-- 'Bigorna de Ouro'
REPLACE INTO `item_violetbox` VALUES (2,989,14);	-- 'Bigorna de Emperium'
REPLACE INTO `item_violetbox` VALUES (2,990,14);	-- 'Sangue Escarlate'
REPLACE INTO `item_violetbox` VALUES (2,991,14);	-- 'Cristal Azul'
REPLACE INTO `item_violetbox` VALUES (2,992,14);	-- 'Frescor do Vento'
REPLACE INTO `item_violetbox` VALUES (2,993,14);	-- 'Vida Verdejante'
REPLACE INTO `item_violetbox` VALUES (2,994,14);	-- 'Coração Flamejante'
REPLACE INTO `item_violetbox` VALUES (2,995,14);	-- 'Gelo Místico'
REPLACE INTO `item_violetbox` VALUES (2,996,14);	-- 'Vento Bruto'
REPLACE INTO `item_violetbox` VALUES (2,997,14);	-- 'Natureza Grandiosa'
REPLACE INTO `item_violetbox` VALUES (2,998,14);	-- 'Ferro'
REPLACE INTO `item_violetbox` VALUES (2,999,14);	-- 'Aço'
REPLACE INTO `item_violetbox` VALUES (2,1000,14);	-- 'Fragmento Estelar'
REPLACE INTO `item_violetbox` VALUES (2,1001,14);	-- 'Poeira Estelar'
REPLACE INTO `item_violetbox` VALUES (2,1002,14);	-- 'Minério de Ferro'
REPLACE INTO `item_violetbox` VALUES (2,1003,14);	-- 'Carvão'
REPLACE INTO `item_violetbox` VALUES (2,1004,14);	-- 'Insígnia da Cavalaria'
REPLACE INTO `item_violetbox` VALUES (2,1005,14);	-- 'Martelo de Ferreiro'
REPLACE INTO `item_violetbox` VALUES (2,1006,14);	-- 'Grimório Antigo'
REPLACE INTO `item_violetbox` VALUES (2,1007,14);	-- 'Colar da Sabedoria'
REPLACE INTO `item_violetbox` VALUES (2,1008,14);	-- 'Colar do Oblívio'
REPLACE INTO `item_violetbox` VALUES (2,1009,14);	-- 'Mão Divina'
REPLACE INTO `item_violetbox` VALUES (2,1010,14);	-- 'Fracon'
REPLACE INTO `item_violetbox` VALUES (2,1011,14);	-- 'Emveretarcon'
REPLACE INTO `item_violetbox` VALUES (2,1012,14);	-- 'Brasão'
REPLACE INTO `item_violetbox` VALUES (2,1013,14);	-- 'Casco Arco-Íris'
REPLACE INTO `item_violetbox` VALUES (2,1014,14);	-- 'Mandíbula de Formiga'
REPLACE INTO `item_violetbox` VALUES (2,1015,14);	-- 'Língua'
REPLACE INTO `item_violetbox` VALUES (2,1016,14);	-- 'Cauda de Rato'
REPLACE INTO `item_violetbox` VALUES (2,1017,14);	-- 'Bigodes de Toupeira'
REPLACE INTO `item_violetbox` VALUES (2,1018,14);	-- 'Garras de Toupeira'
REPLACE INTO `item_violetbox` VALUES (2,1019,14);	-- 'Tronco'
REPLACE INTO `item_violetbox` VALUES (2,1020,14);	-- 'Cabelos Morenos'
REPLACE INTO `item_violetbox` VALUES (2,1021,14);	-- 'Chifre de Dokebi'
REPLACE INTO `item_violetbox` VALUES (2,1022,14);	-- 'Nove-Caudas'
REPLACE INTO `item_violetbox` VALUES (2,1023,14);	-- 'Cauda de Peixe'
REPLACE INTO `item_violetbox` VALUES (2,1024,14);	-- 'Tinta de Polvo'
REPLACE INTO `item_violetbox` VALUES (2,1025,14);	-- 'Teia de Aranha'
REPLACE INTO `item_violetbox` VALUES (2,1026,14);	-- 'Avelã'
REPLACE INTO `item_violetbox` VALUES (2,1027,14);	-- 'Espinho de Porco-Espinho'
REPLACE INTO `item_violetbox` VALUES (2,1028,14);	-- 'Crina'
REPLACE INTO `item_violetbox` VALUES (2,1029,14);	-- 'Pele de Tigre'
REPLACE INTO `item_violetbox` VALUES (2,1030,14);	-- 'Pata de Tigre'
REPLACE INTO `item_violetbox` VALUES (2,1031,14);	-- 'Foice de Louva-a-Deus'
REPLACE INTO `item_violetbox` VALUES (2,1032,14);	-- 'Flor de Planta Carnívora'
REPLACE INTO `item_violetbox` VALUES (2,1033,14);	-- 'Raiz de Planta Carnívora'
REPLACE INTO `item_violetbox` VALUES (2,1034,14);	-- 'Cabelo Azul'
REPLACE INTO `item_violetbox` VALUES (2,1035,14);	-- 'Canino de Dragão'
REPLACE INTO `item_violetbox` VALUES (2,1036,14);	-- 'Escama de Dragão'
REPLACE INTO `item_violetbox` VALUES (2,1037,14);	-- 'Cauda de Dragão'
REPLACE INTO `item_violetbox` VALUES (2,1038,14);	-- 'Pequeno Chifre Maligno'
REPLACE INTO `item_violetbox` VALUES (2,1039,14);	-- 'Pequena Asa Maligna'
REPLACE INTO `item_violetbox` VALUES (2,1040,14);	-- 'Bigode de Anão Ancião'
REPLACE INTO `item_violetbox` VALUES (2,1041,14);	-- 'Lampião'
REPLACE INTO `item_violetbox` VALUES (2,1042,14);	-- 'Pata de Inseto'
REPLACE INTO `item_violetbox` VALUES (2,1043,14);	-- 'Garra de Orc'
REPLACE INTO `item_violetbox` VALUES (2,1044,14);	-- 'Presa de Zenorc'
REPLACE INTO `item_violetbox` VALUES (2,1045,14);	-- 'Máscara Ritualística'
REPLACE INTO `item_violetbox` VALUES (2,1046,14);	-- 'Garra de Escorpião'
REPLACE INTO `item_violetbox` VALUES (2,1047,14);	-- 'Cabeça de Medusa'
REPLACE INTO `item_violetbox` VALUES (2,1048,14);	-- 'Cabelo Horrendo'
REPLACE INTO `item_violetbox` VALUES (2,1049,14);	-- 'Saia Virginal'
REPLACE INTO `item_violetbox` VALUES (2,1050,14);	-- 'Tendões'
REPLACE INTO `item_violetbox` VALUES (2,1051,14);	-- 'Neurônio'
REPLACE INTO `item_violetbox` VALUES (2,1052,14);	-- 'Célula Única'
REPLACE INTO `item_violetbox` VALUES (2,1053,14);	-- 'Dente Fossilizado'
REPLACE INTO `item_violetbox` VALUES (2,1054,14);	-- 'Lábios Fossilizados'
REPLACE INTO `item_violetbox` VALUES (2,1055,14);	-- 'Pele de Minhoca'
REPLACE INTO `item_violetbox` VALUES (2,1056,14);	-- 'Torrão de Areia'
REPLACE INTO `item_violetbox` VALUES (2,1057,14);	-- 'Pó de Traça'
REPLACE INTO `item_violetbox` VALUES (2,1058,14);	-- 'Asas de Traça'
REPLACE INTO `item_violetbox` VALUES (2,1059,14);	-- 'Tecido'
REPLACE INTO `item_violetbox` VALUES (2,1060,14);	-- 'Cabelos Dourados'
REPLACE INTO `item_violetbox` VALUES (2,1061,14);	-- 'Areia Estelar de Bruxa'
REPLACE INTO `item_violetbox` VALUES (2,1062,14);	-- 'Zé-Lanterna'
REPLACE INTO `item_violetbox` VALUES (2,1063,14);	-- 'Presa'
REPLACE INTO `item_violetbox` VALUES (2,1064,14);	-- 'Rédeas'
REPLACE INTO `item_violetbox` VALUES (2,1065,14);	-- 'Armadilha'
REPLACE INTO `item_violetbox` VALUES (2,1066,14);	-- 'Tronco de Alta Qualidade'
REPLACE INTO `item_violetbox` VALUES (2,1067,14);	-- 'Tronco Sólido'
REPLACE INTO `item_violetbox` VALUES (2,1068,14);	-- 'Tronco Estéril'
REPLACE INTO `item_violetbox` VALUES (2,1088,14);	-- 'Solução de Morroc'
REPLACE INTO `item_violetbox` VALUES (2,1089,14);	-- 'Solução de Payon'
REPLACE INTO `item_violetbox` VALUES (2,1092,14);	-- 'Tubo de Ensaio'
REPLACE INTO `item_violetbox` VALUES (2,1093,14);	-- 'Garrafa de Poção'
REPLACE INTO `item_violetbox` VALUES (2,1094,14);	-- 'Trança Curta'
REPLACE INTO `item_violetbox` VALUES (2,1095,14);	-- 'Ponteiro'
REPLACE INTO `item_violetbox` VALUES (2,1096,14);	-- 'Casca Arredondada'
REPLACE INTO `item_violetbox` VALUES (2,1097,14);	-- 'Página Deteriorada'
REPLACE INTO `item_violetbox` VALUES (2,1098,14);	-- 'Algemas'
REPLACE INTO `item_violetbox` VALUES (2,1099,14);	-- 'Uniforme Velho de Presidiário'
REPLACE INTO `item_violetbox` VALUES (2,1102,7);	-- 'Espada'
REPLACE INTO `item_violetbox` VALUES (2,1105,7);	-- 'Alfanje'
REPLACE INTO `item_violetbox` VALUES (2,1108,7);	-- 'Lâmina'
REPLACE INTO `item_violetbox` VALUES (2,1111,7);	-- 'Florete'
REPLACE INTO `item_violetbox` VALUES (2,1114,7);	-- 'Cimitarra'
REPLACE INTO `item_violetbox` VALUES (2,1117,7);	-- 'Kataná'
REPLACE INTO `item_violetbox` VALUES (2,1120,7);	-- 'Tsurugi'
REPLACE INTO `item_violetbox` VALUES (2,1124,7);	-- 'Espada Orc'
REPLACE INTO `item_violetbox` VALUES (2,1125,7);	-- 'Sabre de Impacto'
REPLACE INTO `item_violetbox` VALUES (2,1127,7);	-- 'Sabre'
REPLACE INTO `item_violetbox` VALUES (2,1128,7);	-- 'Haedonggum'
REPLACE INTO `item_violetbox` VALUES (2,1129,7);	-- 'Flamberge'
REPLACE INTO `item_violetbox` VALUES (2,1152,7);	-- 'Espada Matadora'
REPLACE INTO `item_violetbox` VALUES (2,1155,7);	-- 'Espada Bastarda'
REPLACE INTO `item_violetbox` VALUES (2,1158,7);	-- 'Espada de Duas Mãos'
REPLACE INTO `item_violetbox` VALUES (2,1162,7);	-- 'Espada Larga'
REPLACE INTO `item_violetbox` VALUES (2,1163,7);	-- 'Claymore'
REPLACE INTO `item_violetbox` VALUES (2,1202,7);	-- 'Faca'
REPLACE INTO `item_violetbox` VALUES (2,1205,7);	-- 'Punhal'
REPLACE INTO `item_violetbox` VALUES (2,1208,7);	-- 'Main Gauche'
REPLACE INTO `item_violetbox` VALUES (2,1211,7);	-- 'Punhal'
REPLACE INTO `item_violetbox` VALUES (2,1214,7);	-- 'Adaga'
REPLACE INTO `item_violetbox` VALUES (2,1217,7);	-- 'Stiletto'
REPLACE INTO `item_violetbox` VALUES (2,1220,7);	-- 'Gladius'
REPLACE INTO `item_violetbox` VALUES (2,1226,7);	-- 'Damascus'
REPLACE INTO `item_violetbox` VALUES (2,1243,7);	-- 'Adaga do Aprendiz'
REPLACE INTO `item_violetbox` VALUES (2,1251,7);	-- 'Jur'
REPLACE INTO `item_violetbox` VALUES (2,1253,7);	-- 'Katar'
REPLACE INTO `item_violetbox` VALUES (2,1255,7);	-- 'Jamadhar'
REPLACE INTO `item_violetbox` VALUES (2,1256,7);	-- 'Katar Gélida'
REPLACE INTO `item_violetbox` VALUES (2,1257,7);	-- 'Katar da Espinheira Empoeirada'
REPLACE INTO `item_violetbox` VALUES (2,1258,7);	-- 'Katar da Chama Impetuosa'
REPLACE INTO `item_violetbox` VALUES (2,1259,7);	-- 'Katar do Vento Perfurante'
REPLACE INTO `item_violetbox` VALUES (2,1302,7);	-- 'Machado'
REPLACE INTO `item_violetbox` VALUES (2,1304,7);	-- 'Machado dos Orcs'
REPLACE INTO `item_violetbox` VALUES (2,1352,7);	-- 'Machado de Batalha'
REPLACE INTO `item_violetbox` VALUES (2,1355,7);	-- 'Marreta'
REPLACE INTO `item_violetbox` VALUES (2,1358,7);	-- 'Demolidor'
REPLACE INTO `item_violetbox` VALUES (2,1361,7);	-- 'Machado de Duas Mãos'
REPLACE INTO `item_violetbox` VALUES (2,1402,7);	-- 'Azagaia'
REPLACE INTO `item_violetbox` VALUES (2,1405,7);	-- 'Ranseur'
REPLACE INTO `item_violetbox` VALUES (2,1408,7);	-- 'Pique'
REPLACE INTO `item_violetbox` VALUES (2,1411,7);	-- 'Lança'
REPLACE INTO `item_violetbox` VALUES (2,1452,7);	-- 'Guisarme'
REPLACE INTO `item_violetbox` VALUES (2,1455,7);	-- 'Glaive'
REPLACE INTO `item_violetbox` VALUES (2,1458,7);	-- 'Guerrilheira'
REPLACE INTO `item_violetbox` VALUES (2,1461,7);	-- 'Tridente'
REPLACE INTO `item_violetbox` VALUES (2,1464,7);	-- 'Alabarda'
REPLACE INTO `item_violetbox` VALUES (2,1472,7);	-- 'Cajado Cabalístico'
REPLACE INTO `item_violetbox` VALUES (2,1502,7);	-- 'Clava'
REPLACE INTO `item_violetbox` VALUES (2,1505,7);	-- 'Maça'
REPLACE INTO `item_violetbox` VALUES (2,1508,7);	-- 'Esmagador'
REPLACE INTO `item_violetbox` VALUES (2,1511,7);	-- 'Mangual'
REPLACE INTO `item_violetbox` VALUES (2,1514,7);	-- 'Maça de Guerra'
REPLACE INTO `item_violetbox` VALUES (2,1517,7);	-- 'Maça Espada'
REPLACE INTO `item_violetbox` VALUES (2,1520,7);	-- 'Mangual Pesado'
REPLACE INTO `item_violetbox` VALUES (2,1522,7);	-- 'Atordoador'
REPLACE INTO `item_violetbox` VALUES (2,1550,7);	-- 'Livro'
REPLACE INTO `item_violetbox` VALUES (2,1551,7);	-- 'Bíblia'
REPLACE INTO `item_violetbox` VALUES (2,1552,7);	-- 'Tábula'
REPLACE INTO `item_violetbox` VALUES (2,1553,7);	-- 'Livro das Ondas'
REPLACE INTO `item_violetbox` VALUES (2,1554,7);	-- 'Livro da Mãe Terra'
REPLACE INTO `item_violetbox` VALUES (2,1555,7);	-- 'Livro do Sol Ardente'
REPLACE INTO `item_violetbox` VALUES (2,1556,7);	-- 'Livro do Golpe de Vento'
REPLACE INTO `item_violetbox` VALUES (2,1558,7);	-- 'Diário de Menina'
REPLACE INTO `item_violetbox` VALUES (2,1602,7);	-- 'Bastão'
REPLACE INTO `item_violetbox` VALUES (2,1605,7);	-- 'Vareta'
REPLACE INTO `item_violetbox` VALUES (2,1608,7);	-- 'Cajado'
REPLACE INTO `item_violetbox` VALUES (2,1611,7);	-- 'Cetro'
REPLACE INTO `item_violetbox` VALUES (2,1613,7);	-- 'Cajado do Poder'
REPLACE INTO `item_violetbox` VALUES (2,1614,7);	-- 'Bastão Xamista'
REPLACE INTO `item_violetbox` VALUES (2,1615,7);	-- 'Bastão Arcano'
REPLACE INTO `item_violetbox` VALUES (2,1702,7);	-- 'Arco'
REPLACE INTO `item_violetbox` VALUES (2,1705,7);	-- 'Arco Composto'
REPLACE INTO `item_violetbox` VALUES (2,1708,7);	-- 'Arco Grande'
REPLACE INTO `item_violetbox` VALUES (2,1711,7);	-- 'Besta'
REPLACE INTO `item_violetbox` VALUES (2,1715,7);	-- 'Arbaleste'
REPLACE INTO `item_violetbox` VALUES (2,1716,7);	-- 'Gakkung'
REPLACE INTO `item_violetbox` VALUES (2,1718,7);	-- 'Arco de Caça'
REPLACE INTO `item_violetbox` VALUES (2,1750,14);	-- 'Flecha'
REPLACE INTO `item_violetbox` VALUES (2,1751,14);	-- 'Flecha de Prata'
REPLACE INTO `item_violetbox` VALUES (2,1752,14);	-- 'Flecha de Fogo'
REPLACE INTO `item_violetbox` VALUES (2,1753,14);	-- 'Flecha de Aço'
REPLACE INTO `item_violetbox` VALUES (2,1754,14);	-- 'Flecha de Cristal'
REPLACE INTO `item_violetbox` VALUES (2,1755,14);	-- 'Flecha de Vento'
REPLACE INTO `item_violetbox` VALUES (2,1756,14);	-- 'Flecha de Pedra'
REPLACE INTO `item_violetbox` VALUES (2,1757,14);	-- 'Flecha Incorpórea'
REPLACE INTO `item_violetbox` VALUES (2,1758,14);	-- 'Flecha Atordoante'
REPLACE INTO `item_violetbox` VALUES (2,1759,14);	-- 'Flecha Congelante'
REPLACE INTO `item_violetbox` VALUES (2,1760,14);	-- 'Flecha Luminosa'
REPLACE INTO `item_violetbox` VALUES (2,1761,14);	-- 'Flecha Amaldiçoada'
REPLACE INTO `item_violetbox` VALUES (2,1762,14);	-- 'Flecha Enferrujada'
REPLACE INTO `item_violetbox` VALUES (2,1763,14);	-- 'Flecha Envenenada'
REPLACE INTO `item_violetbox` VALUES (2,1764,14);	-- 'Flecha Afiada'
REPLACE INTO `item_violetbox` VALUES (2,1765,14);	-- 'Flecha de Oridecon'
REPLACE INTO `item_violetbox` VALUES (2,1767,14);	-- 'Flecha Sombria'
REPLACE INTO `item_violetbox` VALUES (2,1768,14);	-- 'Flecha Sonífera'
REPLACE INTO `item_violetbox` VALUES (2,1769,14);	-- 'Flecha Emudecedora'
REPLACE INTO `item_violetbox` VALUES (2,1770,14);	-- 'Flecha de Ferro'
REPLACE INTO `item_violetbox` VALUES (2,1802,7);	-- 'Waghnak'
REPLACE INTO `item_violetbox` VALUES (2,1804,7);	-- 'Soqueira'
REPLACE INTO `item_violetbox` VALUES (2,1806,7);	-- 'Soco Inglês'
REPLACE INTO `item_violetbox` VALUES (2,1808,7);	-- 'Punho'
REPLACE INTO `item_violetbox` VALUES (2,1810,7);	-- 'Garra'
REPLACE INTO `item_violetbox` VALUES (2,1812,7);	-- 'Dedos Afiados'
REPLACE INTO `item_violetbox` VALUES (2,1902,7);	-- 'Violino'
REPLACE INTO `item_violetbox` VALUES (2,1904,7);	-- 'Bandolin'
REPLACE INTO `item_violetbox` VALUES (2,1906,7);	-- 'Alaúde'
REPLACE INTO `item_violetbox` VALUES (2,1908,7);	-- 'Violão'
REPLACE INTO `item_violetbox` VALUES (2,1910,7);	-- 'Harpa'
REPLACE INTO `item_violetbox` VALUES (2,1912,7);	-- 'Gumoongoh'
REPLACE INTO `item_violetbox` VALUES (2,1951,7);	-- 'Cordel'
REPLACE INTO `item_violetbox` VALUES (2,1953,7);	-- 'Cordame'
REPLACE INTO `item_violetbox` VALUES (2,1955,7);	-- 'Açoite'
REPLACE INTO `item_violetbox` VALUES (2,1957,7);	-- 'Azorrague'
REPLACE INTO `item_violetbox` VALUES (2,1959,7);	-- 'Chibata'
REPLACE INTO `item_violetbox` VALUES (2,1961,7);	-- 'Chicote'
REPLACE INTO `item_violetbox` VALUES (2,2102,7);	-- 'Vembrassa'
REPLACE INTO `item_violetbox` VALUES (2,2104,7);	-- 'Broquel'
REPLACE INTO `item_violetbox` VALUES (2,2106,7);	-- 'Escudo'
REPLACE INTO `item_violetbox` VALUES (2,2108,7);	-- 'Escudo Espelhado'
REPLACE INTO `item_violetbox` VALUES (2,2109,7);	-- 'Grimório'
REPLACE INTO `item_violetbox` VALUES (2,2112,7);	-- 'Vembrassa do Aprendiz'
REPLACE INTO `item_violetbox` VALUES (2,2201,7);	-- 'Óculos Escuros'
REPLACE INTO `item_violetbox` VALUES (2,2203,7);	-- 'Óculos'
REPLACE INTO `item_violetbox` VALUES (2,2205,7);	-- 'Óculos de Mergulho'
REPLACE INTO `item_violetbox` VALUES (2,2206,7);	-- 'Véu de Noiva'
REPLACE INTO `item_violetbox` VALUES (2,2207,7);	-- 'Florzinha'
REPLACE INTO `item_violetbox` VALUES (2,2208,7);	-- 'Laço'
REPLACE INTO `item_violetbox` VALUES (2,2209,7);	-- 'Laço'
REPLACE INTO `item_violetbox` VALUES (2,2210,7);	-- 'Faixa de Cabelo'
REPLACE INTO `item_violetbox` VALUES (2,2211,7);	-- 'Bandana'
REPLACE INTO `item_violetbox` VALUES (2,2212,7);	-- 'Tapa-Olho'
REPLACE INTO `item_violetbox` VALUES (2,2213,7);	-- 'Orelha de Gato'
REPLACE INTO `item_violetbox` VALUES (2,2214,7);	-- 'Orelha de Coelho'
REPLACE INTO `item_violetbox` VALUES (2,2215,7);	-- 'Chapéu Florido'
REPLACE INTO `item_violetbox` VALUES (2,2216,7);	-- 'Solidéu'
REPLACE INTO `item_violetbox` VALUES (2,2217,7);	-- 'Solidéu'
REPLACE INTO `item_violetbox` VALUES (2,2218,7);	-- 'Máscara Cirúrgica'
REPLACE INTO `item_violetbox` VALUES (2,2220,7);	-- 'Chapéu'
REPLACE INTO `item_violetbox` VALUES (2,2221,7);	-- 'Chapéu'
REPLACE INTO `item_violetbox` VALUES (2,2222,7);	-- 'Turbante'
REPLACE INTO `item_violetbox` VALUES (2,2223,7);	-- 'Turbante'
REPLACE INTO `item_violetbox` VALUES (2,2224,7);	-- 'Óculos de Proteção'
REPLACE INTO `item_violetbox` VALUES (2,2225,7);	-- 'Óculos de Proteção'
REPLACE INTO `item_violetbox` VALUES (2,2226,7);	-- 'Barrete'
REPLACE INTO `item_violetbox` VALUES (2,2227,7);	-- 'Barrete'
REPLACE INTO `item_violetbox` VALUES (2,2228,7);	-- 'Elmo'
REPLACE INTO `item_violetbox` VALUES (2,2229,7);	-- 'Elmo'
REPLACE INTO `item_violetbox` VALUES (2,2230,7);	-- 'Capacete de Schallern'
REPLACE INTO `item_violetbox` VALUES (2,2231,7);	-- 'Capacete de Schallern'
REPLACE INTO `item_violetbox` VALUES (2,2232,7);	-- 'Tiara'
REPLACE INTO `item_violetbox` VALUES (2,2233,7);	-- 'Tiara'
REPLACE INTO `item_violetbox` VALUES (2,2234,1);	-- 'Diadema'
REPLACE INTO `item_violetbox` VALUES (2,2235,1);	-- 'Coroa'
REPLACE INTO `item_violetbox` VALUES (2,2236,7);	-- 'Gorro de Natal'
REPLACE INTO `item_violetbox` VALUES (2,2239,7);	-- 'Monóculo'
REPLACE INTO `item_violetbox` VALUES (2,2241,7);	-- 'Bigode Grisalho'
REPLACE INTO `item_violetbox` VALUES (2,2242,7);	-- 'Óculos Ultra-Violeta'
REPLACE INTO `item_violetbox` VALUES (2,2243,7);	-- 'Quatro-Olhos'
REPLACE INTO `item_violetbox` VALUES (2,2244,7);	-- 'Laço Grande'
REPLACE INTO `item_violetbox` VALUES (2,2245,7);	-- 'Chapéu Charmoso'
REPLACE INTO `item_violetbox` VALUES (2,2246,7);	-- 'Peça Dourada'
REPLACE INTO `item_violetbox` VALUES (2,2247,7);	-- 'Chapéu Romântico'
REPLACE INTO `item_violetbox` VALUES (2,2248,7);	-- 'Chapéu do Velho Oeste'
REPLACE INTO `item_violetbox` VALUES (2,2249,1);	-- 'Coroa Menor'
REPLACE INTO `item_violetbox` VALUES (2,2250,7);	-- 'Laço Meigo'
REPLACE INTO `item_violetbox` VALUES (2,2251,7);	-- 'Chapéu de Monge'
REPLACE INTO `item_violetbox` VALUES (2,2252,7);	-- 'Chapéu de Bathory'
REPLACE INTO `item_violetbox` VALUES (2,2253,7);	-- 'Girassol'
REPLACE INTO `item_violetbox` VALUES (2,2254,1);	-- 'Asas de Anjo'
REPLACE INTO `item_violetbox` VALUES (2,2255,1);	-- 'Asas de Demônio'
REPLACE INTO `item_violetbox` VALUES (2,2256,1);	-- 'Chifres Majestosos'
REPLACE INTO `item_violetbox` VALUES (2,2257,7);	-- 'Chifre de Unicórnio'
REPLACE INTO `item_violetbox` VALUES (2,2258,1);	-- 'Chifres Pontudos'
REPLACE INTO `item_violetbox` VALUES (2,2259,7);	-- 'Hélices'
REPLACE INTO `item_violetbox` VALUES (2,2260,7);	-- 'Pince-Nez'
REPLACE INTO `item_violetbox` VALUES (2,2261,7);	-- 'Capacete de Soldado'
REPLACE INTO `item_violetbox` VALUES (2,2262,7);	-- 'Nariz de Palhaço'
REPLACE INTO `item_violetbox` VALUES (2,2263,7);	-- 'Máscara de Bandido'
REPLACE INTO `item_violetbox` VALUES (2,2265,7);	-- 'Máscara x'
REPLACE INTO `item_violetbox` VALUES (2,2266,7);	-- 'Bevor'
REPLACE INTO `item_violetbox` VALUES (2,2267,7);	-- 'Cigarro'
REPLACE INTO `item_violetbox` VALUES (2,2268,7);	-- 'Cachimbo'
REPLACE INTO `item_violetbox` VALUES (2,2269,7);	-- 'Flor Romântica'
REPLACE INTO `item_violetbox` VALUES (2,2270,7);	-- 'Folha Romântica'
REPLACE INTO `item_violetbox` VALUES (2,2271,7);	-- 'Óculos Charmoso'
REPLACE INTO `item_violetbox` VALUES (2,2274,1);	-- 'Faixa de Fantasma'
REPLACE INTO `item_violetbox` VALUES (2,2275,7);	-- 'Faixa Marrom'
REPLACE INTO `item_violetbox` VALUES (2,2276,7);	-- 'Óculos de Gatinho'
REPLACE INTO `item_violetbox` VALUES (2,2277,7);	-- 'Chapéu de Enfermeira'
REPLACE INTO `item_violetbox` VALUES (2,2278,7);	-- 'Máscara Feliz'
REPLACE INTO `item_violetbox` VALUES (2,2279,7);	-- 'Pavio'
REPLACE INTO `item_violetbox` VALUES (2,2282,7);	-- 'Auréola'
REPLACE INTO `item_violetbox` VALUES (2,2285,7);	-- 'Maçã de Guilherme Tell'
REPLACE INTO `item_violetbox` VALUES (2,2286,1);	-- 'Orelhas de Elfo'
REPLACE INTO `item_violetbox` VALUES (2,2287,7);	-- 'Bandana Pirata'
REPLACE INTO `item_violetbox` VALUES (2,2288,7);	-- 'Máscara Assustadora'
REPLACE INTO `item_violetbox` VALUES (2,2289,7);	-- 'Chapéu Fedorento'
REPLACE INTO `item_violetbox` VALUES (2,2290,7);	-- 'Chapéu Funebre'
REPLACE INTO `item_violetbox` VALUES (2,2291,7);	-- 'Disfarce'
REPLACE INTO `item_violetbox` VALUES (2,2294,7);	-- 'Presilha de Estrela'
REPLACE INTO `item_violetbox` VALUES (2,2295,7);	-- 'Venda'
REPLACE INTO `item_violetbox` VALUES (2,2297,7);	-- 'Máscara de Goblin'
REPLACE INTO `item_violetbox` VALUES (2,2298,7);	-- 'Antenas Verdes'
REPLACE INTO `item_violetbox` VALUES (2,2299,7);	-- 'Capacete de Orc'
REPLACE INTO `item_violetbox` VALUES (2,2302,7);	-- 'Camisa de Algodão'
REPLACE INTO `item_violetbox` VALUES (2,2304,7);	-- 'Gibão'
REPLACE INTO `item_violetbox` VALUES (2,2306,7);	-- 'Túnica'
REPLACE INTO `item_violetbox` VALUES (2,2308,7);	-- 'Capote'
REPLACE INTO `item_violetbox` VALUES (2,2310,7);	-- 'Casaco'
REPLACE INTO `item_violetbox` VALUES (2,2311,7);	-- 'Casaco de Pele'
REPLACE INTO `item_violetbox` VALUES (2,2313,7);	-- 'Armadura Acolchoada'
REPLACE INTO `item_violetbox` VALUES (2,2315,7);	-- 'Cota de Malha'
REPLACE INTO `item_violetbox` VALUES (2,2317,7);	-- 'Armadura Metálica'
REPLACE INTO `item_violetbox` VALUES (2,2318,7);	-- 'Vestimental Nobre'
REPLACE INTO `item_violetbox` VALUES (2,2320,7);	-- 'Paletó'
REPLACE INTO `item_violetbox` VALUES (2,2322,7);	-- 'Manto de Seda'
REPLACE INTO `item_violetbox` VALUES (2,2324,7);	-- 'Escapulário'
REPLACE INTO `item_violetbox` VALUES (2,2326,7);	-- 'Manto Sagrado'
REPLACE INTO `item_violetbox` VALUES (2,2327,1);	-- 'Batina'
REPLACE INTO `item_violetbox` VALUES (2,2329,7);	-- 'Armadura de Madeira'
REPLACE INTO `item_violetbox` VALUES (2,2331,7);	-- 'Malha'
REPLACE INTO `item_violetbox` VALUES (2,2333,7);	-- 'Manto Prateado'
REPLACE INTO `item_violetbox` VALUES (2,2334,1);	-- 'Vestimenta Arcana'
REPLACE INTO `item_violetbox` VALUES (2,2336,7);	-- 'Traje de Gatuno'
REPLACE INTO `item_violetbox` VALUES (2,2337,7);	-- 'Indumentária Ninja'
REPLACE INTO `item_violetbox` VALUES (2,2338,7);	-- 'Vestido de Casamento'
REPLACE INTO `item_violetbox` VALUES (2,2339,7);	-- 'Roupa de Baixo'
REPLACE INTO `item_violetbox` VALUES (2,2340,7);	-- 'Armadura de Aprendiz'
REPLACE INTO `item_violetbox` VALUES (2,2352,7);	-- 'Traje do Aprendiz'
REPLACE INTO `item_violetbox` VALUES (2,2402,7);	-- 'Sandálias'
REPLACE INTO `item_violetbox` VALUES (2,2404,7);	-- 'Sapatos'
REPLACE INTO `item_violetbox` VALUES (2,2406,7);	-- 'Botas'
REPLACE INTO `item_violetbox` VALUES (2,2407,7);	-- 'Sapatilha de Cristal'
REPLACE INTO `item_violetbox` VALUES (2,2408,7);	-- 'Grilhões'
REPLACE INTO `item_violetbox` VALUES (2,2409,7);	-- 'Salto Alto'
REPLACE INTO `item_violetbox` VALUES (2,2411,7);	-- 'Grevas'
REPLACE INTO `item_violetbox` VALUES (2,2414,7);	-- 'Sandálias do Aprendiz'
REPLACE INTO `item_violetbox` VALUES (2,2502,7);	-- 'Capuz'
REPLACE INTO `item_violetbox` VALUES (2,2504,7);	-- 'Sobrepeliz'
REPLACE INTO `item_violetbox` VALUES (2,2506,7);	-- 'Manteau'
REPLACE INTO `item_violetbox` VALUES (2,2507,7);	-- 'Capa do Marquês'
REPLACE INTO `item_violetbox` VALUES (2,2508,7);	-- 'Capa Velha'
REPLACE INTO `item_violetbox` VALUES (2,2510,7);	-- 'Capuz do Aprendiz'
REPLACE INTO `item_violetbox` VALUES (2,2601,7);	-- 'Anel'
REPLACE INTO `item_violetbox` VALUES (2,2602,7);	-- 'Brinco'
REPLACE INTO `item_violetbox` VALUES (2,2603,7);	-- 'Colar'
REPLACE INTO `item_violetbox` VALUES (2,2604,7);	-- 'Luvas'
REPLACE INTO `item_violetbox` VALUES (2,2605,7);	-- 'Broche'
REPLACE INTO `item_violetbox` VALUES (2,2607,7);	-- 'Presilha'
REPLACE INTO `item_violetbox` VALUES (2,2608,7);	-- 'Rosário'
REPLACE INTO `item_violetbox` VALUES (2,2609,7);	-- 'Anel de Caveira'
REPLACE INTO `item_violetbox` VALUES (2,2610,7);	-- 'Anel de Ouro'
REPLACE INTO `item_violetbox` VALUES (2,2611,7);	-- 'Anel de Prata'
REPLACE INTO `item_violetbox` VALUES (2,2612,7);	-- 'Anel de Flor'
REPLACE INTO `item_violetbox` VALUES (2,2613,7);	-- 'Anel de Diamante'
REPLACE INTO `item_violetbox` VALUES (2,2614,1);	-- 'Olho de Dullahan'
REPLACE INTO `item_violetbox` VALUES (2,2615,1);	-- 'Anel de Defesa'
REPLACE INTO `item_violetbox` VALUES (2,2616,1);	-- 'Anel Certeiro'
REPLACE INTO `item_violetbox` VALUES (2,2617,7);	-- 'Luva Sacra'
REPLACE INTO `item_violetbox` VALUES (2,2618,7);	-- 'Coleira de Matyr'
REPLACE INTO `item_violetbox` VALUES (2,2621,1);	-- 'Anel'
REPLACE INTO `item_violetbox` VALUES (2,2622,1);	-- 'Brinco'
REPLACE INTO `item_violetbox` VALUES (2,2623,1);	-- 'Colar'
REPLACE INTO `item_violetbox` VALUES (2,2624,1);	-- 'Luva'
REPLACE INTO `item_violetbox` VALUES (2,2625,1);	-- 'Broche'
REPLACE INTO `item_violetbox` VALUES (2,2626,1);	-- 'Rosário'
REPLACE INTO `item_violetbox` VALUES (2,2627,7);	-- 'Cinto'
REPLACE INTO `item_violetbox` VALUES (2,2628,7);	-- 'Bracelete de Aprendiz'
REPLACE INTO `item_violetbox` VALUES (2,5002,1);	-- 'Coroa Adornada'
REPLACE INTO `item_violetbox` VALUES (2,5003,7);	-- 'Chapéu de Bufão'
REPLACE INTO `item_violetbox` VALUES (2,5005,7);	-- 'Máscara de Gás'
REPLACE INTO `item_violetbox` VALUES (2,5006,7);	-- 'Óculos de Machão'
REPLACE INTO `item_violetbox` VALUES (2,5007,1);	-- 'Coroa do Líder'
REPLACE INTO `item_violetbox` VALUES (2,5008,7);	-- 'Grinalda'
REPLACE INTO `item_violetbox` VALUES (2,5009,7);	-- 'Capacete de Segurança'
REPLACE INTO `item_violetbox` VALUES (2,5010,7);	-- 'Penacho'
REPLACE INTO `item_violetbox` VALUES (2,5011,7);	-- 'Antena'
REPLACE INTO `item_violetbox` VALUES (2,5014,7);	-- 'Barbatanas'
REPLACE INTO `item_violetbox` VALUES (2,5015,7);	-- 'Casca de Ovo'
REPLACE INTO `item_violetbox` VALUES (2,5017,1);	-- 'Elmo de Osso'
REPLACE INTO `item_violetbox` VALUES (2,5019,1);	-- 'Chapéu de Corsário'
REPLACE INTO `item_violetbox` VALUES (2,5030,7);	-- 'Chapéu de Panda'
REPLACE INTO `item_violetbox` VALUES (2,5035,7);	-- 'Chapéu de Poring'
REPLACE INTO `item_violetbox` VALUES (2,5037,7);	-- 'Casca de Maçã'
REPLACE INTO `item_violetbox` VALUES (2,5053,1);	-- 'Coroa de Faraó'
REPLACE INTO `item_violetbox` VALUES (2,5055,7);	-- 'Chapéu de Ovo do Aprendiz'
REPLACE INTO `item_violetbox` VALUES (2,5066,1);	-- 'Chifre de Succubus'
REPLACE INTO `item_violetbox` VALUES (2,5072,1);	-- 'Chifre de Incubus'
REPLACE INTO `item_violetbox` VALUES (2,5085,1);	-- 'Lacinhos'
REPLACE INTO `item_violetbox` VALUES (2,5088,7);	-- 'Máscara Surpresa'
REPLACE INTO `item_violetbox` VALUES (2,5089,7);	-- 'Máscara Aflita'
REPLACE INTO `item_violetbox` VALUES (2,5090,7);	-- 'Máscara de Líder Goblin'
REPLACE INTO `item_violetbox` VALUES (2,5096,1);	-- 'Máscara do Sicário'
REPLACE INTO `item_violetbox` VALUES (2,7001,14);	-- 'Pó de Bolor'
REPLACE INTO `item_violetbox` VALUES (2,7002,14);	-- 'Dente de Ogro'
REPLACE INTO `item_violetbox` VALUES (2,7003,14);	-- 'Pele de Anolian'
REPLACE INTO `item_violetbox` VALUES (2,7004,14);	-- 'Monte de Lama'
REPLACE INTO `item_violetbox` VALUES (2,7005,14);	-- 'Crânio'
REPLACE INTO `item_violetbox` VALUES (2,7006,14);	-- 'Asa de Morcego Vermelho'
REPLACE INTO `item_violetbox` VALUES (2,7007,14);	-- 'Garra de Rato'
REPLACE INTO `item_violetbox` VALUES (2,7008,14);	-- 'Chifre Firme'
REPLACE INTO `item_violetbox` VALUES (2,7009,14);	-- 'Casca Brilhante'
REPLACE INTO `item_violetbox` VALUES (2,7010,14);	-- 'Cauda de Escorpião de Aço'
REPLACE INTO `item_violetbox` VALUES (2,7011,14);	-- 'Garra de Macaco'
REPLACE INTO `item_violetbox` VALUES (2,7012,14);	-- 'Pedaço de Escama Dura'
REPLACE INTO `item_violetbox` VALUES (2,7013,14);	-- 'Coral'
REPLACE INTO `item_violetbox` VALUES (2,7014,14);	-- 'Retrato Velho'
REPLACE INTO `item_violetbox` VALUES (2,7015,14);	-- 'Marca-Página'
REPLACE INTO `item_violetbox` VALUES (2,7016,14);	-- 'Colher Entortada'
REPLACE INTO `item_violetbox` VALUES (2,7026,14);	-- 'Chave para a Torre do Relógio'
REPLACE INTO `item_violetbox` VALUES (2,7027,14);	-- 'Chave para o Subterrâneo'
REPLACE INTO `item_violetbox` VALUES (2,7030,14);	-- 'Garra de Lobo do Deserto'
REPLACE INTO `item_violetbox` VALUES (2,7031,14);	-- 'Frigideira Velha'
REPLACE INTO `item_violetbox` VALUES (2,7032,14);	-- 'Pedaço de Casca de Ovo'
REPLACE INTO `item_violetbox` VALUES (2,7033,14);	-- 'Esporo Venenoso'
REPLACE INTO `item_violetbox` VALUES (2,7034,14);	-- 'Meia Furada'
REPLACE INTO `item_violetbox` VALUES (2,7035,14);	-- 'Palito de Fósforo'
REPLACE INTO `item_violetbox` VALUES (2,7036,14);	-- 'Presa de Hati'
REPLACE INTO `item_violetbox` VALUES (2,7038,14);	-- 'Novelo'
REPLACE INTO `item_violetbox` VALUES (2,7041,14);	-- 'Torrão de Areia Fina'
REPLACE INTO `item_violetbox` VALUES (2,7047,14);	-- 'Avental de Alice'
REPLACE INTO `item_violetbox` VALUES (2,7048,14);	-- 'Garra de Grifo'
REPLACE INTO `item_violetbox` VALUES (2,7049,14);	-- 'Pedra'
REPLACE INTO `item_violetbox` VALUES (2,7053,14);	-- 'Cyfar'
REPLACE INTO `item_violetbox` VALUES (2,7054,14);	-- 'Brigan'
REPLACE INTO `item_violetbox` VALUES (2,7059,14);	-- 'Vale-Armazém'
REPLACE INTO `item_violetbox` VALUES (2,7060,14);	-- 'Vale-Teletransporte'
REPLACE INTO `item_violetbox` VALUES (2,7061,14);	-- 'Vale-Carrinho'
REPLACE INTO `item_violetbox` VALUES (2,7063,14);	-- 'Pena Macia'
REPLACE INTO `item_violetbox` VALUES (2,7064,14);	-- 'Asas de Libélula'
REPLACE INTO `item_violetbox` VALUES (2,7065,14);	-- 'Pele de Lontra'
REPLACE INTO `item_violetbox` VALUES (2,7066,14);	-- 'Cubo de Gelo'
REPLACE INTO `item_violetbox` VALUES (2,7067,14);	-- 'Pedaço de Pedra'
REPLACE INTO `item_violetbox` VALUES (2,7068,14);	-- 'Madeira Queimada'
REPLACE INTO `item_violetbox` VALUES (2,7069,14);	-- 'Armadura Destruída'
REPLACE INTO `item_violetbox` VALUES (2,7070,14);	-- 'Casca Quebrada'
REPLACE INTO `item_violetbox` VALUES (2,7071,14);	-- 'Farrapos'
REPLACE INTO `item_violetbox` VALUES (2,7072,14);	-- 'Shuriken Gasto'
REPLACE INTO `item_violetbox` VALUES (2,7093,14);	-- 'Engrenagem'
REPLACE INTO `item_violetbox` VALUES (2,7094,14);	-- 'Fragmento Misterioso'
REPLACE INTO `item_violetbox` VALUES (2,7095,14);	-- 'Pedaço de Metal'
REPLACE INTO `item_violetbox` VALUES (2,7096,14);	-- 'Pedra Pome'
REPLACE INTO `item_violetbox` VALUES (2,7097,14);	-- 'Coração Incandescente'
REPLACE INTO `item_violetbox` VALUES (2,7098,14);	-- 'Lenha em Brasa'
REPLACE INTO `item_violetbox` VALUES (2,7099,14);	-- 'Pergaminho Antigo'
REPLACE INTO `item_violetbox` VALUES (2,7100,14);	-- 'Folha Afiada'
REPLACE INTO `item_violetbox` VALUES (2,7101,14);	-- 'Pena de Grand Peco'
REPLACE INTO `item_violetbox` VALUES (2,7106,14);	-- 'Chifre de Bode'
REPLACE INTO `item_violetbox` VALUES (2,7107,14);	-- 'Pele de Bode'
REPLACE INTO `item_violetbox` VALUES (2,7108,14);	-- 'Pedaço de Escudo Colossal'
REPLACE INTO `item_violetbox` VALUES (2,7109,14);	-- 'Lâmina de Lança Colossal'
REPLACE INTO `item_violetbox` VALUES (2,7110,14);	-- 'Espada Chanfrada'
REPLACE INTO `item_violetbox` VALUES (2,7111,14);	-- 'Pedaço de Papel'
REPLACE INTO `item_violetbox` VALUES (2,7112,14);	-- 'Lâmina de Papel'
REPLACE INTO `item_violetbox` VALUES (2,7113,14);	-- 'Cetro do Faraó'
REPLACE INTO `item_violetbox` VALUES (2,7114,14);	-- 'Máscara do Faraó'
REPLACE INTO `item_violetbox` VALUES (2,7115,14);	-- 'Pena de Harpia'
REPLACE INTO `item_violetbox` VALUES (2,7116,14);	-- 'Garra de Harpia'
REPLACE INTO `item_violetbox` VALUES (2,7117,14);	-- 'Velho Grimório'
REPLACE INTO `item_violetbox` VALUES (2,7118,14);	-- 'Pergaminho Gasto'
REPLACE INTO `item_violetbox` VALUES (2,7119,14);	-- 'Bactérias'
REPLACE INTO `item_violetbox` VALUES (2,7120,14);	-- 'Ferradura em Chamas'
REPLACE INTO `item_violetbox` VALUES (2,7121,14);	-- 'Pote de Mel'
REPLACE INTO `item_violetbox` VALUES (2,7122,14);	-- 'Pelugem Incandescente'
REPLACE INTO `item_violetbox` VALUES (2,7123,14);	-- 'Pele de Dragão'
REPLACE INTO `item_violetbox` VALUES (2,7124,14);	-- 'Areia Molhada'
REPLACE INTO `item_violetbox` VALUES (2,7125,14);	-- 'Pinças de Escorpião'
REPLACE INTO `item_violetbox` VALUES (2,7126,14);	-- 'Jellopy Tamanho Família'
REPLACE INTO `item_violetbox` VALUES (2,7134,14);	-- 'Vasilha de Mistura'
REPLACE INTO `item_violetbox` VALUES (2,7135,14);	-- 'Frasco de Fogo Grego'
REPLACE INTO `item_violetbox` VALUES (2,7136,14);	-- 'Frasco de Ácido'
REPLACE INTO `item_violetbox` VALUES (2,7137,14);	-- 'Frasco de Planta Carnívora'
REPLACE INTO `item_violetbox` VALUES (2,7138,14);	-- 'Frasco de Esfera Marinha'
REPLACE INTO `item_violetbox` VALUES (2,7139,14);	-- 'Frasco de Revestimento'
REPLACE INTO `item_violetbox` VALUES (2,7149,14);	-- 'Prato Amarelado'
REPLACE INTO `item_violetbox` VALUES (2,7150,14);	-- 'Pedaço de Bambu'
REPLACE INTO `item_violetbox` VALUES (2,7151,14);	-- 'Papel Amarelado'
REPLACE INTO `item_violetbox` VALUES (2,7152,14);	-- 'Cabelos Perfumados'
REPLACE INTO `item_violetbox` VALUES (2,7153,14);	-- 'Velho Obi'
REPLACE INTO `item_violetbox` VALUES (2,7154,14);	-- 'Poeira Venenosa'
REPLACE INTO `item_violetbox` VALUES (2,7155,14);	-- 'Pele de Sapo'
REPLACE INTO `item_violetbox` VALUES (2,7156,14);	-- 'Shuriken Despedaçado'
REPLACE INTO `item_violetbox` VALUES (2,7157,14);	-- 'Máscara Ninja'
REPLACE INTO `item_violetbox` VALUES (2,7158,14);	-- 'Jarro de Saquê'
REPLACE INTO `item_violetbox` VALUES (2,7159,14);	-- 'Nariz de Tengu'
REPLACE INTO `item_violetbox` VALUES (2,7161,14);	-- 'Pele Negra de Urso'
REPLACE INTO `item_violetbox` VALUES (2,7162,14);	-- 'Jarro de Nuvem'
REPLACE INTO `item_violetbox` VALUES (2,7163,14);	-- 'Antenas Afiadas'
REPLACE INTO `item_violetbox` VALUES (2,7164,14);	-- 'Pêssego Petrificado'
REPLACE INTO `item_violetbox` VALUES (2,7165,14);	-- 'Manto Cerimonial Celestial'
REPLACE INTO `item_violetbox` VALUES (2,7166,14);	-- 'Seda Macia'
REPLACE INTO `item_violetbox` VALUES (2,7167,14);	-- 'Misterioso Metal em Pano'
REPLACE INTO `item_violetbox` VALUES (2,7168,14);	-- 'Grandes Asas de Borboleta'
REPLACE INTO `item_violetbox` VALUES (2,7169,14);	-- 'Ba Gua'
REPLACE INTO `item_violetbox` VALUES (2,7170,14);	-- 'Smoking'
REPLACE INTO `item_violetbox` VALUES (2,7171,14);	-- 'Pele de Leopardo'
REPLACE INTO `item_violetbox` VALUES (2,7172,14);	-- 'Garras de Leopardo'
REPLACE INTO `item_violetbox` VALUES (2,7174,14);	-- 'Laço para presente'
REPLACE INTO `item_violetbox` VALUES (2,7175,14);	-- 'Papel de presente'
REPLACE INTO `item_violetbox` VALUES (2,7182,14);	-- 'Cacau'
REPLACE INTO `item_violetbox` VALUES (2,7186,14);	-- 'Cipó'
REPLACE INTO `item_violetbox` VALUES (2,7187,14);	-- 'Máscara do Festival'
REPLACE INTO `item_violetbox` VALUES (2,7188,14);	-- 'Raiz Marrom'
REPLACE INTO `item_violetbox` VALUES (2,7189,14);	-- 'Coração de Madeira'
REPLACE INTO `item_violetbox` VALUES (2,7190,14);	-- 'Casco de Inseto'
REPLACE INTO `item_violetbox` VALUES (2,7191,14);	-- 'Lanterna'
REPLACE INTO `item_violetbox` VALUES (2,7192,14);	-- 'Catavento'
REPLACE INTO `item_violetbox` VALUES (2,7193,14);	-- 'Semente'
REPLACE INTO `item_violetbox` VALUES (2,7194,14);	-- 'Grama'
REPLACE INTO `item_violetbox` VALUES (2,7195,14);	-- 'Estilingue'
REPLACE INTO `item_violetbox` VALUES (2,7196,14);	-- 'Ombreira'
REPLACE INTO `item_violetbox` VALUES (2,7197,14);	-- 'Palha'
REPLACE INTO `item_violetbox` VALUES (2,7198,14);	-- 'Folha Gigante'
REPLACE INTO `item_violetbox` VALUES (2,7200,14);	-- 'Elástico'
REPLACE INTO `item_violetbox` VALUES (2,7201,14);	-- 'Tora'
REPLACE INTO `item_violetbox` VALUES (2,7202,14);	-- 'Pata de Besouro'
REPLACE INTO `item_violetbox` VALUES (2,7203,14);	-- 'Galho Resistente'
REPLACE INTO `item_violetbox` VALUES (2,7205,14);	-- 'Retalho Negro'
REPLACE INTO `item_violetbox` VALUES (2,7206,14);	-- 'Boneco de Gato Preto'
REPLACE INTO `item_violetbox` VALUES (2,7207,14);	-- 'Manteau Velho'
REPLACE INTO `item_violetbox` VALUES (2,7208,14);	-- 'Faca Enferrujada'
REPLACE INTO `item_violetbox` VALUES (2,7209,14);	-- 'Elmo de Dullahan'
REPLACE INTO `item_violetbox` VALUES (2,7210,14);	-- 'Armadura de Dullahan'
REPLACE INTO `item_violetbox` VALUES (2,7211,14);	-- 'Lasca de Pedra'
REPLACE INTO `item_violetbox` VALUES (2,7212,14);	-- 'Boneca Enforcada'
REPLACE INTO `item_violetbox` VALUES (2,7213,14);	-- 'Almofada de Alfinetes'
REPLACE INTO `item_violetbox` VALUES (2,7214,14);	-- 'Gaiola de Morcegos'
REPLACE INTO `item_violetbox` VALUES (2,7215,14);	-- 'Espeto Quebrado'
REPLACE INTO `item_violetbox` VALUES (2,7216,14);	-- 'Cachecol Vermelho'
REPLACE INTO `item_violetbox` VALUES (2,7217,14);	-- 'Carretel'
REPLACE INTO `item_violetbox` VALUES (2,7218,14);	-- 'Corda Decomposta'
REPLACE INTO `item_violetbox` VALUES (2,7219,14);	-- 'Meia Listrada'
REPLACE INTO `item_violetbox` VALUES (2,7220,14);	-- 'Ectoplasma'
REPLACE INTO `item_violetbox` VALUES (2,7221,14);	-- 'Corrente'
REPLACE INTO `item_violetbox` VALUES (2,7222,14);	-- 'Coluna de Madeira'
REPLACE INTO `item_violetbox` VALUES (2,7223,14);	-- 'Auto Retrato'
REPLACE INTO `item_violetbox` VALUES (2,7225,14);	-- 'Lanterna de Abóbora'
REPLACE INTO `item_violetbox` VALUES (2,7262,14);	-- 'Leque Fantasma'
REPLACE INTO `item_violetbox` VALUES (2,7263,14);	-- 'Olho de Gato'
REPLACE INTO `item_violetbox` VALUES (2,7264,14);	-- 'Areia Seca'
REPLACE INTO `item_violetbox` VALUES (2,7265,14);	-- 'Chifre de Dragão'
REPLACE INTO `item_violetbox` VALUES (2,7266,14);	-- 'Dentadura da Máscara do Dragão'
REPLACE INTO `item_violetbox` VALUES (2,7267,14);	-- 'Tanga de Tigre'
REPLACE INTO `item_violetbox` VALUES (2,7268,14);	-- 'Pequena Boneca Fantasma'
REPLACE INTO `item_violetbox` VALUES (2,7269,14);	-- 'Babador'
REPLACE INTO `item_violetbox` VALUES (2,7270,14);	-- 'Mamadeira'
REPLACE INTO `item_violetbox` VALUES (2,10001,7);	-- 'Elmo de Crânio'
REPLACE INTO `item_violetbox` VALUES (2,10002,7);	-- 'Máscara de Oxigênio para Bichinhos'
REPLACE INTO `item_violetbox` VALUES (2,10003,7);	-- 'Capacete Espacial'
REPLACE INTO `item_violetbox` VALUES (2,10004,7);	-- 'Chupeta'
REPLACE INTO `item_violetbox` VALUES (2,10005,7);	-- 'Peruca'
REPLACE INTO `item_violetbox` VALUES (2,10006,7);	-- 'Ornamento da Rainha'
REPLACE INTO `item_violetbox` VALUES (2,10007,7);	-- 'Laço de Seda'
REPLACE INTO `item_violetbox` VALUES (2,10008,7);	-- 'Pavana'
REPLACE INTO `item_violetbox` VALUES (2,10009,7);	-- 'Flor Selvagem'
REPLACE INTO `item_violetbox` VALUES (2,10010,7);	-- 'Panela Velha'
REPLACE INTO `item_violetbox` VALUES (2,10011,7);	-- 'Ornato Estelar'
REPLACE INTO `item_violetbox` VALUES (2,10012,7);	-- 'Casca de Ovo Minúscula'
REPLACE INTO `item_violetbox` VALUES (2,10013,7);	-- 'Mochila'
REPLACE INTO `item_violetbox` VALUES (2,10014,7);	-- 'Óculos de Rocker'
REPLACE INTO `item_violetbox` VALUES (2,10015,7);	-- 'Laço Verde'
REPLACE INTO `item_violetbox` VALUES (2,10016,7);	-- 'Sino de Ouro'
REPLACE INTO `item_violetbox` VALUES (2,10017,7);	-- 'Saia Havaiana'
REPLACE INTO `item_violetbox` VALUES (2,10018,7);	-- 'Coroa de Macaco'
REPLACE INTO `item_violetbox` VALUES (2,10019,7);	-- 'Pano Vermelho'
REPLACE INTO `item_violetbox` VALUES (2,10020,7);	-- 'Espada chinesa'
REPLACE INTO `item_violetbox` VALUES (2,7751,17);	-- 'Velha Vestimenta Branca'
REPLACE INTO `item_violetbox` VALUES (2,7752,16);	-- 'Crânio Atordoante'
REPLACE INTO `item_violetbox` VALUES (2,7753,17);	-- 'Utensílio Rural Quebrado'
REPLACE INTO `item_violetbox` VALUES (2,1264,1);	-- 'Jur Especial'
REPLACE INTO `item_violetbox` VALUES (2,1269,1);	-- 'Escama Invertida'
REPLACE INTO `item_violetbox` VALUES (2,1271,1);	-- 'Lágrimas Sangrentas'
REPLACE INTO `item_violetbox` VALUES (2,1370,1);	-- 'Machado do Apocalipse'
REPLACE INTO `item_violetbox` VALUES (2,1376,1);	-- 'Desolador'
REPLACE INTO `item_violetbox` VALUES (2,1377,1);	-- 'Fúria do Furacão'
REPLACE INTO `item_violetbox` VALUES (2,1478,1);	-- 'Ahlspiess'
REPLACE INTO `item_violetbox` VALUES (2,13304,1);	-- 'Huuma da Calmaria'
REPLACE INTO `item_violetbox` VALUES (2,1730,1);	-- 'Arco Incendiário'
REPLACE INTO `item_violetbox` VALUES (2,1731,1);	-- 'Arco Glacial'
REPLACE INTO `item_violetbox` VALUES (2,1732,1);	-- 'Arco da Terra'
REPLACE INTO `item_violetbox` VALUES (2,1733,1);	-- 'Arco do Vendaval'
REPLACE INTO `item_violetbox` VALUES (2,1818,1);	-- 'Punho de Magma'
REPLACE INTO `item_violetbox` VALUES (2,1819,1);	-- 'Punho Gélido'
REPLACE INTO `item_violetbox` VALUES (2,1820,1);	-- 'Punho Voltaico'
REPLACE INTO `item_violetbox` VALUES (2,1821,1);	-- 'Punho Sísmico'
REPLACE INTO `item_violetbox` VALUES (2,1822,1);	-- 'Luva de Combo'
REPLACE INTO `item_violetbox` VALUES (2,1919,1);	-- 'Contra-Baixo'
REPLACE INTO `item_violetbox` VALUES (2,1972,1);	-- 'Enguia Elétrica'
REPLACE INTO `item_violetbox` VALUES (2,1973,1);	-- 'Botas da Bruxa do Mar'
REPLACE INTO `item_violetbox` VALUES (2,1974,1);	-- 'Chicote de Cenoura'
REPLACE INTO `item_violetbox` VALUES (2,13200,1);	-- 'Projétil'
REPLACE INTO `item_violetbox` VALUES (2,13201,1);	-- 'Projétil de Prata'
REPLACE INTO `item_violetbox` VALUES (2,13202,1);	-- 'Projétil Sanguinário'
REPLACE INTO `item_violetbox` VALUES (2,13203,1);	-- 'Esfera de Chamas'
REPLACE INTO `item_violetbox` VALUES (2,13204,1);	-- 'Esfera de Relâmpagos'
REPLACE INTO `item_violetbox` VALUES (2,13205,1);	-- 'Esfera Venenosa'
REPLACE INTO `item_violetbox` VALUES (2,13206,1);	-- 'Esfera Cegante'
REPLACE INTO `item_violetbox` VALUES (2,13207,1);	-- 'Esfera Congelante'
REPLACE INTO `item_violetbox` VALUES (2,13167,1);	-- 'Leão-de-Chácara'
REPLACE INTO `item_violetbox` VALUES (2,13168,1);	-- 'Trovoada'
REPLACE INTO `item_violetbox` VALUES (2,13163,1);	-- 'Rifle de Alcance'
REPLACE INTO `item_violetbox` VALUES (2,13170,2);	-- 'Espingarda Calibre 12'
REPLACE INTO `item_violetbox` VALUES (2,13164,1);	-- 'Rifle de Alcance