--
-- Estrutura para a tabela `item_buyingstore`
--  

CREATE TABLE IF NOT EXISTS `item_buyingstore` (
  `ItemID` mediumint(3) unsigned NOT NULL default '0',
   PRIMARY KEY (`ItemID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*
 Janela de Compras.
 Descrição: Responsável pelos itens usáveis com a janela de compras.
 Cabeçalho: REPLACE INTO `item_buyingstore` VALUES ('ID do Item');
*/

REPLACE INTO `item_buyingstore` VALUES (714);  -- 'Emperium'
REPLACE INTO `item_buyingstore` VALUES (6381);  -- 'Field_Shovel'
REPLACE INTO `item_buyingstore` VALUES (6382);  -- 'Urn'
REPLACE INTO `item_buyingstore` VALUES (6393);  -- 'Round_Feather'
REPLACE INTO `item_buyingstore` VALUES (6394);  -- 'Golden_Feather'
REPLACE INTO `item_buyingstore` VALUES (6395);  -- 'Angel_Magic_Power'
REPLACE INTO `item_buyingstore` VALUES (7347);  -- 'Lab_Staff_Record'
REPLACE INTO `item_buyingstore` VALUES (7760);  -- 'Yaga_Magic_Book'
REPLACE INTO `item_buyingstore` VALUES (7762);  -- 'Yaga_Pestle'
REPLACE INTO `item_buyingstore` VALUES (7824);  -- 'Spirit_Liquor'
REPLACE INTO `item_buyingstore` VALUES (11519);  -- 'Beef_Toast'
REPLACE INTO `item_buyingstore` VALUES (11520);  -- 'Mora_Mandarin'
REPLACE INTO `item_buyingstore` VALUES (11521);  -- 'Pingui_Berry_Juice'
REPLACE INTO `item_buyingstore` VALUES (11522);  -- 'Red_Raffle_Sap'
REPLACE INTO `item_buyingstore` VALUES (11523);  -- 'Yellow_Raffle_Sap'
REPLACE INTO `item_buyingstore` VALUES (11524);  -- 'White_Raffle_Sap'
REPLACE INTO `item_buyingstore` VALUES (11525);  -- 'Mora_Hip_Tea'
REPLACE INTO `item_buyingstore` VALUES (11526);  -- 'Rafflecino'
REPLACE INTO `item_buyingstore` VALUES (12329);  -- 'Recall_MaleGm'
REPLACE INTO `item_buyingstore` VALUES (12330);  -- 'Recall_FemaleGm'
REPLACE INTO `item_buyingstore` VALUES (12342);  -- 'ManukNULLs_Opportunity'
REPLACE INTO `item_buyingstore` VALUES (12343);  -- 'ManukNULLs_Courage'
REPLACE INTO `item_buyingstore` VALUES (12344);  -- 'PinguiculaNULLs_fruit_Jam'
REPLACE INTO `item_buyingstore` VALUES (12345);  -- 'LuciolaNULLs_Honey_Jam'
REPLACE INTO `item_buyingstore` VALUES (12348);  -- 'ManukNULLs_Faith'
REPLACE INTO `item_buyingstore` VALUES (12349);  -- 'CornusNULL_Tears'
REPLACE INTO `item_buyingstore` VALUES (12350);  -- 'Angeling_Potion'
REPLACE INTO `item_buyingstore` VALUES (12351);  -- 'Shout_Megaphone'
REPLACE INTO `item_buyingstore` VALUES (12354);  -- 'Buche_De_Noel'
REPLACE INTO `item_buyingstore` VALUES (12355);  -- 'Xmas_Gift'
REPLACE INTO `item_buyingstore` VALUES (12356);  -- 'Louise_Costume_Box'
REPLACE INTO `item_buyingstore` VALUES (12418);  -- 'Full_Swingk'
REPLACE INTO `item_buyingstore` VALUES (12419);  -- 'Mana_Plus'
REPLACE INTO `item_buyingstore` VALUES (12422);  -- 'HP_Increase_Potions'
REPLACE INTO `item_buyingstore` VALUES (12423);  -- 'HP_Increase_Potionm'
REPLACE INTO `item_buyingstore` VALUES (12424);  -- 'HP_Increase_Potionl'
REPLACE INTO `item_buyingstore` VALUES (12425);  -- 'SP_Increase_Potions'
REPLACE INTO `item_buyingstore` VALUES (12426);  -- 'SP_Increase_Potionm'
REPLACE INTO `item_buyingstore` VALUES (12427);  -- 'SP_Increase_Potionl'
REPLACE INTO `item_buyingstore` VALUES (12428);  -- 'Enrich_White_Potionz'
REPLACE INTO `item_buyingstore` VALUES (12429);  -- 'Savage_BBq'
REPLACE INTO `item_buyingstore` VALUES (12430);  -- 'Wug_Blood_Cocktail'
REPLACE INTO `item_buyingstore` VALUES (12431);  -- 'Minor_Brisket'
REPLACE INTO `item_buyingstore` VALUES (12432);  -- 'Siroma_Icetea'
REPLACE INTO `item_buyingstore` VALUES (12433);  -- 'Drocera_Herb_Stew'
REPLACE INTO `item_buyingstore` VALUES (12434);  -- 'Petti_Tail_Noodle'
REPLACE INTO `item_buyingstore` VALUES (12436);  -- 'Vitata500'
REPLACE INTO `item_buyingstore` VALUES (12437);  -- 'Enrich_Celermine_Juice'
REPLACE INTO `item_buyingstore` VALUES (12475);  -- 'Cure_Free'
REPLACE INTO `item_buyingstore` VALUES (12536);  -- 'NY_Rice_Cake_Soup'
REPLACE INTO `item_buyingstore` VALUES (12539);  -- 'Splendid_Box'
REPLACE INTO `item_buyingstore` VALUES (12561);  -- 'Mysterious_Seed'
REPLACE INTO `item_buyingstore` VALUES (12574);  -- 'Mora_Berry'
REPLACE INTO `item_buyingstore` VALUES (12575);  -- 'Arrow_Of_Elf_Cntr'
REPLACE INTO `item_buyingstore` VALUES (12576);  -- 'Hunting_Arrow_Cntr'
REPLACE INTO `item_buyingstore` VALUES (601);  -- 'Asa de Mosca'
REPLACE INTO `item_buyingstore` VALUES (602);  -- 'Asa de Borboleta'
REPLACE INTO `item_buyingstore` VALUES (603);  -- 'Velha Caixa Azul'
REPLACE INTO `item_buyingstore` VALUES (604);  -- 'Galho Seco'
REPLACE INTO `item_buyingstore` VALUES (605);  -- 'Analgésico'
REPLACE INTO `item_buyingstore` VALUES (606);  -- 'Aloe Vera'
REPLACE INTO `item_buyingstore` VALUES (607);  -- 'Fruto de Yggdrasil'
REPLACE INTO `item_buyingstore` VALUES (608);  -- 'Semente de Yggdrasil'
REPLACE INTO `item_buyingstore` VALUES (609);  -- 'Amuleto'
REPLACE INTO `item_buyingstore` VALUES (610);  -- 'Folha de Yggdrasil'
REPLACE INTO `item_buyingstore` VALUES (611);  -- 'Lupa'
REPLACE INTO `item_buyingstore` VALUES (612);  -- 'Mini-Fornalha'
REPLACE INTO `item_buyingstore` VALUES (613);  -- 'Martelo de Ferro'
REPLACE INTO `item_buyingstore` VALUES (614);  -- 'Martelo de Ouro'
REPLACE INTO `item_buyingstore` VALUES (615);  -- 'Martelo de Oridecon'
REPLACE INTO `item_buyingstore` VALUES (616);  -- 'Velho Álbum de Cartas'
REPLACE INTO `item_buyingstore` VALUES (617);  -- 'Velha Caixa Roxa'
REPLACE INTO `item_buyingstore` VALUES (618);  -- 'Pergaminho Desgastado'
REPLACE INTO `item_buyingstore` VALUES (619);  -- 'Maçã Verde'
REPLACE INTO `item_buyingstore` VALUES (620);  -- 'Suco de Laranja'
REPLACE INTO `item_buyingstore` VALUES (621);  -- 'Erva Amarga'
REPLACE INTO `item_buyingstore` VALUES (622);  -- 'Cenoura Arco-Íris'
REPLACE INTO `item_buyingstore` VALUES (623);  -- 'Minhoca Boa-Pinta'
REPLACE INTO `item_buyingstore` VALUES (624);  -- 'Peixe Podre'
REPLACE INTO `item_buyingstore` VALUES (625);  -- 'Ferro Enferrujado'
REPLACE INTO `item_buyingstore` VALUES (626);  -- 'Suco de Monstro'
REPLACE INTO `item_buyingstore` VALUES (627);  -- 'Leite Doce'
REPLACE INTO `item_buyingstore` VALUES (628);  -- 'Osso Seco'
REPLACE INTO `item_buyingstore` VALUES (629);  -- 'Flor Cantante'
REPLACE INTO `item_buyingstore` VALUES (630);  -- 'Musgo Encharcado'
REPLACE INTO `item_buyingstore` VALUES (631);  -- 'Erva Letal'
REPLACE INTO `item_buyingstore` VALUES (632);  -- 'Minhoca Gorducha'
REPLACE INTO `item_buyingstore` VALUES (633);  -- 'Batata Assada'
REPLACE INTO `item_buyingstore` VALUES (634);  -- 'Banana Tropical'
REPLACE INTO `item_buyingstore` VALUES (635);  -- 'Horror da Tribo'
REPLACE INTO `item_buyingstore` VALUES (636);  -- 'Sem Destinatário'
REPLACE INTO `item_buyingstore` VALUES (637);  -- 'Vassoura Velha'
REPLACE INTO `item_buyingstore` VALUES (638);  -- 'Faca de Prata da Castidade'
REPLACE INTO `item_buyingstore` VALUES (639);  -- 'Bracelete da Obediência'
REPLACE INTO `item_buyingstore` VALUES (640);  -- 'Pedra Brilhante'
REPLACE INTO `item_buyingstore` VALUES (641);  -- 'Contratos das Sombras'
REPLACE INTO `item_buyingstore` VALUES (642);  -- 'Livro do Diabo'
REPLACE INTO `item_buyingstore` VALUES (643);  -- 'Incubadora'
REPLACE INTO `item_buyingstore` VALUES (644);  -- 'Caixa de Presente'
REPLACE INTO `item_buyingstore` VALUES (645);  -- 'Poção da Concentração'
REPLACE INTO `item_buyingstore` VALUES (656);  -- 'Poção do Despertar'
REPLACE INTO `item_buyingstore` VALUES (657);  -- 'Poção da Fúria Selvagem'
REPLACE INTO `item_buyingstore` VALUES (658);  -- 'União da Tribo'
REPLACE INTO `item_buyingstore` VALUES (659);  -- 'Coração Apaixonado'
REPLACE INTO `item_buyingstore` VALUES (660);  -- 'Vela do Marquês de Sade'
REPLACE INTO `item_buyingstore` VALUES (661);  -- 'Avental Elegante'
REPLACE INTO `item_buyingstore` VALUES (662);  -- 'Emblema Oficial'
REPLACE INTO `item_buyingstore` VALUES (663);  -- 'Ovos de Chocolate Branco'
REPLACE INTO `item_buyingstore` VALUES (664);  -- 'Caixa de Presente 1'
REPLACE INTO `item_buyingstore` VALUES (665);  -- 'Caixa de Presente 2'
REPLACE INTO `item_buyingstore` VALUES (666);  -- 'Caixa de Presente 3'
REPLACE INTO `item_buyingstore` VALUES (667);  -- 'Caixa de Presente 4'
REPLACE INTO `item_buyingstore` VALUES (668);  -- 'Envelope Vermelho'
REPLACE INTO `item_buyingstore` VALUES (669);  -- 'Sopa de Arroz'
REPLACE INTO `item_buyingstore` VALUES (678);  -- 'Garrafa de Veneno'
REPLACE INTO `item_buyingstore` VALUES (679);  -- 'Pílula Dourada'
REPLACE INTO `item_buyingstore` VALUES (681);  -- 'Álbum de Fotos de Casamento'
REPLACE INTO `item_buyingstore` VALUES (682);  -- 'Bebida de Realgar'
REPLACE INTO `item_buyingstore` VALUES (683);  -- 'Erva de Exorcismo'
REPLACE INTO `item_buyingstore` VALUES (684);  -- 'Jaca'
REPLACE INTO `item_buyingstore` VALUES (686);  -- 'Coluna de Pedra Nível 3'
REPLACE INTO `item_buyingstore` VALUES (687);  -- 'Coluna de Pedra Nível 5'
REPLACE INTO `item_buyingstore` VALUES (688);  -- 'Lanças de Gelo Nível 3'
REPLACE INTO `item_buyingstore` VALUES (689);  -- 'Lanças de Gelo Nível 5'
REPLACE INTO `item_buyingstore` VALUES (690);  -- 'Lanças de Fogo Nível 3'
REPLACE INTO `item_buyingstore` VALUES (691);  -- 'Lanças de Fogo Nível 5'
REPLACE INTO `item_buyingstore` VALUES (692);  -- 'Relâmpago Nível 3'
REPLACE INTO `item_buyingstore` VALUES (693);  -- 'Relâmpago Nível 5'
REPLACE INTO `item_buyingstore` VALUES (694);  -- 'Espíritos Anciões Nível 3'
REPLACE INTO `item_buyingstore` VALUES (695);  -- 'Espíritos Anciões Nível 5'
REPLACE INTO `item_buyingstore` VALUES (696);  -- 'Bolas de Fogo Nível 1'
REPLACE INTO `item_buyingstore` VALUES (697);  -- 'Bolas de Fogo Nível 5'
REPLACE INTO `item_buyingstore` VALUES (698);  -- 'Barreira de Fogo Nível 1'
REPLACE INTO `item_buyingstore` VALUES (699);  -- 'Barreira de Fogo Nível 5'
REPLACE INTO `item_buyingstore` VALUES (700);  -- 'Rajada Congelante Nível 1'
REPLACE INTO `item_buyingstore` VALUES (12000);  -- 'Rajada Congelante Nível 5'
REPLACE INTO `item_buyingstore` VALUES (12001);  -- 'Cura Nível 3'
REPLACE INTO `item_buyingstore` VALUES (12002);  -- 'Cura Nível 5'
REPLACE INTO `item_buyingstore` VALUES (12003);  -- 'Teleporte Nível 1'
REPLACE INTO `item_buyingstore` VALUES (12004);  -- 'Aljave'
REPLACE INTO `item_buyingstore` VALUES (12005);  -- 'Aljave de Flechas de Ferro'
REPLACE INTO `item_buyingstore` VALUES (12006);  -- 'Aljave de Flechas de Aço'
REPLACE INTO `item_buyingstore` VALUES (12007);  -- 'Aljave de Flechas de Oridecon'
REPLACE INTO `item_buyingstore` VALUES (12008);  -- 'Aljave de Flechas de Fogo'
REPLACE INTO `item_buyingstore` VALUES (12009);  -- 'Aljave de Flechas de Prata'
REPLACE INTO `item_buyingstore` VALUES (12010);  -- 'Aljave de Flechas de Vento'
REPLACE INTO `item_buyingstore` VALUES (12011);  -- 'Aljave de Flechas de Pedra'
REPLACE INTO `item_buyingstore` VALUES (12012);  -- 'Aljave de Flechas de Cristal'
REPLACE INTO `item_buyingstore` VALUES (12013);  -- 'Aljave de Flechas de Sombra'
REPLACE INTO `item_buyingstore` VALUES (12014);  -- 'Aljave de Flechas Imateriais'
REPLACE INTO `item_buyingstore` VALUES (12015);  -- 'Aljave de Flechas Enferrujadas'
REPLACE INTO `item_buyingstore` VALUES (12016);  -- 'Poção do Vento'
REPLACE INTO `item_buyingstore` VALUES (12017);  -- 'Poção da Lentidão'
REPLACE INTO `item_buyingstore` VALUES (12018);  -- 'Fogo de Artifício'
REPLACE INTO `item_buyingstore` VALUES (12020);  -- 'Água Amaldiçoada'
REPLACE INTO `item_buyingstore` VALUES (12027);  -- 'Caixa Risonha'
REPLACE INTO `item_buyingstore` VALUES (12028);  -- 'Caixa do Trovão'
REPLACE INTO `item_buyingstore` VALUES (12029);  -- 'Caixa da Escuridão'
REPLACE INTO `item_buyingstore` VALUES (12030);  -- 'Caixa do Ressentimento'
REPLACE INTO `item_buyingstore` VALUES (12031);  -- 'Caixa da Sonolência'
REPLACE INTO `item_buyingstore` VALUES (12032);  -- 'Caixa da Tempestade'
REPLACE INTO `item_buyingstore` VALUES (12033);  -- 'Caixa da Luz do Sol'
REPLACE INTO `item_buyingstore` VALUES (12034);  -- 'Caixa do Arquejo'
REPLACE INTO `item_buyingstore` VALUES (12040);  -- 'Pedra do Sábio'
REPLACE INTO `item_buyingstore` VALUES (12041);  -- 'Pernas de Gafanhoto Fritas'
REPLACE INTO `item_buyingstore` VALUES (12042);  -- 'Palmípede Temperado'
REPLACE INTO `item_buyingstore` VALUES (12043);  -- 'Bife Bombástico'
REPLACE INTO `item_buyingstore` VALUES (12044);  -- 'Bife Marinado com Ervas'
REPLACE INTO `item_buyingstore` VALUES (12045);  -- 'Panqueca de Lutie'
REPLACE INTO `item_buyingstore` VALUES (12046);  -- 'Chá de Ervas com Uvas'
REPLACE INTO `item_buyingstore` VALUES (12047);  -- 'Chá Vermelho de Outono'
REPLACE INTO `item_buyingstore` VALUES (12048);  -- 'Chá de Ervas e Mel'
REPLACE INTO `item_buyingstore` VALUES (12049);  -- 'Vinho de Frutas de Morroc'
REPLACE INTO `item_buyingstore` VALUES (12050);  -- 'Vinho de Mastela'
REPLACE INTO `item_buyingstore` VALUES (12051);  -- 'Garras de Caranguejo no Vapor'
REPLACE INTO `item_buyingstore` VALUES (12052);  -- 'Frutos do Mar Sortidos'
REPLACE INTO `item_buyingstore` VALUES (12053);  -- 'Sopa de Ostra'
REPLACE INTO `item_buyingstore` VALUES (12054);  -- 'Água-Viva Temperada'
REPLACE INTO `item_buyingstore` VALUES (12055);  -- 'Pão de Carne Picante Frito'
REPLACE INTO `item_buyingstore` VALUES (12056);  -- 'Sopa de Tinta de Lula e Ovos de Sapo'
REPLACE INTO `item_buyingstore` VALUES (12057);  -- 'Macarrão Liso'
REPLACE INTO `item_buyingstore` VALUES (12058);  -- 'Queijo Gratinado com Tentáculos'
REPLACE INTO `item_buyingstore` VALUES (12059);  -- 'Macarrão Frio de Lutie'
REPLACE INTO `item_buyingstore` VALUES (12060);  -- 'Asa de Morcego com Abóbora no Vapor'
REPLACE INTO `item_buyingstore` VALUES (12061);  -- 'Suco de Uva e Mel'
REPLACE INTO `item_buyingstore` VALUES (12062);  -- 'Bolo-Mousse de Chocolate'
REPLACE INTO `item_buyingstore` VALUES (12063);  -- 'Salada de Frutas'
REPLACE INTO `item_buyingstore` VALUES (12064);  -- 'Sanduíche Cremoso'
REPLACE INTO `item_buyingstore` VALUES (12065);  -- 'Salada Verde'
REPLACE INTO `item_buyingstore` VALUES (12066);  -- 'Caudas de Macaco Fritas'
REPLACE INTO `item_buyingstore` VALUES (12067);  -- 'Suco Misto'
REPLACE INTO `item_buyingstore` VALUES (12068);  -- 'Batata-Doce Frita'
REPLACE INTO `item_buyingstore` VALUES (12069);  -- 'Lábios Fossilizados no Vapor'
REPLACE INTO `item_buyingstore` VALUES (12070);  -- 'Caudas de Escorpião Fritas'
REPLACE INTO `item_buyingstore` VALUES (12071);  -- 'Bife Marinado Brilhante'
REPLACE INTO `item_buyingstore` VALUES (12072);  -- 'Assado Inteiro'
REPLACE INTO `item_buyingstore` VALUES (12073);  -- 'Pé de Urso Especial'
REPLACE INTO `item_buyingstore` VALUES (12074);  -- 'Saté de Tendões'
REPLACE INTO `item_buyingstore` VALUES (12075);  -- 'Língua no Vapor'
REPLACE INTO `item_buyingstore` VALUES (12076);  -- 'Vinho de Cogumelo Vermelho'
REPLACE INTO `item_buyingstore` VALUES (12077);  -- 'Chá de Ervas e Geléia Real Especial'
REPLACE INTO `item_buyingstore` VALUES (12078);  -- 'Chá da Família Real'
REPLACE INTO `item_buyingstore` VALUES (12079);  -- 'Tristam 12 Anos'
REPLACE INTO `item_buyingstore` VALUES (12080);  -- 'Coquetel Sopro do Dragão'
REPLACE INTO `item_buyingstore` VALUES (12081);  -- 'Bebida Amargosa'
REPLACE INTO `item_buyingstore` VALUES (12082);  -- 'Banquete Suntuoso'
REPLACE INTO `item_buyingstore` VALUES (12083);  -- 'Burrito Gigante'
REPLACE INTO `item_buyingstore` VALUES (12084);  -- 'Sopa de Dragão Ascendente'
REPLACE INTO `item_buyingstore` VALUES (12085);  -- 'Cozido Imortal'
REPLACE INTO `item_buyingstore` VALUES (12086);  -- 'Gratinado de Chilli e Camarão'
REPLACE INTO `item_buyingstore` VALUES (12087);  -- 'Crocodilo no Vapor com Vegetais'
REPLACE INTO `item_buyingstore` VALUES (12088);  -- 'Curry Incrivelmente Picante'
REPLACE INTO `item_buyingstore` VALUES (12089);  -- 'Cozido de Carne Especial'
REPLACE INTO `item_buyingstore` VALUES (12090);  -- 'Escorpiões do Deserto no Vapor'
REPLACE INTO `item_buyingstore` VALUES (12091);  -- 'Bolo de Pêssego'
REPLACE INTO `item_buyingstore` VALUES (12092);  -- 'Pão Doce Assombroso'
REPLACE INTO `item_buyingstore` VALUES (12093);  -- 'Torrada Especial'
REPLACE INTO `item_buyingstore` VALUES (12094);  -- 'Suco de Frutas Divino'
REPLACE INTO `item_buyingstore` VALUES (12095);  -- 'Tônico de Hwergelmir'
REPLACE INTO `item_buyingstore` VALUES (12096);  -- 'Sopa da Sorte'
REPLACE INTO `item_buyingstore` VALUES (12097);  -- 'Espetinho Sortido'
REPLACE INTO `item_buyingstore` VALUES (12098);  -- 'Bolinho de Arroz com Morango'
REPLACE INTO `item_buyingstore` VALUES (12099);  -- 'Refrigerante Sangrento'
REPLACE INTO `item_buyingstore` VALUES (12100);  -- 'Nove Caudas Cozidas'
REPLACE INTO `item_buyingstore` VALUES (12101);  -- 'Citron'
REPLACE INTO `item_buyingstore` VALUES (12102);  -- 'Grilled Skewer'
REPLACE INTO `item_buyingstore` VALUES (12103);  -- 'Galho Sangrento'
REPLACE INTO `item_buyingstore` VALUES (12104);  -- 'Aljave Aleatório'
REPLACE INTO `item_buyingstore` VALUES (12105);  -- 'Kit de Domesticação'
REPLACE INTO `item_buyingstore` VALUES (12106);  -- 'Caixa de Jóias'
REPLACE INTO `item_buyingstore` VALUES (12107);  -- 'Máscara Embrulhada'
REPLACE INTO `item_buyingstore` VALUES (12108);  -- 'Pacote de Pergaminho'
REPLACE INTO `item_buyingstore` VALUES (12109);  -- 'Caixa Poring'
REPLACE INTO `item_buyingstore` VALUES (12110);  -- 'Kit de Primeiros Socorros'
REPLACE INTO `item_buyingstore` VALUES (12111);  -- 'Trouxa de Comida'
REPLACE INTO `item_buyingstore` VALUES (12112);  -- 'Sograt Tropical'
REPLACE INTO `item_buyingstore` VALUES (12113);  -- 'Escarlate Praiano'
REPLACE INTO `item_buyingstore` VALUES (12114);  -- 'Conversor Elemental'
REPLACE INTO `item_buyingstore` VALUES (12115);  -- 'Conversor Elemental'
REPLACE INTO `item_buyingstore` VALUES (12116);  -- 'Conversor Elemental'
REPLACE INTO `item_buyingstore` VALUES (12117);  -- 'Conversor Elemental'
REPLACE INTO `item_buyingstore` VALUES (12118);  -- 'Poção Anti-Fogo'
REPLACE INTO `item_buyingstore` VALUES (12119);  -- 'Poção Anti-Água'
REPLACE INTO `item_buyingstore` VALUES (12120);  -- 'Poção Anti-Terra'
REPLACE INTO `item_buyingstore` VALUES (12121);  -- 'Poção Anti-Vento'
REPLACE INTO `item_buyingstore` VALUES (12122);  -- 'Ovinhos Coloridos'
REPLACE INTO `item_buyingstore` VALUES (12123);  -- 'Biscoito de Mel'
REPLACE INTO `item_buyingstore` VALUES (12124);  -- 'Bolo Arco-Íris'
REPLACE INTO `item_buyingstore` VALUES (12125);  -- 'Kit de Culinária Portátil'
REPLACE INTO `item_buyingstore` VALUES (12126);  -- 'Kit de Culinária Caseiro'
REPLACE INTO `item_buyingstore` VALUES (12127);  -- 'Kit de Culinária Profissional'
REPLACE INTO `item_buyingstore` VALUES (12128);  -- 'Kit de Culinária Real'
REPLACE INTO `item_buyingstore` VALUES (12129);  -- 'Kit de Culinária Fantástico'
REPLACE INTO `item_buyingstore` VALUES (12130);  -- 'Sacola de Biscoitos'
REPLACE INTO `item_buyingstore` VALUES (12132);  -- 'Bolsa de Papai Noel'
REPLACE INTO `item_buyingstore` VALUES (12144);  -- 'Pacote de Esferas de Relâmpago'
REPLACE INTO `item_buyingstore` VALUES (12145);  -- 'Pacote de Esferas Cegantes'
REPLACE INTO `item_buyingstore` VALUES (12146);  -- 'Pacote de Esferas Venenosas'
REPLACE INTO `item_buyingstore` VALUES (12147);  -- 'Pacote de Esferas Congelantes'
REPLACE INTO `item_buyingstore` VALUES (12148);  -- 'Pacote de Esferas de Chamas'
REPLACE INTO `item_buyingstore` VALUES (12149);  -- 'Carregador'
REPLACE INTO `item_buyingstore` VALUES (12150);  -- 'Carregador Sanguinário'
REPLACE INTO `item_buyingstore` VALUES (12151);  -- 'Carregador de Prata'
REPLACE INTO `item_buyingstore` VALUES (12183);  -- 'Aljave de Flechas Sagradas'
REPLACE INTO `item_buyingstore` VALUES (12184);  -- 'Poção Vermelha de Ajudante'
REPLACE INTO `item_buyingstore` VALUES (12185);  -- 'Poção Azul de Ajudante'
REPLACE INTO `item_buyingstore` VALUES (12194);  -- 'Hometown Gift'
REPLACE INTO `item_buyingstore` VALUES (12195);  -- 'Plain Rice Cake'
REPLACE INTO `item_buyingstore` VALUES (12196);  -- 'Hearty Rice Cake'
REPLACE INTO `item_buyingstore` VALUES (12197);  -- 'Salty Rice Cake'
REPLACE INTO `item_buyingstore` VALUES (12198);  -- 'Lucky Rice Cake'
REPLACE INTO `item_buyingstore` VALUES (12241);  -- 'Poção da Concentração para Assistentes'
REPLACE INTO `item_buyingstore` VALUES (12242);  -- 'Poção de Despertar para Assistentes'
REPLACE INTO `item_buyingstore` VALUES (12243);  -- 'Poção da Fúria Selvagem para Assistentes'
REPLACE INTO `item_buyingstore` VALUES (12246);  -- 'Álbum Mágico de Cartas'
REPLACE INTO `item_buyingstore` VALUES (12260);  -- 'Roupas de Praia'
REPLACE INTO `item_buyingstore` VALUES (12290);  -- 'Mysterious Can Magic Powder'
REPLACE INTO `item_buyingstore` VALUES (12291);  -- 'Mysterious PET Bottle'
REPLACE INTO `item_buyingstore` VALUES (12292);  -- 'Unripe Fruit'
REPLACE INTO `item_buyingstore` VALUES (12293);  -- 'Dried Yggdrasilberry'
REPLACE INTO `item_buyingstore` VALUES (12341);  -- 'Special Alloy Trap Box'
REPLACE INTO `item_buyingstore` VALUES (12346);  -- 'Avelã Verde'
REPLACE INTO `item_buyingstore` VALUES (12347);  -- 'Geleia de Avelã'
REPLACE INTO `item_buyingstore` VALUES (12353);  -- 'Garrafa Pequena'
REPLACE INTO `item_buyingstore` VALUES (12358);  -- 'Leque dos Ventos'
REPLACE INTO `item_buyingstore` VALUES (12359);  -- 'Folha Macia'
REPLACE INTO `item_buyingstore` VALUES (12360);  -- 'Suco Vermelho-Sangue'
REPLACE INTO `item_buyingstore` VALUES (12362);  -- 'Kuloren'
REPLACE INTO `item_buyingstore` VALUES (12364);  -- 'Cajado do Líder'
REPLACE INTO `item_buyingstore` VALUES (12365);  -- 'Flor de Lótus'
REPLACE INTO `item_buyingstore` VALUES (12366);  -- 'Bonequinha Oriental'
REPLACE INTO `item_buyingstore` VALUES (12367);  -- 'Garrafa de Bebida'
REPLACE INTO `item_buyingstore` VALUES (12368);  -- 'Espelho de Mão'
REPLACE INTO `item_buyingstore` VALUES (12369);  -- 'Oilpalm Coconut'
REPLACE INTO `item_buyingstore` VALUES (12371);  -- 'Magical Lithography'
REPLACE INTO `item_buyingstore` VALUES (12372);  -- 'Hell Contract'
REPLACE INTO `item_buyingstore` VALUES (12373);  -- 'Coração Puro'
REPLACE INTO `item_buyingstore` VALUES (12374);  -- 'Chama Azulada'
REPLACE INTO `item_buyingstore` VALUES (12376);  -- 'Mysterious Can2'
REPLACE INTO `item_buyingstore` VALUES (12377);  -- 'Mysterious PET Bottle2'
REPLACE INTO `item_buyingstore` VALUES (12379);  -- 'Pope Cookie'
REPLACE INTO `item_buyingstore` VALUES (12383);  -- 'Vulcan Bullet Magazine'
REPLACE INTO `item_buyingstore` VALUES (12392);  -- 'Repair a'
REPLACE INTO `item_buyingstore` VALUES (12393);  -- 'Repair b'
REPLACE INTO `item_buyingstore` VALUES (12394);  -- 'Repair c'
REPLACE INTO `item_buyingstore` VALUES (12395);  -- 'Guloseima Recheada'
REPLACE INTO `item_buyingstore` VALUES (12414);  -- 'Bala de Guaraná'
REPLACE INTO `item_buyingstore` VALUES (12717);  -- 'Curare'
REPLACE INTO `item_buyingstore` VALUES (12718);  -- 'Vipera'
REPLACE INTO `item_buyingstore` VALUES (12719);  -- 'Toque do Oblívio'
REPLACE INTO `item_buyingstore` VALUES (12720);  -- 'Beijo da Morte'
REPLACE INTO `item_buyingstore` VALUES (12721);  -- 'Cicuta'
REPLACE INTO `item_buyingstore` VALUES (12722);  -- 'Pirexia'
REPLACE INTO `item_buyingstore` VALUES (12723);  -- 'Waraitake'
REPLACE INTO `item_buyingstore` VALUES (12724);  -- 'Beladona'
REPLACE INTO `item_buyingstore` VALUES (12734);  -- 'Runa Bruta Forte'
REPLACE INTO `item_buyingstore` VALUES (12735);  -- 'Runa Bruta Antiga'
REPLACE INTO `item_buyingstore` VALUES (12736);  -- 'Runa Bruta Mística'
REPLACE INTO `item_buyingstore` VALUES (12737);  -- 'Runa Bruta Comum'
REPLACE INTO `item_buyingstore` VALUES (12738);  -- 'Runa Bruta Rara'
REPLACE INTO `item_buyingstore` VALUES (506);  -- 'Poção Verde'
REPLACE INTO `item_buyingstore` VALUES (507);  -- 'Erva Vermelha'
REPLACE INTO `item_buyingstore` VALUES (508);  -- 'Erva Amarela'
REPLACE INTO `item_buyingstore` VALUES (509);  -- 'Erva Branca'
REPLACE INTO `item_buyingstore` VALUES (510);  -- 'Erva Azul'
REPLACE INTO `item_buyingstore` VALUES (511);  -- 'Erva Verde'
REPLACE INTO `item_buyingstore` VALUES (512);  -- 'Maçã'
REPLACE INTO `item_buyingstore` VALUES (513);  -- 'Banana'
REPLACE INTO `item_buyingstore` VALUES (514);  -- 'Uvas'
REPLACE INTO `item_buyingstore` VALUES (515);  -- 'Cenoura'
REPLACE INTO `item_buyingstore` VALUES (516);  -- 'Batata Doce'
REPLACE INTO `item_buyingstore` VALUES (517);  -- 'Carne'
REPLACE INTO `item_buyingstore` VALUES (518);  -- 'Mel'
REPLACE INTO `item_buyingstore` VALUES (519);  -- 'Leite'
REPLACE INTO `item_buyingstore` VALUES (520);  -- 'Folha de Hinalle'
REPLACE INTO `item_buyingstore` VALUES (521);  -- 'Folha de Aloe'
REPLACE INTO `item_buyingstore` VALUES (522);  -- 'Mastela'
REPLACE INTO `item_buyingstore` VALUES (523);  -- 'Água Benta'
REPLACE INTO `item_buyingstore` VALUES (525);  -- 'Panacéia'
REPLACE INTO `item_buyingstore` VALUES (526);  -- 'Geléia Real'
REPLACE INTO `item_buyingstore` VALUES (528);  -- 'Ração para Monstros'
REPLACE INTO `item_buyingstore` VALUES (529);  -- 'Bala'
REPLACE INTO `item_buyingstore` VALUES (530);  -- 'Bengala Doce'
REPLACE INTO `item_buyingstore` VALUES (531);  -- 'Suco de Maçã'
REPLACE INTO `item_buyingstore` VALUES (532);  -- 'Suco de Banana'
REPLACE INTO `item_buyingstore` VALUES (533);  -- 'Suco de Uva'
REPLACE INTO `item_buyingstore` VALUES (534);  -- 'Suco de Cenoura'
REPLACE INTO `item_buyingstore` VALUES (535);  -- 'Abóbora'
REPLACE INTO `item_buyingstore` VALUES (536);  -- 'Sorvete'
REPLACE INTO `item_buyingstore` VALUES (537);  -- 'Ração para Bichinho'
REPLACE INTO `item_buyingstore` VALUES (538);  -- 'Biscoito de Gengibre'
REPLACE INTO `item_buyingstore` VALUES (539);  -- 'Pedaço de Bolo'
REPLACE INTO `item_buyingstore` VALUES (544);  -- 'Peixe Cru'
REPLACE INTO `item_buyingstore` VALUES (548);  -- 'Queijo'
REPLACE INTO `item_buyingstore` VALUES (549);  -- 'Batata Doce Assada'
REPLACE INTO `item_buyingstore` VALUES (550);  -- 'Bolinhos de Arroz'
REPLACE INTO `item_buyingstore` VALUES (551);  -- 'Sushi'
REPLACE INTO `item_buyingstore` VALUES (553);  -- 'Pão de Carne'
REPLACE INTO `item_buyingstore` VALUES (564);  -- 'Bolinho de Arroz'
REPLACE INTO `item_buyingstore` VALUES (566);  -- 'Sopa Tailandesa'
REPLACE INTO `item_buyingstore` VALUES (567);  -- 'Camarão'
REPLACE INTO `item_buyingstore` VALUES (568);  -- 'Limão'
REPLACE INTO `item_buyingstore` VALUES (569);  -- 'Poção de Aprendiz'
REPLACE INTO `item_buyingstore` VALUES (570);  -- 'Doce da Sorte'
REPLACE INTO `item_buyingstore` VALUES (571);  -- 'Bengala Doce da Sorte'
REPLACE INTO `item_buyingstore` VALUES (572);  -- 'Biscoito da Sorte'
REPLACE INTO `item_buyingstore` VALUES (574);  -- 'Ovo'
REPLACE INTO `item_buyingstore` VALUES (576);  -- 'Fruta Espinhosa'
REPLACE INTO `item_buyingstore` VALUES (577);  -- 'Sacola de Grãos'
REPLACE INTO `item_buyingstore` VALUES (578);  -- 'Morango'
REPLACE INTO `item_buyingstore` VALUES (579);  -- 'Peixe Fresco'
REPLACE INTO `item_buyingstore` VALUES (580);  -- 'Pão'
REPLACE INTO `item_buyingstore` VALUES (581);  -- 'Cogumelo Comestível'
REPLACE INTO `item_buyingstore` VALUES (582);  -- 'Laranja'
REPLACE INTO `item_buyingstore` VALUES (584);  -- 'Sopa com Bolinhos de Peixe'
REPLACE INTO `item_buyingstore` VALUES (587);  -- 'Fruta Espinhosa Escarlate'
REPLACE INTO `item_buyingstore` VALUES (591);  -- 'Panqueca de Caviar'
REPLACE INTO `item_buyingstore` VALUES (592);  -- 'Panqueca de Geléia'
REPLACE INTO `item_buyingstore` VALUES (593);  -- 'Panqueca com Mel'
REPLACE INTO `item_buyingstore` VALUES (594);  -- 'Panqueca Azeda'
REPLACE INTO `item_buyingstore` VALUES (595);  -- 'Panqueca de Cogumelos'
REPLACE INTO `item_buyingstore` VALUES (11513);  -- 'Pastilha Refrescante'
REPLACE INTO `item_buyingstore` VALUES (11515);  -- 'Coco'
REPLACE INTO `item_buyingstore` VALUES (11516);  -- 'Açaí'
REPLACE INTO `item_buyingstore` VALUES (11517);  -- 'Poção Puri'
REPLACE INTO `item_buyingstore` VALUES (701);  -- 'Armadilha para Insetos'
REPLACE INTO `item_buyingstore` VALUES (702);  -- 'Sangue de Animal'
REPLACE INTO `item_buyingstore` VALUES (703);  -- 'Hinalle'
REPLACE INTO `item_buyingstore` VALUES (704);  -- 'Aloés'
REPLACE INTO `item_buyingstore` VALUES (705);  -- 'Trevo'
REPLACE INTO `item_buyingstore` VALUES (706);  -- 'Trevo de Quatro Folhas'
REPLACE INTO `item_buyingstore` VALUES (707);  -- 'Planta da Melodia'
REPLACE INTO `item_buyingstore` VALUES (708);  -- 'Menta'
REPLACE INTO `item_buyingstore` VALUES (709);  -- 'Izidor'
REPLACE INTO `item_buyingstore` VALUES (710);  -- 'Flor das Ilusões'
REPLACE INTO `item_buyingstore` VALUES (711);  -- 'Broto'
REPLACE INTO `item_buyingstore` VALUES (712);  -- 'Flor'
REPLACE INTO `item_buyingstore` VALUES (713);  -- 'Garrafa Vazia'
REPLACE INTO `item_buyingstore` VALUES (715);  -- 'Gema Amarela'
REPLACE INTO `item_buyingstore` VALUES (716);  -- 'Gema Vermelha'
REPLACE INTO `item_buyingstore` VALUES (717);  -- 'Gema Azul'
REPLACE INTO `item_buyingstore` VALUES (718);  -- 'Granada'
REPLACE INTO `item_buyingstore` VALUES (719);  -- 'Ametista'
REPLACE INTO `item_buyingstore` VALUES (720);  -- 'Aquamarina'
REPLACE INTO `item_buyingstore` VALUES (721);  -- 'Esmeralda'
REPLACE INTO `item_buyingstore` VALUES (722);  -- 'Pérola'
REPLACE INTO `item_buyingstore` VALUES (723);  -- 'Rubi'
REPLACE INTO `item_buyingstore` VALUES (724);  -- 'Rubi Amaldiçoado'
REPLACE INTO `item_buyingstore` VALUES (725);  -- 'Peridoto'
REPLACE INTO `item_buyingstore` VALUES (726);  -- 'Safira'
REPLACE INTO `item_buyingstore` VALUES (727);  -- 'Opala'
REPLACE INTO `item_buyingstore` VALUES (728);  -- 'Topázio'
REPLACE INTO `item_buyingstore` VALUES (729);  -- 'Zircônio'
REPLACE INTO `item_buyingstore` VALUES (730);  -- 'Diamante de 1 quilate'
REPLACE INTO `item_buyingstore` VALUES (731);  -- 'Diamante de 2 quilates'
REPLACE INTO `item_buyingstore` VALUES (732);  -- 'Diamante de 3 quilates'
REPLACE INTO `item_buyingstore` VALUES (733);  -- 'Diamante Rachado'
REPLACE INTO `item_buyingstore` VALUES (734);  -- 'Moldura Vermelha'
REPLACE INTO `item_buyingstore` VALUES (735);  -- 'Chung Jah'
REPLACE INTO `item_buyingstore` VALUES (736);  -- 'Prato de Porcelana'
REPLACE INTO `item_buyingstore` VALUES (737);  -- 'Concha Preta'
REPLACE INTO `item_buyingstore` VALUES (738);  -- 'Estojo de Lápis'
REPLACE INTO `item_buyingstore` VALUES (739);  -- 'Batom'
REPLACE INTO `item_buyingstore` VALUES (740);  -- 'Boneco de Pelúcia'
REPLACE INTO `item_buyingstore` VALUES (741);  -- 'Boneco de Poring'
REPLACE INTO `item_buyingstore` VALUES (742);  -- 'Boneco de Chonchon'
REPLACE INTO `item_buyingstore` VALUES (743);  -- 'Boneco de Esporo'
REPLACE INTO `item_buyingstore` VALUES (744);  -- 'Buquê'
REPLACE INTO `item_buyingstore` VALUES (745);  -- 'Buquê de Casamento'
REPLACE INTO `item_buyingstore` VALUES (746);  -- 'Bolinha de Gude'
REPLACE INTO `item_buyingstore` VALUES (747);  -- 'Espelho de Cristal'
REPLACE INTO `item_buyingstore` VALUES (748);  -- 'Rosa Eterna'
REPLACE INTO `item_buyingstore` VALUES (749);  -- 'Rosa de Gelo'
REPLACE INTO `item_buyingstore` VALUES (750);  -- 'Boneco de Bafomé'
REPLACE INTO `item_buyingstore` VALUES (751);  -- 'Boneco de Osíris'
REPLACE INTO `item_buyingstore` VALUES (752);  -- 'Boneco de Rocker'
REPLACE INTO `item_buyingstore` VALUES (753);  -- 'Boneco de Yoyo'
REPLACE INTO `item_buyingstore` VALUES (754);  -- 'Boneco de Fumacento'
REPLACE INTO `item_buyingstore` VALUES (756);  -- 'Minério de Oridecon'
REPLACE INTO `item_buyingstore` VALUES (757);  -- 'Minério de Elunium'
REPLACE INTO `item_buyingstore` VALUES (901);  -- 'Trança'
REPLACE INTO `item_buyingstore` VALUES (902);  -- 'Raiz de Árvore'
REPLACE INTO `item_buyingstore` VALUES (903);  -- 'Língua de Réptil'
REPLACE INTO `item_buyingstore` VALUES (904);  -- 'Cauda de Escorpião'
REPLACE INTO `item_buyingstore` VALUES (905);  -- 'Caule'
REPLACE INTO `item_buyingstore` VALUES (906);  -- 'Escama Afiada'
REPLACE INTO `item_buyingstore` VALUES (907);  -- 'Resina'
REPLACE INTO `item_buyingstore` VALUES (908);  -- 'Ova de Sapo'
REPLACE INTO `item_buyingstore` VALUES (909);  -- 'Jellopy'
REPLACE INTO `item_buyingstore` VALUES (910);  -- 'Garleta'
REPLACE INTO `item_buyingstore` VALUES (911);  -- 'Scell'
REPLACE INTO `item_buyingstore` VALUES (912);  -- 'Zargônio'
REPLACE INTO `item_buyingstore` VALUES (913);  -- 'Dente de Morcego'
REPLACE INTO `item_buyingstore` VALUES (914);  -- 'Felpa'
REPLACE INTO `item_buyingstore` VALUES (915);  -- 'Crisálida'
REPLACE INTO `item_buyingstore` VALUES (916);  -- 'Plumas de Ave'
REPLACE INTO `item_buyingstore` VALUES (917);  -- 'Garra de Ave'
REPLACE INTO `item_buyingstore` VALUES (918);  -- 'Pata Pegajosa'
REPLACE INTO `item_buyingstore` VALUES (919);  -- 'Couro de Animal'
REPLACE INTO `item_buyingstore` VALUES (920);  -- 'Garra de Lobo'
REPLACE INTO `item_buyingstore` VALUES (921);  -- 'Esporo de Cogumelo'
REPLACE INTO `item_buyingstore` VALUES (922);  -- 'Presa de Orc'
REPLACE INTO `item_buyingstore` VALUES (923);  -- 'Chifre Diabólico'
REPLACE INTO `item_buyingstore` VALUES (924);  -- 'Pó de Borboleta'
REPLACE INTO `item_buyingstore` VALUES (925);  -- 'Bico de Ave'
REPLACE INTO `item_buyingstore` VALUES (926);  -- 'Escamas de Cobra'
REPLACE INTO `item_buyingstore` VALUES (928);  -- 'Antenas de Inseto'
REPLACE INTO `item_buyingstore` VALUES (929);  -- 'Coração Imortal'
REPLACE INTO `item_buyingstore` VALUES (930);  -- 'Bandagem Estragada'
REPLACE INTO `item_buyingstore` VALUES (931);  -- 'Amuleto dos Orcs'
REPLACE INTO `item_buyingstore` VALUES (932);  -- 'Osso'
REPLACE INTO `item_buyingstore` VALUES (934);  -- 'Espólio'
REPLACE INTO `item_buyingstore` VALUES (935);  -- 'Casca'
REPLACE INTO `item_buyingstore` VALUES (936);  -- 'Casca Escamada'
REPLACE INTO `item_buyingstore` VALUES (937);  -- 'Canino Venenoso'
REPLACE INTO `item_buyingstore` VALUES (938);  -- 'Muco Pegajoso'
REPLACE INTO `item_buyingstore` VALUES (939);  -- 'Ferrão de Abelha'
REPLACE INTO `item_buyingstore` VALUES (940);  -- 'Perna de Gafanhoto'
REPLACE INTO `item_buyingstore` VALUES (941);  -- 'Argola'
REPLACE INTO `item_buyingstore` VALUES (942);  -- 'Cauda de Yoyo'
REPLACE INTO `item_buyingstore` VALUES (943);  -- 'Casca Rija'
REPLACE INTO `item_buyingstore` VALUES (944);  -- 'Ferradura'
REPLACE INTO `item_buyingstore` VALUES (945);  -- 'Folha de Fumacento'
REPLACE INTO `item_buyingstore` VALUES (946);  -- 'Casco de Caramujo'
REPLACE INTO `item_buyingstore` VALUES (947);  -- 'Chifre'
REPLACE INTO `item_buyingstore` VALUES (948);  -- 'Pata de Urso'
REPLACE INTO `item_buyingstore` VALUES (949);  -- 'Pluma'
REPLACE INTO `item_buyingstore` VALUES (950);  -- 'Coração de Sereia'
REPLACE INTO `item_buyingstore` VALUES (951);  -- 'Nadadeira'
REPLACE INTO `item_buyingstore` VALUES (952);  -- 'Espinho de Cacto'
REPLACE INTO `item_buyingstore` VALUES (953);  -- 'Coração de Pedra'
REPLACE INTO `item_buyingstore` VALUES (954);  -- 'Escama Brilhante'
REPLACE INTO `item_buyingstore` VALUES (955);  -- 'Pele de Verme'
REPLACE INTO `item_buyingstore` VALUES (956);  -- 'Guelra'
REPLACE INTO `item_buyingstore` VALUES (957);  -- 'Unha Apodrecida'
REPLACE INTO `item_buyingstore` VALUES (958);  -- 'Mandíbula Horrenda'
REPLACE INTO `item_buyingstore` VALUES (959);  -- 'Escama Fétida'
REPLACE INTO `item_buyingstore` VALUES (960);  -- 'Garra de Crustáceo'
REPLACE INTO `item_buyingstore` VALUES (961);  -- 'Concha'
REPLACE INTO `item_buyingstore` VALUES (962);  -- 'Tentáculo'
REPLACE INTO `item_buyingstore` VALUES (963);  -- 'Escama Aquática'
REPLACE INTO `item_buyingstore` VALUES (964);  -- 'Casco de Caranguejo'
REPLACE INTO `item_buyingstore` VALUES (965);  -- 'Casco de Ostra'
REPLACE INTO `item_buyingstore` VALUES (966);  -- 'Carne de Ostra'
REPLACE INTO `item_buyingstore` VALUES (967);  -- 'Casco de Tartaruga'
REPLACE INTO `item_buyingstore` VALUES (968);  -- 'Insígnia do Herói'
REPLACE INTO `item_buyingstore` VALUES (969);  -- 'Ouro'
REPLACE INTO `item_buyingstore` VALUES (971);  -- 'Detrimindexta'
REPLACE INTO `item_buyingstore` VALUES (972);  -- 'Karvodailnirol'
REPLACE INTO `item_buyingstore` VALUES (973);  -- 'Antígeno'
REPLACE INTO `item_buyingstore` VALUES (974);  -- 'Mistura'
REPLACE INTO `item_buyingstore` VALUES (975);  -- 'Tintura Vermelha'
REPLACE INTO `item_buyingstore` VALUES (976);  -- 'Tintura Amarela'
REPLACE INTO `item_buyingstore` VALUES (978);  -- 'Tintura Azul'
REPLACE INTO `item_buyingstore` VALUES (979);  -- 'Tintura Verde'
REPLACE INTO `item_buyingstore` VALUES (980);  -- 'Tintura Laranja'
REPLACE INTO `item_buyingstore` VALUES (981);  -- 'Tintura Violeta'
REPLACE INTO `item_buyingstore` VALUES (982);  -- 'Tintura Branca'
REPLACE INTO `item_buyingstore` VALUES (983);  -- 'Tintura Preta'
REPLACE INTO `item_buyingstore` VALUES (984);  -- 'Oridecon'
REPLACE INTO `item_buyingstore` VALUES (985);  -- 'Elunium'
REPLACE INTO `item_buyingstore` VALUES (986);  -- 'Bigorna'
REPLACE INTO `item_buyingstore` VALUES (987);  -- 'Bigorna de Oridecon'
REPLACE INTO `item_buyingstore` VALUES (988);  -- 'Bigorna de Ouro'
REPLACE INTO `item_buyingstore` VALUES (989);  -- 'Bigorna de Emperium'
REPLACE INTO `item_buyingstore` VALUES (990);  -- 'Sangue Escarlate'
REPLACE INTO `item_buyingstore` VALUES (991);  -- 'Cristal Azul'
REPLACE INTO `item_buyingstore` VALUES (992);  -- 'Frescor do Vento'
REPLACE INTO `item_buyingstore` VALUES (993);  -- 'Vida Verdejante'
REPLACE INTO `item_buyingstore` VALUES (994);  -- 'Coração Flamejante'
REPLACE INTO `item_buyingstore` VALUES (995);  -- 'Gelo Místico'
REPLACE INTO `item_buyingstore` VALUES (996);  -- 'Vento Bruto'
REPLACE INTO `item_buyingstore` VALUES (997);  -- 'Natureza Grandiosa'
REPLACE INTO `item_buyingstore` VALUES (998);  -- 'Ferro'
REPLACE INTO `item_buyingstore` VALUES (999);  -- 'Aço'
REPLACE INTO `item_buyingstore` VALUES (1000);  -- 'Fragmento Estelar'
REPLACE INTO `item_buyingstore` VALUES (1001);  -- 'Poeira Estelar'
REPLACE INTO `item_buyingstore` VALUES (1002);  -- 'Minério de Ferro'
REPLACE INTO `item_buyingstore` VALUES (1003);  -- 'Carvão'
REPLACE INTO `item_buyingstore` VALUES (1004);  -- 'Insígnia da Cavalaria'
REPLACE INTO `item_buyingstore` VALUES (1005);  -- 'Martelo de Ferreiro'
REPLACE INTO `item_buyingstore` VALUES (1006);  -- 'Grimório Antigo'
REPLACE INTO `item_buyingstore` VALUES (1007);  -- 'Colar da Sabedoria'
REPLACE INTO `item_buyingstore` VALUES (1008);  -- 'Colar do Oblívio'
REPLACE INTO `item_buyingstore` VALUES (1009);  -- 'Mão Divina'
REPLACE INTO `item_buyingstore` VALUES (1010);  -- 'Fracon'
REPLACE INTO `item_buyingstore` VALUES (1011);  -- 'Emveretarcon'
REPLACE INTO `item_buyingstore` VALUES (1012);  -- 'Brasão'
REPLACE INTO `item_buyingstore` VALUES (1013);  -- 'Casco Arco-Íris'
REPLACE INTO `item_buyingstore` VALUES (1014);  -- 'Mandíbula de Formiga'
REPLACE INTO `item_buyingstore` VALUES (1015);  -- 'Língua'
REPLACE INTO `item_buyingstore` VALUES (1016);  -- 'Cauda de Rato'
REPLACE INTO `item_buyingstore` VALUES (1017);  -- 'Bigodes de Toupeira'
REPLACE INTO `item_buyingstore` VALUES (1018);  -- 'Garras de Toupeira'
REPLACE INTO `item_buyingstore` VALUES (1019);  -- 'Tronco'
REPLACE INTO `item_buyingstore` VALUES (1020);  -- 'Cabelos Morenos'
REPLACE INTO `item_buyingstore` VALUES (1021);  -- 'Chifre de Dokebi'
REPLACE INTO `item_buyingstore` VALUES (1022);  -- 'Nove-Caudas'
REPLACE INTO `item_buyingstore` VALUES (1023);  -- 'Cauda de Peixe'
REPLACE INTO `item_buyingstore` VALUES (1024);  -- 'Tinta de Polvo'
REPLACE INTO `item_buyingstore` VALUES (1025);  -- 'Teia de Aranha'
REPLACE INTO `item_buyingstore` VALUES (1026);  -- 'Avelã'
REPLACE INTO `item_buyingstore` VALUES (1027);  -- 'Espinho de Porco-Espinho'
REPLACE INTO `item_buyingstore` VALUES (1028);  -- 'Crina'
REPLACE INTO `item_buyingstore` VALUES (1029);  -- 'Pele de Tigre'
REPLACE INTO `item_buyingstore` VALUES (1030);  -- 'Pata de Tigre'
REPLACE INTO `item_buyingstore` VALUES (1031);  -- 'Foice de Louva-a-Deus'
REPLACE INTO `item_buyingstore` VALUES (1032);  -- 'Flor de Planta Carnívora'
REPLACE INTO `item_buyingstore` VALUES (1033);  -- 'Raiz de Planta Carnívora'
REPLACE INTO `item_buyingstore` VALUES (1034);  -- 'Cabelo Azul'
REPLACE INTO `item_buyingstore` VALUES (1035);  -- 'Canino de Dragão'
REPLACE INTO `item_buyingstore` VALUES (1036);  -- 'Escama de Dragão'
REPLACE INTO `item_buyingstore` VALUES (1037);  -- 'Cauda de Dragão'
REPLACE INTO `item_buyingstore` VALUES (1038);  -- 'Pequeno Chifre Maligno'
REPLACE INTO `item_buyingstore` VALUES (1039);  -- 'Pequena Asa Maligna'
REPLACE INTO `item_buyingstore` VALUES (1040);  -- 'Bigode de Anão Ancião'
REPLACE INTO `item_buyingstore` VALUES (1041);  -- 'Lampião'
REPLACE INTO `item_buyingstore` VALUES (1042);  -- 'Pata de Inseto'
REPLACE INTO `item_buyingstore` VALUES (1043);  -- 'Garra de Orc'
REPLACE INTO `item_buyingstore` VALUES (1044);  -- 'Presa de Zenorc'
REPLACE INTO `item_buyingstore` VALUES (1045);  -- 'Máscara Ritualística'
REPLACE INTO `item_buyingstore` VALUES (1046);  -- 'Garra de Escorpião'
REPLACE INTO `item_buyingstore` VALUES (1047);  -- 'Cabeça de Medusa'
REPLACE INTO `item_buyingstore` VALUES (1048);  -- 'Cabelo Horrendo'
REPLACE INTO `item_buyingstore` VALUES (1049);  -- 'Saia Virginal'
REPLACE INTO `item_buyingstore` VALUES (1050);  -- 'Tendões'
REPLACE INTO `item_buyingstore` VALUES (1051);  -- 'Neurônio'
REPLACE INTO `item_buyingstore` VALUES (1052);  -- 'Célula Única'
REPLACE INTO `item_buyingstore` VALUES (1053);  -- 'Dente Fossilizado'
REPLACE INTO `item_buyingstore` VALUES (1054);  -- 'Lábios Fossilizados'
REPLACE INTO `item_buyingstore` VALUES (1055);  -- 'Pele de Minhoca'
REPLACE INTO `item_buyingstore` VALUES (1056);  -- 'Torrão de Areia'
REPLACE INTO `item_buyingstore` VALUES (1057);  -- 'Pó de Traça'
REPLACE INTO `item_buyingstore` VALUES (1058);  -- 'Asas de Traça'
REPLACE INTO `item_buyingstore` VALUES (1059);  -- 'Tecido'
REPLACE INTO `item_buyingstore` VALUES (1060);  -- 'Cabelos Dourados'
REPLACE INTO `item_buyingstore` VALUES (1061);  -- 'Areia Estelar de Bruxa'
REPLACE INTO `item_buyingstore` VALUES (1062);  -- 'Zé-Lanterna'
REPLACE INTO `item_buyingstore` VALUES (1063);  -- 'Presa'
REPLACE INTO `item_buyingstore` VALUES (1064);  -- 'Rédeas'
REPLACE INTO `item_buyingstore` VALUES (1065);  -- 'Armadilha'
REPLACE INTO `item_buyingstore` VALUES (1066);  -- 'Tronco de Alta Qualidade'
REPLACE INTO `item_buyingstore` VALUES (1067);  -- 'Tronco Sólido'
REPLACE INTO `item_buyingstore` VALUES (1068);  -- 'Tronco Estéril'
REPLACE INTO `item_buyingstore` VALUES (1088);  -- 'Solução de Morroc'
REPLACE INTO `item_buyingstore` VALUES (1089);  -- 'Solução de Payon'
REPLACE INTO `item_buyingstore` VALUES (1092);  -- 'Tubo de Ensaio'
REPLACE INTO `item_buyingstore` VALUES (1093);  -- 'Garrafa de Poção'
REPLACE INTO `item_buyingstore` VALUES (1094);  -- 'Trança Curta'
REPLACE INTO `item_buyingstore` VALUES (1095);  -- 'Ponteiro'
REPLACE INTO `item_buyingstore` VALUES (1096);  -- 'Casca Arredondada'
REPLACE INTO `item_buyingstore` VALUES (1097);  -- 'Página Deteriorada'
REPLACE INTO `item_buyingstore` VALUES (1098);  -- 'Algemas'
REPLACE INTO `item_buyingstore` VALUES (1099);  -- 'Uniforme Velho de Presidiário'
REPLACE INTO `item_buyingstore` VALUES (6001);  -- 'Essência de Fogo'
REPLACE INTO `item_buyingstore` VALUES (6002);  -- 'Medalhão do Apóstolo'
REPLACE INTO `item_buyingstore` VALUES (6003);  -- 'Pingente do Espírito'
REPLACE INTO `item_buyingstore` VALUES (6004);  -- 'Boneco de Bafomé Maldito'
REPLACE INTO `item_buyingstore` VALUES (6008);  -- 'Wood'
REPLACE INTO `item_buyingstore` VALUES (6010);  -- 'Picareta'
REPLACE INTO `item_buyingstore` VALUES (6020);  -- 'Pêlo'
REPLACE INTO `item_buyingstore` VALUES (6021);  -- 'Chapéu Pontudo'
REPLACE INTO `item_buyingstore` VALUES (6022);  -- 'Pele Dura'
REPLACE INTO `item_buyingstore` VALUES (6023);  -- 'Chifre Místico'
REPLACE INTO `item_buyingstore` VALUES (6032);  -- 'Chifre de Leão da Montanha'
REPLACE INTO `item_buyingstore` VALUES (6033);  -- 'Chifre de Leão de Vinhas'
REPLACE INTO `item_buyingstore` VALUES (6073);  -- 'Crina de Dragão'
REPLACE INTO `item_buyingstore` VALUES (6075);  -- 'Lágrima Cristalizada'
REPLACE INTO `item_buyingstore` VALUES (6086);  -- 'Flor Murcha'
REPLACE INTO `item_buyingstore` VALUES (6087);  -- 'Crista Espiritual Azul'
REPLACE INTO `item_buyingstore` VALUES (6088);  -- 'Crista Espiritual Vermelha'
REPLACE INTO `item_buyingstore` VALUES (6089);  -- 'Fragmento Sombrio'
REPLACE INTO `item_buyingstore` VALUES (6090);  -- 'Bradium Purificado'
REPLACE INTO `item_buyingstore` VALUES (6091);  -- 'Escama Vermelha-Escura'
REPLACE INTO `item_buyingstore` VALUES (6095);  -- 'Líquido Aromatizado'
REPLACE INTO `item_buyingstore` VALUES (6096);  -- 'Peixe Azulado'
REPLACE INTO `item_buyingstore` VALUES (6097);  -- 'Torta Assustadora'
REPLACE INTO `item_buyingstore` VALUES (6098);  -- 'Cristal de Neve'
REPLACE INTO `item_buyingstore` VALUES (6099);  -- 'Grilled Rice Cake'
REPLACE INTO `item_buyingstore` VALUES (6100);  -- 'Fumaça Negra'
REPLACE INTO `item_buyingstore` VALUES (6104);  -- 'Cristal Gigante'
REPLACE INTO `item_buyingstore` VALUES (6105);  -- 'Orvalho da Manhã'
REPLACE INTO `item_buyingstore` VALUES (6106);  -- 'Morango Maduro'
REPLACE INTO `item_buyingstore` VALUES (6107);  -- 'Coquetel de Verão'
REPLACE INTO `item_buyingstore` VALUES (6108);  -- 'Gelatina de Maçã'
REPLACE INTO `item_buyingstore` VALUES (6109);  -- 'Plant Neutrient'
REPLACE INTO `item_buyingstore` VALUES (6110);  -- 'Flor Vívida'
REPLACE INTO `item_buyingstore` VALUES (6111);  -- 'Mystic Stone'
REPLACE INTO `item_buyingstore` VALUES (6112);  -- 'Fresh Plant'
REPLACE INTO `item_buyingstore` VALUES (6113);  -- 'Flor Vital'
REPLACE INTO `item_buyingstore` VALUES (6114);  -- 'Gema em Chamas'
REPLACE INTO `item_buyingstore` VALUES (6115);  -- 'Bolinho Quente'
REPLACE INTO `item_buyingstore` VALUES (6120);  -- 'Tinta para Parede'
REPLACE INTO `item_buyingstore` VALUES (6123);  -- 'Surface Paint'
REPLACE INTO `item_buyingstore` VALUES (6128);  -- 'Antídoto'
REPLACE INTO `item_buyingstore` VALUES (6144);  -- 'Lágrimas de Arrependimento'
REPLACE INTO `item_buyingstore` VALUES (6145);  -- 'Cápsula Incandescente'
REPLACE INTO `item_buyingstore` VALUES (6146);  -- 'Combustível Diferenciado Leve'
REPLACE INTO `item_buyingstore` VALUES (6147);  -- 'Cápsula de Nitrogênio Líquido'
REPLACE INTO `item_buyingstore` VALUES (6186);  -- 'Chave Inglesa'
REPLACE INTO `item_buyingstore` VALUES (6189);  -- 'Grimório de Lanças de Fogo'
REPLACE INTO `item_buyingstore` VALUES (6190);  -- 'Grimório de Lanças de Gelo'
REPLACE INTO `item_buyingstore` VALUES (6191);  -- 'Grimório de Relâmpago'
REPLACE INTO `item_buyingstore` VALUES (6192);  -- 'Grimório de Nevasca'
REPLACE INTO `item_buyingstore` VALUES (6193);  -- 'Grimório de Ira de Thor'
REPLACE INTO `item_buyingstore` VALUES (6194);  -- 'Grimório de Chuva de Meteoros'
REPLACE INTO `item_buyingstore` VALUES (6195);  -- 'Grimório de Cometa'
REPLACE INTO `item_buyingstore` VALUES (6196);  -- 'Grimório de Tetra Vortex'
REPLACE INTO `item_buyingstore` VALUES (6197);  -- 'Grimório de Tempestade de Raios'
REPLACE INTO `item_buyingstore` VALUES (6198);  -- 'Grimório de Trovão de Júpiter'
REPLACE INTO `item_buyingstore` VALUES (6199);  -- 'Grimório de Esferas DNULLÁgua'
REPLACE INTO `item_buyingstore` VALUES (6200);  -- 'Grimório de Fúria da Terra'
REPLACE INTO `item_buyingstore` VALUES (6201);  -- 'Grimório de Coluna de Pedra'
REPLACE INTO `item_buyingstore` VALUES (6202);  -- 'Grimório de Abalo Sísmico'
REPLACE INTO `item_buyingstore` VALUES (6203);  -- 'Grimório de Corrente Elétrica'
REPLACE INTO `item_buyingstore` VALUES (6204);  -- 'Grimório de Meteoro Escarlate'
REPLACE INTO `item_buyingstore` VALUES (6205);  -- 'Grimório de Drenar Vida'
REPLACE INTO `item_buyingstore` VALUES (6210);  -- 'Semente de Planta Selvagem'
REPLACE INTO `item_buyingstore` VALUES (6211);  -- 'Semente de Planta Sanguessuga'
REPLACE INTO `item_buyingstore` VALUES (6212);  -- 'Esporo de Cogumelo Explosivo'
REPLACE INTO `item_buyingstore` VALUES (6213);  -- 'Pó Explosivo'
REPLACE INTO `item_buyingstore` VALUES (6214);  -- 'Gás de Fumaça'
REPLACE INTO `item_buyingstore` VALUES (6215);  -- 'Gás Lacrimejante'
REPLACE INTO `item_buyingstore` VALUES (6216);  -- 'Garrafa com Óleo'
REPLACE INTO `item_buyingstore` VALUES (6217);  -- 'Muda de Mandrágora'
REPLACE INTO `item_buyingstore` VALUES (6223);  -- 'Carnium'
REPLACE INTO `item_buyingstore` VALUES (6224);  -- 'Bradium'
REPLACE INTO `item_buyingstore` VALUES (6244);  -- 'Mistura de Pólvora'
REPLACE INTO `item_buyingstore` VALUES (6245);  -- 'Pó Negro'
REPLACE INTO `item_buyingstore` VALUES (6246);  -- 'Pó Amarelo'
REPLACE INTO `item_buyingstore` VALUES (6247);  -- 'Pó Branco'
REPLACE INTO `item_buyingstore` VALUES (6248);  -- 'Vasilha Melange'
REPLACE INTO `item_buyingstore` VALUES (6249);  -- 'Carne de Selvagem'
REPLACE INTO `item_buyingstore` VALUES (6250);  -- 'Espeto de Cozinha'
REPLACE INTO `item_buyingstore` VALUES (6251);  -- 'Carvão Negro'
REPLACE INTO `item_buyingstore` VALUES (6252);  -- 'Sangue de Lobo'
REPLACE INTO `item_buyingstore` VALUES (6253);  -- 'Gelo'
REPLACE INTO `item_buyingstore` VALUES (6254);  -- 'Medalhões de Carne'
REPLACE INTO `item_buyingstore` VALUES (6255);  -- 'Vasilha Grande'
REPLACE INTO `item_buyingstore` VALUES (6256);  -- 'Raspadinha'
REPLACE INTO `item_buyingstore` VALUES (6257);  -- 'Gelo Cristalino'
REPLACE INTO `item_buyingstore` VALUES (6258);  -- 'Fruta de Comodo'
REPLACE INTO `item_buyingstore` VALUES (6259);  -- 'Tentáculo de Drosera'
REPLACE INTO `item_buyingstore` VALUES (6260);  -- 'Rabo de Petite'
REPLACE INTO `item_buyingstore` VALUES (6261);  -- 'Macarrão Fino'
REPLACE INTO `item_buyingstore` VALUES (6262);  -- 'Molho Especial'
REPLACE INTO `item_buyingstore` VALUES (6263);  -- 'Coco Fresco'
REPLACE INTO `item_buyingstore` VALUES (6264);  -- 'Melão'
REPLACE INTO `item_buyingstore` VALUES (6265);  -- 'Abacaxi'
REPLACE INTO `item_buyingstore` VALUES (6279);  -- 'Livro de Bombas de Maçã'
REPLACE INTO `item_buyingstore` VALUES (6280);  -- 'Livro de Bombas de Abacaxi'
REPLACE INTO `item_buyingstore` VALUES (6281);  -- 'Livro de Bombas de Coco'
REPLACE INTO `item_buyingstore` VALUES (6282);  -- 'Livro de Bombas de Melão'
REPLACE INTO `item_buyingstore` VALUES (6283);  -- 'Livro de Bombas de Banana'
REPLACE INTO `item_buyingstore` VALUES (6284);  -- 'Livro de Genética Vegetal'
REPLACE INTO `item_buyingstore` VALUES (6285);  -- 'Livro de Farmacologia'
REPLACE INTO `item_buyingstore` VALUES (6297);  -- 'Garrafa de Arremesso'
REPLACE INTO `item_buyingstore` VALUES (6321);  -- 'Rake Helmet'
REPLACE INTO `item_buyingstore` VALUES (6322);  -- 'Antler Helmet'
REPLACE INTO `item_buyingstore` VALUES (6323);  -- 'Two-Horn Helmet'
REPLACE INTO `item_buyingstore` VALUES (6324);  -- 'One-Horn Helmet'
REPLACE INTO `item_buyingstore` VALUES (6325);  -- 'White Spider Legs'
REPLACE INTO `item_buyingstore` VALUES (6326);  -- 'Queen Scraba Shell'
REPLACE INTO `item_buyingstore` VALUES (6360);  -- 'Fragmento Escarlate'
REPLACE INTO `item_buyingstore` VALUES (6361);  -- 'Fragmento Azul'
REPLACE INTO `item_buyingstore` VALUES (6362);  -- 'Fragmento Amarelo'
REPLACE INTO `item_buyingstore` VALUES (6363);  -- 'FragmentoVerde'
REPLACE INTO `item_buyingstore` VALUES (7001);  -- 'Pó de Bolor'
REPLACE INTO `item_buyingstore` VALUES (7002);  -- 'Dente de Ogro'
REPLACE INTO `item_buyingstore` VALUES (7003);  -- 'Pele de Anolian'
REPLACE INTO `item_buyingstore` VALUES (7004);  -- 'Monte de Lama'
REPLACE INTO `item_buyingstore` VALUES (7005);  -- 'Crânio'
REPLACE INTO `item_buyingstore` VALUES (7006);  -- 'Asa de Morcego Vermelho'
REPLACE INTO `item_buyingstore` VALUES (7007);  -- 'Garra de Rato'
REPLACE INTO `item_buyingstore` VALUES (7008);  -- 'Chifre Firme'
REPLACE INTO `item_buyingstore` VALUES (7009);  -- 'Casca Brilhante'
REPLACE INTO `item_buyingstore` VALUES (7010);  -- 'Cauda de Escorpião de Aço'
REPLACE INTO `item_buyingstore` VALUES (7011);  -- 'Garra de Macaco'
REPLACE INTO `item_buyingstore` VALUES (7012);  -- 'Pedaço de Escama Dura'
REPLACE INTO `item_buyingstore` VALUES (7013);  -- 'Coral'
REPLACE INTO `item_buyingstore` VALUES (7014);  -- 'Retrato Velho'
REPLACE INTO `item_buyingstore` VALUES (7015);  -- 'Marca-Página'
REPLACE INTO `item_buyingstore` VALUES (7016);  -- 'Colher Entortada'
REPLACE INTO `item_buyingstore` VALUES (7017);  -- 'Luva do Carrasco'
REPLACE INTO `item_buyingstore` VALUES (7018);  -- 'Graveto de Visco'
REPLACE INTO `item_buyingstore` VALUES (7019);  -- 'Sussurros de Loki'
REPLACE INTO `item_buyingstore` VALUES (7020);  -- 'Pesadelo Maternal'
REPLACE INTO `item_buyingstore` VALUES (7021);  -- 'Tolice do Cego'
REPLACE INTO `item_buyingstore` VALUES (7022);  -- 'Bainha Velha'
REPLACE INTO `item_buyingstore` VALUES (7023);  -- 'Lâmina Perdida nas Trevas'
REPLACE INTO `item_buyingstore` VALUES (7024);  -- 'Lâmina Ensanguentada'
REPLACE INTO `item_buyingstore` VALUES (7026);  -- 'Chave para a Torre do Relógio'
REPLACE INTO `item_buyingstore` VALUES (7027);  -- 'Chave para o Subterrâneo'
REPLACE INTO `item_buyingstore` VALUES (7030);  -- 'Garra de Lobo do Deserto'
REPLACE INTO `item_buyingstore` VALUES (7031);  -- 'Frigideira Velha'
REPLACE INTO `item_buyingstore` VALUES (7032);  -- 'Pedaço de Casca de Ovo'
REPLACE INTO `item_buyingstore` VALUES (7033);  -- 'Esporo Venenoso'
REPLACE INTO `item_buyingstore` VALUES (7034);  -- 'Meia Furada'
REPLACE INTO `item_buyingstore` VALUES (7035);  -- 'Palito de Fósforo'
REPLACE INTO `item_buyingstore` VALUES (7036);  -- 'Presa de Hati'
REPLACE INTO `item_buyingstore` VALUES (7038);  -- 'Novelo'
REPLACE INTO `item_buyingstore` VALUES (7041);  -- 'Torrão de Areia Fina'
REPLACE INTO `item_buyingstore` VALUES (7043);  -- 'Areia Fina'
REPLACE INTO `item_buyingstore` VALUES (7047);  -- 'Avental de Alice'
REPLACE INTO `item_buyingstore` VALUES (7048);  -- 'Garra de Grifo'
REPLACE INTO `item_buyingstore` VALUES (7049);  -- 'Pedra'
REPLACE INTO `item_buyingstore` VALUES (7053);  -- 'Cyfar'
REPLACE INTO `item_buyingstore` VALUES (7054);  -- 'Brigan'
REPLACE INTO `item_buyingstore` VALUES (7055);  -- 'Cocô de Bichinho'
REPLACE INTO `item_buyingstore` VALUES (7056);  -- 'Extrato de Pagamento'
REPLACE INTO `item_buyingstore` VALUES (7057);  -- 'Gjallar'
REPLACE INTO `item_buyingstore` VALUES (7058);  -- 'Gleipnir'
REPLACE INTO `item_buyingstore` VALUES (7063);  -- 'Pena Macia'
REPLACE INTO `item_buyingstore` VALUES (7064);  -- 'Asas de Libélula'
REPLACE INTO `item_buyingstore` VALUES (7065);  -- 'Pele de Lontra'
REPLACE INTO `item_buyingstore` VALUES (7066);  -- 'Cubo de Gelo'
REPLACE INTO `item_buyingstore` VALUES (7067);  -- 'Pedaço de Pedra'
REPLACE INTO `item_buyingstore` VALUES (7068);  -- 'Madeira Queimada'
REPLACE INTO `item_buyingstore` VALUES (7069);  -- 'Armadura Destruída'
REPLACE INTO `item_buyingstore` VALUES (7070);  -- 'Casca Quebrada'
REPLACE INTO `item_buyingstore` VALUES (7071);  -- 'Farrapos'
REPLACE INTO `item_buyingstore` VALUES (7072);  -- 'Shuriken Gasto'
REPLACE INTO `item_buyingstore` VALUES (7073);  -- 'Lágrimas de Freyja'
REPLACE INTO `item_buyingstore` VALUES (7074);  -- 'Manopla de Thor'
REPLACE INTO `item_buyingstore` VALUES (7075);  -- 'Dama de Ferro'
REPLACE INTO `item_buyingstore` VALUES (7076);  -- 'Roda desconhecida'
REPLACE INTO `item_buyingstore` VALUES (7077);  -- 'Ornamento de Prata'
REPLACE INTO `item_buyingstore` VALUES (7078);  -- 'Fúria das Valquírias'
REPLACE INTO `item_buyingstore` VALUES (7079);  -- 'Pena de Asas Angelicais'
REPLACE INTO `item_buyingstore` VALUES (7080);  -- 'Passos de Gato'
REPLACE INTO `item_buyingstore` VALUES (7081);  -- 'Barbas de Mulher'
REPLACE INTO `item_buyingstore` VALUES (7082);  -- 'Raiz de Montanha'
REPLACE INTO `item_buyingstore` VALUES (7083);  -- 'Hálito de Peixe'
REPLACE INTO `item_buyingstore` VALUES (7084);  -- 'Saliva de Ave'
REPLACE INTO `item_buyingstore` VALUES (7085);  -- 'Nervos de Urso'
REPLACE INTO `item_buyingstore` VALUES (7086);  -- 'Símbolo do Deus-Sol'
REPLACE INTO `item_buyingstore` VALUES (7087);  -- 'Essência de Espírito'
REPLACE INTO `item_buyingstore` VALUES (7088);  -- 'Floco de Neve'
REPLACE INTO `item_buyingstore` VALUES (7089);  -- 'Presságio de Tempestade'
REPLACE INTO `item_buyingstore` VALUES (7090);  -- 'Murmúrio'
REPLACE INTO `item_buyingstore` VALUES (7091);  -- 'Tsunami'
REPLACE INTO `item_buyingstore` VALUES (7092);  -- 'Ar Silencioso'
REPLACE INTO `item_buyingstore` VALUES (7093);  -- 'Engrenagem'
REPLACE INTO `item_buyingstore` VALUES (7094);  -- 'Fragmento Misterioso'
REPLACE INTO `item_buyingstore` VALUES (7095);  -- 'Pedaço de Metal'
REPLACE INTO `item_buyingstore` VALUES (7096);  -- 'Pedra Pome'
REPLACE INTO `item_buyingstore` VALUES (7097);  -- 'Coração Incandescente'
REPLACE INTO `item_buyingstore` VALUES (7098);  -- 'Lenha em Brasa'
REPLACE INTO `item_buyingstore` VALUES (7099);  -- 'Pergaminho Antigo'
REPLACE INTO `item_buyingstore` VALUES (7100);  -- 'Folha Afiada'
REPLACE INTO `item_buyingstore` VALUES (7101);  -- 'Pena de Grand Peco'
REPLACE INTO `item_buyingstore` VALUES (7102);  -- 'Pedra do Pesadelo'
REPLACE INTO `item_buyingstore` VALUES (7103);  -- 'Essência de AXe'
REPLACE INTO `item_buyingstore` VALUES (7104);  -- 'Asas de Anjo Fajutas'
REPLACE INTO `item_buyingstore` VALUES (7105);  -- 'Auréola Fajuta'
REPLACE INTO `item_buyingstore` VALUES (7106);  -- 'Chifre de Bode'
REPLACE INTO `item_buyingstore` VALUES (7107);  -- 'Pele de Bode'
REPLACE INTO `item_buyingstore` VALUES (7108);  -- 'Pedaço de Escudo Colossal'
REPLACE INTO `item_buyingstore` VALUES (7109);  -- 'Lâmina de Lança Colossal'
REPLACE INTO `item_buyingstore` VALUES (7110);  -- 'Espada Chanfrada'
REPLACE INTO `item_buyingstore` VALUES (7111);  -- 'Pedaço de Papel'
REPLACE INTO `item_buyingstore` VALUES (7112);  -- 'Lâmina de Papel'
REPLACE INTO `item_buyingstore` VALUES (7113);  -- 'Cetro do Faraó'
REPLACE INTO `item_buyingstore` VALUES (7114);  -- 'Máscara do Faraó'
REPLACE INTO `item_buyingstore` VALUES (7115);  -- 'Pena de Harpia'
REPLACE INTO `item_buyingstore` VALUES (7116);  -- 'Garra de Harpia'
REPLACE INTO `item_buyingstore` VALUES (7117);  -- 'Velho Grimório'
REPLACE INTO `item_buyingstore` VALUES (7118);  -- 'Pergaminho Gasto'
REPLACE INTO `item_buyingstore` VALUES (7119);  -- 'Bactérias'
REPLACE INTO `item_buyingstore` VALUES (7120);  -- 'Ferradura em Chamas'
REPLACE INTO `item_buyingstore` VALUES (7121);  -- 'Pote de Mel'
REPLACE INTO `item_buyingstore` VALUES (7122);  -- 'Pelugem Incandescente'
REPLACE INTO `item_buyingstore` VALUES (7123);  -- 'Pele de Dragão'
REPLACE INTO `item_buyingstore` VALUES (7124);  -- 'Areia Molhada'
REPLACE INTO `item_buyingstore` VALUES (7125);  -- 'Pinças de Escorpião'
REPLACE INTO `item_buyingstore` VALUES (7126);  -- 'Jellopy Tamanho Família'
REPLACE INTO `item_buyingstore` VALUES (7127);  -- 'Manual de Criação Vol.2: Álcool'
REPLACE INTO `item_buyingstore` VALUES (7128);  -- 'Manual de Criação: Vol.3: Fogo Grego'
REPLACE INTO `item_buyingstore` VALUES (7129);  -- 'Manual de Criação: Vol.4: Ácidos'
REPLACE INTO `item_buyingstore` VALUES (7130);  -- 'Manual de Criação: Vol.5: Plantas'
REPLACE INTO `item_buyingstore` VALUES (7131);  -- 'Manual de Criação: Vol.6: Explosivos'
REPLACE INTO `item_buyingstore` VALUES (7132);  -- 'Manual de Criação: Vol.7: Revestimentos'
REPLACE INTO `item_buyingstore` VALUES (7133);  -- 'Manual de Criação: Vol.8: Poções Compactas'
REPLACE INTO `item_buyingstore` VALUES (7134);  -- 'Vasilha de Mistura'
REPLACE INTO `item_buyingstore` VALUES (7140);  -- 'Semente da Vida'
REPLACE INTO `item_buyingstore` VALUES (7141);  -- 'Orvalho da Yggdrasil'
REPLACE INTO `item_buyingstore` VALUES (7143);  -- 'Cápsula da Criação'
REPLACE INTO `item_buyingstore` VALUES (7144);  -- 'Manual de Criação: Vol.1: Poções Comuns'
REPLACE INTO `item_buyingstore` VALUES (7147);  -- 'Jasmim'
REPLACE INTO `item_buyingstore` VALUES (7149);  -- 'Prato Amarelado'
REPLACE INTO `item_buyingstore` VALUES (7150);  -- 'Pedaço de Bambu'
REPLACE INTO `item_buyingstore` VALUES (7151);  -- 'Papel Amarelado'
REPLACE INTO `item_buyingstore` VALUES (7152);  -- 'Cabelos Perfumados'
REPLACE INTO `item_buyingstore` VALUES (7153);  -- 'Velho Obi'
REPLACE INTO `item_buyingstore` VALUES (7154);  -- 'Poeira Venenosa'
REPLACE INTO `item_buyingstore` VALUES (7155);  -- 'Pele de Sapo'
REPLACE INTO `item_buyingstore` VALUES (7156);  -- 'Shuriken Despedaçado'
REPLACE INTO `item_buyingstore` VALUES (7157);  -- 'Máscara Ninja'
REPLACE INTO `item_buyingstore` VALUES (7158);  -- 'Jarro de Saquê'
REPLACE INTO `item_buyingstore` VALUES (7159);  -- 'Nariz de Tengu'
REPLACE INTO `item_buyingstore` VALUES (7160);  -- 'Passe Imperial'
REPLACE INTO `item_buyingstore` VALUES (7161);  -- 'Pele Negra de Urso'
REPLACE INTO `item_buyingstore` VALUES (7162);  -- 'Jarro de Nuvem'
REPLACE INTO `item_buyingstore` VALUES (7163);  -- 'Antenas Afiadas'
REPLACE INTO `item_buyingstore` VALUES (7164);  -- 'Pêssego Petrificado'
REPLACE INTO `item_buyingstore` VALUES (7165);  -- 'Manto Cerimonial Celestial'
REPLACE INTO `item_buyingstore` VALUES (7166);  -- 'Seda Macia'
REPLACE INTO `item_buyingstore` VALUES (7167);  -- 'Misterioso Metal em Pano'
REPLACE INTO `item_buyingstore` VALUES (7168);  -- 'Grandes Asas de Borboleta'
REPLACE INTO `item_buyingstore` VALUES (7169);  -- 'Ba Gua'
REPLACE INTO `item_buyingstore` VALUES (7170);  -- 'Smoking'
REPLACE INTO `item_buyingstore` VALUES (7171);  -- 'Pele de Leopardo'
REPLACE INTO `item_buyingstore` VALUES (7172);  -- 'Garras de Leopardo'
REPLACE INTO `item_buyingstore` VALUES (7174);  -- 'Laço para presente'
REPLACE INTO `item_buyingstore` VALUES (7175);  -- 'Papel de presente'
REPLACE INTO `item_buyingstore` VALUES (7182);  -- 'Cacau'
REPLACE INTO `item_buyingstore` VALUES (7186);  -- 'Cipó'
REPLACE INTO `item_buyingstore` VALUES (7187);  -- 'Máscara do Festival'
REPLACE INTO `item_buyingstore` VALUES (7188);  -- 'Raiz Marrom'
REPLACE INTO `item_buyingstore` VALUES (7189);  -- 'Coração de Madeira'
REPLACE INTO `item_buyingstore` VALUES (7190);  -- 'Casco de Inseto'
REPLACE INTO `item_buyingstore` VALUES (7191);  -- 'Lanterna'
REPLACE INTO `item_buyingstore` VALUES (7192);  -- 'Catavento'
REPLACE INTO `item_buyingstore` VALUES (7193);  -- 'Semente'
REPLACE INTO `item_buyingstore` VALUES (7194);  -- 'Grama'
REPLACE INTO `item_buyingstore` VALUES (7195);  -- 'Estilingue'
REPLACE INTO `item_buyingstore` VALUES (7196);  -- 'Ombreira'
REPLACE INTO `item_buyingstore` VALUES (7197);  -- 'Palha'
REPLACE INTO `item_buyingstore` VALUES (7198);  -- 'Folha Gigante'
REPLACE INTO `item_buyingstore` VALUES (7199);  -- 'Cupom Misterioso'
REPLACE INTO `item_buyingstore` VALUES (7200);  -- 'Elástico'
REPLACE INTO `item_buyingstore` VALUES (7201);  -- 'Tora'
REPLACE INTO `item_buyingstore` VALUES (7202);  -- 'Pata de Besouro'
REPLACE INTO `item_buyingstore` VALUES (7203);  -- 'Galho Resistente'
REPLACE INTO `item_buyingstore` VALUES (7204);  -- 'Pólvora'
REPLACE INTO `item_buyingstore` VALUES (7205);  -- 'Retalho Negro'
REPLACE INTO `item_buyingstore` VALUES (7206);  -- 'Boneco de Gato Preto'
REPLACE INTO `item_buyingstore` VALUES (7207);  -- 'Manteau Velho'
REPLACE INTO `item_buyingstore` VALUES (7208);  -- 'Faca Enferrujada'
REPLACE INTO `item_buyingstore` VALUES (7209);  -- 'Elmo de Dullahan'
REPLACE INTO `item_buyingstore` VALUES (7210);  -- 'Armadura de Dullahan'
REPLACE INTO `item_buyingstore` VALUES (7211);  -- 'Lasca de Pedra'
REPLACE INTO `item_buyingstore` VALUES (7212);  -- 'Boneca Enforcada'
REPLACE INTO `item_buyingstore` VALUES (7213);  -- 'Almofada de Alfinetes'
REPLACE INTO `item_buyingstore` VALUES (7214);  -- 'Gaiola de Morcegos'
REPLACE INTO `item_buyingstore` VALUES (7215);  -- 'Espeto Quebrado'
REPLACE INTO `item_buyingstore` VALUES (7216);  -- 'Cachecol Vermelho'
REPLACE INTO `item_buyingstore` VALUES (7217);  -- 'Carretel'
REPLACE INTO `item_buyingstore` VALUES (7218);  -- 'Corda Decomposta'
REPLACE INTO `item_buyingstore` VALUES (7219);  -- 'Meia Listrada'
REPLACE INTO `item_buyingstore` VALUES (7220);  -- 'Ectoplasma'
REPLACE INTO `item_buyingstore` VALUES (7221);  -- 'Corrente'
REPLACE INTO `item_buyingstore` VALUES (7222);  -- 'Coluna de Madeira'
REPLACE INTO `item_buyingstore` VALUES (7223);  -- 'Auto Retrato'
REPLACE INTO `item_buyingstore` VALUES (7225);  -- 'Lanterna de Abóbora'
REPLACE INTO `item_buyingstore` VALUES (7226);  -- 'Pílula'
REPLACE INTO `item_buyingstore` VALUES (7262);  -- 'Leque Fantasma'
REPLACE INTO `item_buyingstore` VALUES (7263);  -- 'Olho de Gato'
REPLACE INTO `item_buyingstore` VALUES (7264);  -- 'Areia Seca'
REPLACE INTO `item_buyingstore` VALUES (7265);  -- 'Chifre de Dragão'
REPLACE INTO `item_buyingstore` VALUES (7266);  -- 'Dentadura da Máscara do Dragão'
REPLACE INTO `item_buyingstore` VALUES (7267);  -- 'Tanga de Tigre'
REPLACE INTO `item_buyingstore` VALUES (7268);  -- 'Pequena Boneca Fantasma'
REPLACE INTO `item_buyingstore` VALUES (7269);  -- 'Babador'
REPLACE INTO `item_buyingstore` VALUES (7270);  -- 'Mamadeira'
REPLACE INTO `item_buyingstore` VALUES (7277);  -- 'Boneco de Munak'
REPLACE INTO `item_buyingstore` VALUES (7286);  -- 'Pimenta Vermelha'
REPLACE INTO `item_buyingstore` VALUES (7289);  -- 'Cristal de Peridoto'
REPLACE INTO `item_buyingstore` VALUES (7290);  -- 'Flogopita'
REPLACE INTO `item_buyingstore` VALUES (7291);  -- 'Ágata'
REPLACE INTO `item_buyingstore` VALUES (7292);  -- 'Moscovita'
REPLACE INTO `item_buyingstore` VALUES (7293);  -- 'Quartzo Rosa'
REPLACE INTO `item_buyingstore` VALUES (7294);  -- 'Turquesa'
REPLACE INTO `item_buyingstore` VALUES (7295);  -- 'Citrina'
REPLACE INTO `item_buyingstore` VALUES (7296);  -- 'Piroxênio'
REPLACE INTO `item_buyingstore` VALUES (7297);  -- 'Biotita'
REPLACE INTO `item_buyingstore` VALUES (7298);  -- 'Folha de Figo'
REPLACE INTO `item_buyingstore` VALUES (7299);  -- 'Cesto de Palha'
REPLACE INTO `item_buyingstore` VALUES (7300);  -- 'Pedras Preciosas'
REPLACE INTO `item_buyingstore` VALUES (7301);  -- 'Fitilhos'
REPLACE INTO `item_buyingstore` VALUES (7303);  -- 'Saco de Arroz'
REPLACE INTO `item_buyingstore` VALUES (7312);  -- 'Jubileu'
REPLACE INTO `item_buyingstore` VALUES (7315);  -- 'Fragmento de Cristal Negro'
REPLACE INTO `item_buyingstore` VALUES (7316);  -- 'Perna de Inseto'
REPLACE INTO `item_buyingstore` VALUES (7317);  -- 'Parafuso Enferrujado'
REPLACE INTO `item_buyingstore` VALUES (7318);  -- 'Picareta Velha'
REPLACE INTO `item_buyingstore` VALUES (7319);  -- 'Placa de Ferro Usada'
REPLACE INTO `item_buyingstore` VALUES (7320);  -- 'Poeira Poluente'
REPLACE INTO `item_buyingstore` VALUES (7321);  -- 'Fragmento de Cristal'
REPLACE INTO `item_buyingstore` VALUES (7322);  -- 'Gás Tóxico'
REPLACE INTO `item_buyingstore` VALUES (7323);  -- 'Chaleira Surrada'
REPLACE INTO `item_buyingstore` VALUES (7325);  -- 'Tubo Flexível'
REPLACE INTO `item_buyingstore` VALUES (7326);  -- 'Líquido Fluorescente'
REPLACE INTO `item_buyingstore` VALUES (7327);  -- 'Lanterna de Capacete'
REPLACE INTO `item_buyingstore` VALUES (7340);  -- 'Desejo das Trevas'
REPLACE INTO `item_buyingstore` VALUES (7345);  -- 'Algemas'
REPLACE INTO `item_buyingstore` VALUES (7352);  -- 'Prato Transparente'
REPLACE INTO `item_buyingstore` VALUES (7353);  -- 'Prato Transparente'
REPLACE INTO `item_buyingstore` VALUES (7354);  -- 'Prato Transparente'
REPLACE INTO `item_buyingstore` VALUES (7355);  -- 'Prato Transparente'
REPLACE INTO `item_buyingstore` VALUES (7356);  -- 'Pedaço de Crista'
REPLACE INTO `item_buyingstore` VALUES (7357);  -- 'Pedaço de Crista'
REPLACE INTO `item_buyingstore` VALUES (7358);  -- 'Pedaço de Crista'
REPLACE INTO `item_buyingstore` VALUES (7359);  -- 'Pedaço de Crista'
REPLACE INTO `item_buyingstore` VALUES (7419);  -- 'Guia de Criação de Embriões'
REPLACE INTO `item_buyingstore` VALUES (7433);  -- 'Pergaminho em Branco'
REPLACE INTO `item_buyingstore` VALUES (7434);  -- 'Guia de Criação de Poções Elementais'
REPLACE INTO `item_buyingstore` VALUES (7435);  -- 'Ornamento Dourado'
REPLACE INTO `item_buyingstore` VALUES (7436);  -- 'Fragmento de Agonia'
REPLACE INTO `item_buyingstore` VALUES (7437);  -- 'Fragmento de Desgraça'
REPLACE INTO `item_buyingstore` VALUES (7438);  -- 'Fragmento de Ódio'
REPLACE INTO `item_buyingstore` VALUES (7439);  -- 'Fragmento de Desespero'
REPLACE INTO `item_buyingstore` VALUES (7440);  -- 'Pena Vermelha'
REPLACE INTO `item_buyingstore` VALUES (7441);  -- 'Pena Azul'
REPLACE INTO `item_buyingstore` VALUES (7442);  -- 'Selo Maldito'
REPLACE INTO `item_buyingstore` VALUES (7443);  -- 'Cabeça de Dragão de Três Cabeças'
REPLACE INTO `item_buyingstore` VALUES (7444);  -- 'Arca de Tesouro'
REPLACE INTO `item_buyingstore` VALUES (7445);  -- 'Bijuteria Verde'
REPLACE INTO `item_buyingstore` VALUES (7446);  -- 'Bijuteria Azul'
REPLACE INTO `item_buyingstore` VALUES (7447);  -- 'Bijuteria Vermelha'
REPLACE INTO `item_buyingstore` VALUES (7448);  -- 'Bijuteria Amarela'
REPLACE INTO `item_buyingstore` VALUES (7449);  -- 'Página Sangrenta'
REPLACE INTO `item_buyingstore` VALUES (7450);  -- 'Peça de Armadura de Esqueleto'
REPLACE INTO `item_buyingstore` VALUES (7451);  -- 'Escama de Dragão de Fogo'
REPLACE INTO `item_buyingstore` VALUES (7452);  -- 'Condimento Amarelo'
REPLACE INTO `item_buyingstore` VALUES (7453);  -- 'Molho Doce'
REPLACE INTO `item_buyingstore` VALUES (7454);  -- 'Molho Saboroso'
REPLACE INTO `item_buyingstore` VALUES (7455);  -- 'Molho Picante'
REPLACE INTO `item_buyingstore` VALUES (7456);  -- 'Condimento Vermelho'
REPLACE INTO `item_buyingstore` VALUES (7457);  -- 'Óleo de Cozinha'
REPLACE INTO `item_buyingstore` VALUES (7472);  -- 'Livro de Culinária Nível 1'
REPLACE INTO `item_buyingstore` VALUES (7473);  -- 'Livro de Culinária Nível 2'
REPLACE INTO `item_buyingstore` VALUES (7474);  -- 'Livro de Culinária Nível 3'
REPLACE INTO `item_buyingstore` VALUES (7475);  -- 'Livro de Culinária Nível 4'
REPLACE INTO `item_buyingstore` VALUES (7476);  -- 'Livro de Culinária Nível 5'
REPLACE INTO `item_buyingstore` VALUES (7477);  -- 'Livro de Culinária Nível 6'
REPLACE INTO `item_buyingstore` VALUES (7478);  -- 'Livro de Culinária Nível 7'
REPLACE INTO `item_buyingstore` VALUES (7479);  -- 'Livro de Culinária Nível 8'
REPLACE INTO `item_buyingstore` VALUES (7480);  -- 'Livro de Culinária Nível 9'
REPLACE INTO `item_buyingstore` VALUES (7481);  -- 'Livro de Culinária Nível 10'
REPLACE INTO `item_buyingstore` VALUES (7482);  -- 'Panela'
REPLACE INTO `item_buyingstore` VALUES (7507);  -- 'Pedaço de Ferro Sólido'
REPLACE INTO `item_buyingstore` VALUES (7510);  -- 'Flor de Valhalla'
REPLACE INTO `item_buyingstore` VALUES (7511);  -- 'Runa da Escuridão'
REPLACE INTO `item_buyingstore` VALUES (7512);  -- 'Peça Queimada'
REPLACE INTO `item_buyingstore` VALUES (7513);  -- 'Relógio de Bolso'
REPLACE INTO `item_buyingstore` VALUES (7521);  -- 'Pedra do Fogo'
REPLACE INTO `item_buyingstore` VALUES (7522);  -- 'Pedra do Gelo'
REPLACE INTO `item_buyingstore` VALUES (7523);  -- 'Pedra do Vento'
REPLACE INTO `item_buyingstore` VALUES (7524);  -- 'Esfera das Sombras'
REPLACE INTO `item_buyingstore` VALUES (7561);  -- 'Coração Glacial'
REPLACE INTO `item_buyingstore` VALUES (7562);  -- 'Escama de Gelo'
REPLACE INTO `item_buyingstore` VALUES (7563);  -- 'Runa Sangrenta'
REPLACE INTO `item_buyingstore` VALUES (7564);  -- 'Carne Estragada'
REPLACE INTO `item_buyingstore` VALUES (7565);  -- 'Veneno Pegajoso'
REPLACE INTO `item_buyingstore` VALUES (7566);  -- 'Desejo das Trevas Escarlate'
REPLACE INTO `item_buyingstore` VALUES (7567);  -- 'Chapéu Suspeito'
REPLACE INTO `item_buyingstore` VALUES (7568);  -- 'Máscara Branca'
REPLACE INTO `item_buyingstore` VALUES (7574);  -- 'Pó Glacial'
REPLACE INTO `item_buyingstore` VALUES (7751);  -- 'Velha Vestimenta Branca'
REPLACE INTO `item_buyingstore` VALUES (7752);  -- 'Crânio Atordoante'
REPLACE INTO `item_buyingstore` VALUES (7753);  -- 'Utensílio Rural Quebrado'
REPLACE INTO `item_buyingstore` VALUES (7754);  -- 'Coroa Quebrada'
REPLACE INTO `item_buyingstore` VALUES (7830);  -- 'Lágrima da Deusa'
REPLACE INTO `item_buyingstore` VALUES (7831);  -- 'Símbolo da Valquíria'
REPLACE INTO `item_buyingstore` VALUES (7832);  -- 'Pedaço de Vestimenta'
REPLACE INTO `item_buyingstore` VALUES (7833);  -- 'Cinzas de Herói'
REPLACE INTO `item_buyingstore` VALUES (7834);  -- 'Anel de Andvari'
REPLACE INTO `item_buyingstore` VALUES (7835);  -- 'Crepúsculo Vermelho'
REPLACE INTO `item_buyingstore` VALUES (7836);  -- 'Essência do Alvorecer'
REPLACE INTO `item_buyingstore` VALUES (7837);  -- 'Luar Gélido'
REPLACE INTO `item_buyingstore` VALUES (7838);  -- 'Constelação Obscura'
REPLACE INTO `item_buyingstore` VALUES (7931);  -- 'Kit de Veneno'
REPLACE INTO `item_buyingstore` VALUES (7932);  -- 'Nerium'
REPLACE INTO `item_buyingstore` VALUES (7933);  -- 'Lantana'
REPLACE INTO `item_buyingstore` VALUES (7934);  -- 'Makulrata'
REPLACE INTO `item_buyingstore` VALUES (7935);  -- 'Celatom'
REPLACE INTO `item_buyingstore` VALUES (7936);  -- 'Scoforia'
REPLACE INTO `item_buyingstore` VALUES (7937);  -- 'Amoena'
REPLACE INTO `item_buyingstore` VALUES (7938);  -- 'Partículas de Luz'
REPLACE INTO `item_buyingstore` VALUES (7939);  -- 'Galho Antigo'
REPLACE INTO `item_buyingstore` VALUES (7940);  -- 'Armadilha Especial'
REPLACE INTO `item_buyingstore` VALUES (11000);  -- 'História de Prontera'
REPLACE INTO `item_buyingstore` VALUES (11001);  -- 'Histórias de Aventura Vol.1'
REPLACE INTO `item_buyingstore` VALUES (11002);  -- 'Mestre-Cuca Orleans Vol.1'
REPLACE INTO `item_buyingstore` VALUES (11003);  -- 'Lendas das Kafras Vol.1'
REPLACE INTO `item_buyingstore` VALUES (11004);  -- 'Livro Antigo'
REPLACE INTO `item_buyingstore` VALUES (11005);  -- 'A Família Real de Rune-Midgard'
REPLACE INTO `item_buyingstore` VALUES (11006);  -- 'Flores de Sangue Vol.1'
REPLACE INTO `item_buyingstore` VALUES (11007);  -- 'Flores de Sangue Vol.2'
REPLACE INTO `item_buyingstore` VALUES (11008);  -- 'Dicionário Biográfico'
REPLACE INTO `item_buyingstore` VALUES (11009);  -- 'Histórias de Aventura Vol.2'
REPLACE INTO `item_buyingstore` VALUES (11020);  -- 'Japanese Book 1'
REPLACE INTO `item_buyingstore` VALUES (11021);  -- 'Japanese Book 2'
REPLACE INTO `item_buyingstore` VALUES (11022);  -- 'Livro de Culinária Avançada'
REPLACE INTO `item_buyingstore` VALUES (11023);  -- 'Como Aumentar sua Força'
REPLACE INTO `item_buyingstore` VALUES (11024);  -- 'Como Aumentar sua Energia