--
-- Estrutura para a tabela `mercenary_skill_db`
--    

CREATE TABLE IF NOT EXISTS `mercenary_skill_db` (
	`MercenaryID` mediumint(9) unsigned NOT NULL default '0',
	`SkillID` mediumint(9) unsigned NOT NULL default '0',
	`SkillLevel` tinyint(4) unsigned NOT NULL default '0',
	PRIMARY KEY (`SkillID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

#
# Habilidades de Assistentes.
# Descrição: Responsável pelo banco de dados de habilidades dos assistentes mercenários.
# Cabeçalho: REPLACE INTO `mercenary_skill_db` VALUES ('ID do Assistente','ID da Habilidade','Nível da Habilidade');
# 

REPLACE INTO `mercenary_skill_db` VALUES (6017,8207,2);			# 'MA_DOUBLE = Rajada de Flechas'
REPLACE INTO `mercenary_skill_db` VALUES (6017,8233,1);			# 'MER_AUTOBERSERK = Instinto de Sobrevivência Automático'
REPLACE INTO `mercenary_skill_db` VALUES (6018,8208,2);			# 'MA_SHOWER = Chuva de Flechas'
REPLACE INTO `mercenary_skill_db` VALUES (6018,8224,1);			# 'MER_SIGHT = Chama Reveladora'
REPLACE INTO `mercenary_skill_db` VALUES (6019,8214,1);			# 'MA_CHARGEARROW = Carregar Flechas'
REPLACE INTO `mercenary_skill_db` VALUES (6019,8223,1);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (6020,8237,1);			# 'MER_ESTIMATION = Propriedades do Monstro'
REPLACE INTO `mercenary_skill_db` VALUES (6020,8222,1);			# 'MER_MAGNIFICAT = Magnificat'
REPLACE INTO `mercenary_skill_db` VALUES (6020,8227,1);			# 'MER_TENDER = Amolecer'
REPLACE INTO `mercenary_skill_db` VALUES (6021,8207,5);			# 'MA_DOUBLE = Rajada de Flechas'
REPLACE INTO `mercenary_skill_db` VALUES (6021,8232,1);			# 'MER_PROVOKE = Provocar'
REPLACE INTO `mercenary_skill_db` VALUES (6021,8213,1);			# 'MA_REMOVETRAP = Remover Armadilha'
REPLACE INTO `mercenary_skill_db` VALUES (6022,8207,7);			# 'MA_DOUBLE = Rajada de Flechas'
REPLACE INTO `mercenary_skill_db` VALUES (6022,8209,3);			# 'MA_SKIDTRAP = Armadilha Escorregadia'
REPLACE INTO `mercenary_skill_db` VALUES (6022,8234,1);			# 'MER_DECAGI = Diminuir Agilidade'
REPLACE INTO `mercenary_skill_db` VALUES (6023,8208,10);		# 'MA_SHOWER = Chuva de Flechas'
REPLACE INTO `mercenary_skill_db` VALUES (6023,8230,1);			# 'MER_MENTALCURE = Cura Mental'
REPLACE INTO `mercenary_skill_db` VALUES (6023,8212,2);			# 'MA_FREEZINGTRAP = Armadilha Congelante'
REPLACE INTO `mercenary_skill_db` VALUES (6024,8223,2);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (6024,8232,3);			# 'MER_PROVOKE = Provocar'
REPLACE INTO `mercenary_skill_db` VALUES (6024,8211,3);			# 'MA_SANDMAN = Armadilha Sonífera'
REPLACE INTO `mercenary_skill_db` VALUES (6025,8207,10);		# 'MA_DOUBLE = Rajada de Flechas'
REPLACE INTO `mercenary_skill_db` VALUES (6025,8214,1);			# 'MA_CHARGEARROW = Carregar Flechas'
REPLACE INTO `mercenary_skill_db` VALUES (6025,8210,5);			# 'MA_LANDMINE = Armadilha Atordoante'
REPLACE INTO `mercenary_skill_db` VALUES (6026,8214,1);			# 'MA_CHARGEARROW = Carregar Flechas'
REPLACE INTO `mercenary_skill_db` VALUES (6026,8215,5);			# 'MA_SHARPSHOOTING = Disparo Violento'
REPLACE INTO `mercenary_skill_db` VALUES (6026,8223,5);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (6026,8233,1);			# 'MER_AUTOBERSERK = Instinto de Sobrevivência Automático'
REPLACE INTO `mercenary_skill_db` VALUES (6027,8216,1);			# 'ML_PIERCE = Perfurar'
REPLACE INTO `mercenary_skill_db` VALUES (6027,8226,1);			# 'MER_REGAIN = Recompor'
REPLACE INTO `mercenary_skill_db` VALUES (6028,8217,2);			# 'ML_BRANDISH = Brandir Lança'
REPLACE INTO `mercenary_skill_db` VALUES (6028,8236,1);			# 'MER_LEXDIVINA = Lex Divina'
REPLACE INTO `mercenary_skill_db` VALUES (6029,8216,2);			# 'ML_PIERCE = Perfurar'
REPLACE INTO `mercenary_skill_db` VALUES (6029,8221,1);			# 'ML_DEVOTION = Devoção'
REPLACE INTO `mercenary_skill_db` VALUES (6029,8229,1);			# 'MER_RECUPERATE = Restabelecer'
REPLACE INTO `mercenary_skill_db` VALUES (6030,8219,1);			# 'ML_DEFENDER = Aura Sagrada'
REPLACE INTO `mercenary_skill_db` VALUES (6030,8225,4);			# 'MER_CRASH = Impacto'
REPLACE INTO `mercenary_skill_db` VALUES (6031,8216,5);			# 'ML_PIERCE = Perfurar'
REPLACE INTO `mercenary_skill_db` VALUES (6031,8220,3);			# 'ML_AUTOGUARD = Bloqueio'
REPLACE INTO `mercenary_skill_db` VALUES (6032,8223,2);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (6032,8217,5);			# 'ML_BRANDISH = Brandir Lança'
REPLACE INTO `mercenary_skill_db` VALUES (6033,8221,1);			# 'ML_DEVOTION = Devoção'
REPLACE INTO `mercenary_skill_db` VALUES (6033,8233,1);			# 'MER_AUTOBERSERK = Instinto de Sobrevivência Automático'
REPLACE INTO `mercenary_skill_db` VALUES (6034,8235,1);			# 'MER_SCAPEGOAT = Bode Expiatório'
REPLACE INTO `mercenary_skill_db` VALUES (6034,8216,10);		# 'ML_PIERCE = Perfurar'
REPLACE INTO `mercenary_skill_db` VALUES (6034,8232,5);			# 'MER_PROVOKE = Provocar'
REPLACE INTO `mercenary_skill_db` VALUES (6035,8217,10);		# 'ML_BRANDISH = Brandir Lança'
REPLACE INTO `mercenary_skill_db` VALUES (6035,8220,7);			# 'ML_AUTOGUARD = Bloqueio'
REPLACE INTO `mercenary_skill_db` VALUES (6035,8219,3);			# 'ML_DEFENDER = Aura Sagrada'
REPLACE INTO `mercenary_skill_db` VALUES (6036,8223,5);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (6036,8220,10);		# 'ML_AUTOGUARD = Bloqueio'
REPLACE INTO `mercenary_skill_db` VALUES (6036,8221,3);			# 'ML_DEVOTION = Devoção'
REPLACE INTO `mercenary_skill_db` VALUES (6036,8218,5);			# 'ML_SPIRALPIERCE = Perfurar em Espiral'
REPLACE INTO `mercenary_skill_db` VALUES (6037,8201,1);			# 'MS_BASH = Golpe Fulminante'
REPLACE INTO `mercenary_skill_db` VALUES (6037,8234,1);			# 'MER_DECAGI = Diminuir Agilidade'
REPLACE INTO `mercenary_skill_db` VALUES (6038,8232,5);			# 'MER_PROVOKE = Provocar'
REPLACE INTO `mercenary_skill_db` VALUES (6038,8202,3);			# 'MS_MAGNUM = Impacto Explosivo'
REPLACE INTO `mercenary_skill_db` VALUES (6039,8223,1);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (6039,8228,1);			# 'MER_BENEDICTION = Bendição'
REPLACE INTO `mercenary_skill_db` VALUES (6040,8225,1);			# 'MER_CRASH = Impacto'
REPLACE INTO `mercenary_skill_db` VALUES (6040,8202,5);			# 'MS_MAGNUM = Impacto Explosivo'
REPLACE INTO `mercenary_skill_db` VALUES (6041,8201,5);			# 'MS_BASH = Golpe Fulminante'
REPLACE INTO `mercenary_skill_db` VALUES (6041,8225,4);			# 'MER_CRASH = Impacto'
REPLACE INTO `mercenary_skill_db` VALUES (6041,8228,1);			# 'MER_BENEDICTION = Bendição'
REPLACE INTO `mercenary_skill_db` VALUES (6042,8223,5);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (6042,8237,1);			# 'MER_ESTIMATION = Propriedades do Monstro'
REPLACE INTO `mercenary_skill_db` VALUES (6042,8234,3);			# 'MER_DECAGI = Diminuir Agilidade'
REPLACE INTO `mercenary_skill_db` VALUES (6043,8201,10);		# 'MS_BASH = Golpe Fulminante'
REPLACE INTO `mercenary_skill_db` VALUES (6043,8233,1);			# 'MER_AUTOBERSERK = Instinto de Sobrevivência Automático'
REPLACE INTO `mercenary_skill_db` VALUES (6043,8235,1);			# 'MER_SCAPEGOAT = Bode Expiatório'
REPLACE INTO `mercenary_skill_db` VALUES (6044,8223,10);		# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (6044,8203,5);			# 'MS_BOWLINGABASH = Impacto de Tyr'
REPLACE INTO `mercenary_skill_db` VALUES (6044,8231,1);			# 'MER_COMPRESS = Compressa'
REPLACE INTO `mercenary_skill_db` VALUES (6044,8204,4);			# 'MS_PARRYING = Aparar Golpe'
REPLACE INTO `mercenary_skill_db` VALUES (6045,8203,8);			# 'MS_BOWLINGABASH = Impacto de Tyr'
REPLACE INTO `mercenary_skill_db` VALUES (6045,8225,3);			# 'MER_CRASH = Impacto'
REPLACE INTO `mercenary_skill_db` VALUES (6045,8205,5);			# 'MS_REFLECTSHIELD = Escudo Refletor'
REPLACE INTO `mercenary_skill_db` VALUES (6046,8223,10);		# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (6046,8203,10);		# 'MS_BOWLINGABASH = Impacto de Tyr'
REPLACE INTO `mercenary_skill_db` VALUES (6046,8201,10);		# 'MS_BASH = Golpe Fulminante'
REPLACE INTO `mercenary_skill_db` VALUES (6046,8206,1);			# 'MS_BERSERK = Fúria Insana'
REPLACE INTO `mercenary_skill_db` VALUES (1191,8233,1);			# 'MER_AUTOBERSERK = Instinto de Sobrevivência Automático'
REPLACE INTO `mercenary_skill_db` VALUES (1191,8220,5);			# 'ML_AUTOGUARD = Bloqueio'
REPLACE INTO `mercenary_skill_db` VALUES (1191,8201,5);			# 'MS_BASH = Golpe Fulminante'
REPLACE INTO `mercenary_skill_db` VALUES (1506,8223,2);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (1506,8225,5);			# 'MER_CRASH = Impacto'
REPLACE INTO `mercenary_skill_db` VALUES (1506,8236,3);			# 'MER_LEXDIVINA = Lex Divina'
REPLACE INTO `mercenary_skill_db` VALUES (1275,8232,5);			# 'MER_PROVOKE = Provocar'
REPLACE INTO `mercenary_skill_db` VALUES (1275,8202,5);			# 'MS_MAGNUM = Impacto Explosivo'
REPLACE INTO `mercenary_skill_db` VALUES (1275,8217,5);			# 'ML_BRANDISH = Brandir Lança'
REPLACE INTO `mercenary_skill_db` VALUES (1275,8226,1);			# 'MER_REGAIN = Recompor'
REPLACE INTO `mercenary_skill_db` VALUES (1965,8201,5);			# 'MS_BASH = Golpe Fulminante'
REPLACE INTO `mercenary_skill_db` VALUES (1966,8223,5);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (1966,8201,5);			# 'MS_BASH = Golpe Fulminante'
REPLACE INTO `mercenary_skill_db` VALUES (1966,8221,3);			# 'ML_DEVOTION = Devoção'
REPLACE INTO `mercenary_skill_db` VALUES (1967,8223,5);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (1967,8201,5);			# 'MS_BASH = Golpe Fulminante'
REPLACE INTO `mercenary_skill_db` VALUES (1967,8221,3);			# 'ML_DEVOTION = Devoção'
REPLACE INTO `mercenary_skill_db` VALUES (2000,8226,1);			# 'MER_REGAIN = Recompor'
REPLACE INTO `mercenary_skill_db` VALUES (2000,8227,1);			# 'MER_TENDER = Amolecer'
REPLACE INTO `mercenary_skill_db` VALUES (2000,8238,5);			# 'MER_KYRIE = Kyrie Eleison'
REPLACE INTO `mercenary_skill_db` VALUES (2000,8239,5);			# 'MER_BLESSING = Benção'
REPLACE INTO `mercenary_skill_db` VALUES (2000,8240,5);			# 'MER_INCAGI = Aumentar Agilidade'
REPLACE INTO `mercenary_skill_db` VALUES (2001,8226,1);			# 'MER_REGAIN = Recompor'
REPLACE INTO `mercenary_skill_db` VALUES (2001,8227,1);			# 'MER_TENDER = Amolecer'
REPLACE INTO `mercenary_skill_db` VALUES (2001,8238,5);			# 'MER_KYRIE = Kyrie Eleison'
REPLACE INTO `mercenary_skill_db` VALUES (2001,8239,5);			# 'MER_BLESSING = Benção'
REPLACE INTO `mercenary_skill_db` VALUES (2001,8240,5);			# 'MER_INCAGI = Aumentar Agilidade'
REPLACE INTO `mercenary_skill_db` VALUES (2058,8233,1);			# 'MER_AUTOBERSERK = Instinto de Sobrevivência Automático'
REPLACE INTO `mercenary_skill_db` VALUES (2058,8220,5);			# 'ML_AUTOGUARD = Bloqueio'
REPLACE INTO `mercenary_skill_db` VALUES (2058,8201,5);			# 'MS_BASH = Golpe Fulminante'
REPLACE INTO `mercenary_skill_db` VALUES (2059,8223,2);			# 'MER_QUICKEN = Rapidez com Arma'
REPLACE INTO `mercenary_skill_db` VALUES (2059,8225,5);			# 'MER_CRASH = Impacto'
REPLACE INTO `mercenary_skill_db` VALUES (2059,8236,3);			# 'MER_LEXDIVINA = Lex Divina'
REPLACE INTO `mercenary_skill_db` VALUES (2060,8232,5);			# 'MER_PROVOKE = Provocar'
REPLACE INTO `mercenary_skill_db` VALUES (2060,8202,5);			# 'MS_MAGNUM = Impacto Explosivo'
REPLACE INTO `mercenary_skill_db` VALUES (2060,8217,5);			# 'ML_BRANDISH = Brandir Lança'
REPLACE INTO `mercenary_skill_db` VALUES (2060,8226,1);			# 'MER_REGAIN = Recompor'
